<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Tests\Controllers;

use DockerLib\Controllers\AccessTokensController;
use DockerLib\Exceptions;

class AccessTokensControllerTest extends BaseTestController
{
    /**
     * @var AccessTokensController AccessTokensController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getAccessTokensController();
    }

    public function testGetalistofpersonalaccesstokens()
    {
        // Parameters for the API call
        $page = 1;
        $pageSize = 10;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->getalistofpersonalaccesstokens($page, $pageSize);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
