<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use DockerLib\Controllers\SystemController;
use DockerLib\Exceptions;

class SystemControllerTest extends BaseTestController
{
    /**
     * @var SystemController SystemController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getSystemController();
    }

    public function testSystemPing()
    {
        // Perform API call
        $result = null;
        try {
            $result = self::$controller->systemPing();
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['API-Version'] = ["", false];
        $headers['Docker-Experimental'] = ["", false];
        $headers['Content-Type'] = ['text/plain', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testSystemAuth()
    {
        // Parameters for the API call
        $body = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->systemAuth($body);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(
                TestParam::object('{"IdentityToken":"9cbaf023786cd7...","Status":"Login Succeeded"}')
            ))
            ->assert();
    }

    public function testSystemAuth1()
    {
        // Parameters for the API call
        $body = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->systemAuth($body);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(204)->assert();
    }

    public function testSystemEvents()
    {
        // Parameters for the API call
        $since = null;
        $until = null;
        $filters = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->systemEvents($since, $until, $filters);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"Action":"create","Actor":{"Attributes":{"com.example.some-label":"some-label' .
                '-value","image":"alpine","name":"my-container"},"ID":"ede54ee1afda366ab42f824e8' .
                'a5ffd195155d853ceaec74a927f249ea270c743"},"Type":"container","time":1461943101}' .
                ''
            )))
            ->assert();
    }

    public function testSystemInfo()
    {
        // Perform API call
        $result = null;
        try {
            $result = self::$controller->systemInfo();
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testSystemDataUsage()
    {
        // Perform API call
        $result = null;
        try {
            $result = self::$controller->systemDataUsage();
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testSystemDataUsage1()
    {
        // Perform API call
        $result = null;
        try {
            $result = self::$controller->systemDataUsage();
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['text/plain', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testSystemVersion()
    {
        // Perform API call
        $result = null;
        try {
            $result = self::$controller->systemVersion();
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"ApiVersion":"1.27","Arch":"amd64","BuildTime":"2016-06-14T07:09:13.444803460' .
                '+00:00","Experimental":true,"GitCommit":"deadbee","GoVersion":"go1.7.5","Kernel' .
                'Version":"3.19.0-23-generic","MinAPIVersion":"1.12","Os":"linux","Version":"17.' .
                '04.0"}'
            )))
            ->assert();
    }
}
