<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use DockerLib\Controllers\TaskController;
use DockerLib\Exceptions;

class TaskControllerTest extends BaseTestController
{
    /**
     * @var TaskController TaskController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getTaskController();
    }

    public function testTaskList()
    {
        // Parameters for the API call
        $filters = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->taskList($filters);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '[{"CreatedAt":"2016-06-07T21:07:31.171892745Z","DesiredState":"running","ID":"' .
                '0kzzo1i0y4jz6027t0k7aezc7","NetworksAttachments":[{"Addresses":["10.255.0.10/16' .
                '"],"Network":{"CreatedAt":"2016-06-07T20:31:11.912919752Z","DriverState":{"Name' .
                '":"overlay","Options":{"com.docker.network.driver.overlay.vxlanid_list":"256"}}' .
                ',"ID":"4qvuz4ko70xaltuqbt8956gd1","IPAMOptions":{"Configs":[{"Gateway":"10.255.' .
                '0.1","Subnet":"10.255.0.0/16"}],"Driver":{"Name":"default"}},"Spec":{"DriverCon' .
                'figuration":{},"IPAMOptions":{"Configs":[{"Gateway":"10.255.0.1","Subnet":"10.2' .
                '55.0.0/16"}],"Driver":{}},"Labels":{"com.docker.swarm.internal":"true"},"Name":' .
                '"ingress"},"UpdatedAt":"2016-06-07T21:07:29.955277358Z","Version":{"Index":18}}' .
                '}],"NodeID":"60gvrl6tm78dmak4yl7srz94v","ServiceID":"9mnpnzenvg8p8tdbtq4wvbkcz"' .
                ',"Slot":1,"Spec":{"ContainerSpec":{"Image":"redis"},"Placement":{},"Resources":' .
                '{"Limits":{},"Reservations":{}},"RestartPolicy":{"Condition":"any","MaxAttempts' .
                '":0}},"Status":{"ContainerStatus":{"ContainerID":"e5d62702a1b48d01c3e02ca1e0212' .
                'a250801fa8d67caca0b6f35919ebc12f035","PID":677},"Message":"started","State":"ru' .
                'nning","Timestamp":"2016-06-07T21:07:31.290032978Z"},"UpdatedAt":"2016-06-07T21' .
                ':07:31.376370513Z","Version":{"Index":71}},{"CreatedAt":"2016-06-07T21:07:30.01' .
                '9104782Z","DesiredState":"shutdown","ID":"1yljwbmlr8er2waf8orvqpwms","Name":"ho' .
                'peful_cori","NetworksAttachments":[{"Addresses":["10.255.0.5/16"],"Network":{"C' .
                'reatedAt":"2016-06-07T20:31:11.912919752Z","DriverState":{"Name":"overlay","Opt' .
                'ions":{"com.docker.network.driver.overlay.vxlanid_list":"256"}},"ID":"4qvuz4ko7' .
                '0xaltuqbt8956gd1","IPAMOptions":{"Configs":[{"Gateway":"10.255.0.1","Subnet":"1' .
                '0.255.0.0/16"}],"Driver":{"Name":"default"}},"Spec":{"DriverConfiguration":{},"' .
                'IPAMOptions":{"Configs":[{"Gateway":"10.255.0.1","Subnet":"10.255.0.0/16"}],"Dr' .
                'iver":{}},"Labels":{"com.docker.swarm.internal":"true"},"Name":"ingress"},"Upda' .
                'tedAt":"2016-06-07T21:07:29.955277358Z","Version":{"Index":18}}}],"NodeID":"60g' .
                'vrl6tm78dmak4yl7srz94v","ServiceID":"9mnpnzenvg8p8tdbtq4wvbkcz","Slot":1,"Spec"' .
                ':{"ContainerSpec":{"Image":"redis"},"Placement":{},"Resources":{"Limits":{},"Re' .
                'servations":{}},"RestartPolicy":{"Condition":"any","MaxAttempts":0}},"Status":{' .
                '"ContainerStatus":{"ContainerID":"1cf8d63d18e79668b0004a4be4c6ee58cddfad2dae295' .
                '06d8781581d0688a213"},"Message":"shutdown","State":"shutdown","Timestamp":"2016' .
                '-06-07T21:07:30.202183143Z"},"UpdatedAt":"2016-06-07T21:07:30.231958098Z","Vers' .
                'ion":{"Index":30}}]'
            )))
            ->assert();
    }
}
