<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\AccessToken;

/**
 * Builder for model AccessToken
 *
 * @see AccessToken
 */
class AccessTokenBuilder
{
    /**
     * @var AccessToken
     */
    private $instance;

    private function __construct(AccessToken $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Access Token Builder object.
     */
    public static function init(): self
    {
        return new self(new AccessToken());
    }

    /**
     * Sets client id field.
     *
     * @param string|null $value
     */
    public function clientId(?string $value): self
    {
        $this->instance->setClientId($value);
        return $this;
    }

    /**
     * Sets created at field.
     *
     * @param string|null $value
     */
    public function createdAt(?string $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets creator ip field.
     *
     * @param string|null $value
     */
    public function creatorIp(?string $value): self
    {
        $this->instance->setCreatorIp($value);
        return $this;
    }

    /**
     * Sets creator ua field.
     *
     * @param string|null $value
     */
    public function creatorUa(?string $value): self
    {
        $this->instance->setCreatorUa($value);
        return $this;
    }

    /**
     * Sets generated by field.
     *
     * @param string|null $value
     */
    public function generatedBy(?string $value): self
    {
        $this->instance->setGeneratedBy($value);
        return $this;
    }

    /**
     * Sets is active field.
     *
     * @param bool|null $value
     */
    public function isActive(?bool $value): self
    {
        $this->instance->setIsActive($value);
        return $this;
    }

    /**
     * Sets last used field.
     *
     * @param string|null $value
     */
    public function lastUsed(?string $value): self
    {
        $this->instance->setLastUsed($value);
        return $this;
    }

    /**
     * Unsets last used field.
     */
    public function unsetLastUsed(): self
    {
        $this->instance->unsetLastUsed();
        return $this;
    }

    /**
     * Sets scopes field.
     *
     * @param string[]|null $value
     */
    public function scopes(?array $value): self
    {
        $this->instance->setScopes($value);
        return $this;
    }

    /**
     * Sets token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Sets token label field.
     *
     * @param string|null $value
     */
    public function tokenLabel(?string $value): self
    {
        $this->instance->setTokenLabel($value);
        return $this;
    }

    /**
     * Sets uuid field.
     *
     * @param string|null $value
     */
    public function uuid(?string $value): self
    {
        $this->instance->setUuid($value);
        return $this;
    }

    /**
     * Initializes a new Access Token object.
     */
    public function build(): AccessToken
    {
        return CoreHelper::clone($this->instance);
    }
}
