<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Address;

/**
 * Builder for model Address
 *
 * @see Address
 */
class AddressBuilder
{
    /**
     * @var Address
     */
    private $instance;

    private function __construct(Address $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Address Builder object.
     */
    public static function init(): self
    {
        return new self(new Address());
    }

    /**
     * Sets Addr field.
     *
     * @param string|null $value
     */
    public function addr(?string $value): self
    {
        $this->instance->setAddr($value);
        return $this;
    }

    /**
     * Sets Prefix Len field.
     *
     * @param int|null $value
     */
    public function prefixLen(?int $value): self
    {
        $this->instance->setPrefixLen($value);
        return $this;
    }

    /**
     * Initializes a new Address object.
     */
    public function build(): Address
    {
        return CoreHelper::clone($this->instance);
    }
}
