<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\AuditLogAction;

/**
 * Builder for model AuditLogAction
 *
 * @see AuditLogAction
 */
class AuditLogActionBuilder
{
    /**
     * @var AuditLogAction
     */
    private $instance;

    private function __construct(AuditLogAction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Audit Log Action Builder object.
     */
    public static function init(): self
    {
        return new self(new AuditLogAction());
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets label field.
     *
     * @param string|null $value
     */
    public function label(?string $value): self
    {
        $this->instance->setLabel($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new Audit Log Action object.
     */
    public function build(): AuditLogAction
    {
        return CoreHelper::clone($this->instance);
    }
}
