<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\BindOptions;

/**
 * Builder for model BindOptions
 *
 * @see BindOptions
 */
class BindOptionsBuilder
{
    /**
     * @var BindOptions
     */
    private $instance;

    private function __construct(BindOptions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bind Options Builder object.
     */
    public static function init(): self
    {
        return new self(new BindOptions());
    }

    /**
     * Sets Propagation field.
     *
     * @param string|null $value
     */
    public function propagation(?string $value): self
    {
        $this->instance->setPropagation($value);
        return $this;
    }

    /**
     * Initializes a new Bind Options object.
     */
    public function build(): BindOptions
    {
        return CoreHelper::clone($this->instance);
    }
}
