<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Config;
use DockerLib\Models\ConfigSpec;
use DockerLib\Models\Version;

/**
 * Builder for model Config
 *
 * @see Config
 */
class ConfigBuilder
{
    /**
     * @var Config
     */
    private $instance;

    private function __construct(Config $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Config Builder object.
     */
    public static function init(): self
    {
        return new self(new Config());
    }

    /**
     * Sets Created At field.
     *
     * @param string|null $value
     */
    public function createdAt(?string $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets ID field.
     *
     * @param string|null $value
     */
    public function iD(?string $value): self
    {
        $this->instance->setID($value);
        return $this;
    }

    /**
     * Sets Spec field.
     *
     * @param ConfigSpec|null $value
     */
    public function spec(?ConfigSpec $value): self
    {
        $this->instance->setSpec($value);
        return $this;
    }

    /**
     * Sets Updated At field.
     *
     * @param string|null $value
     */
    public function updatedAt(?string $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Sets Version field.
     *
     * @param Version|null $value
     */
    public function version(?Version $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Initializes a new Config object.
     */
    public function build(): Config
    {
        return CoreHelper::clone($this->instance);
    }
}
