<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ContainersAttachResponse;

/**
 * Builder for model ContainersAttachResponse
 *
 * @see ContainersAttachResponse
 */
class ContainersAttachResponseBuilder
{
    /**
     * @var ContainersAttachResponse
     */
    private $instance;

    private function __construct(ContainersAttachResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Containers Attach Response Builder object.
     *
     * @param string $message
     */
    public static function init(string $message): self
    {
        return new self(new ContainersAttachResponse($message));
    }

    /**
     * Initializes a new Containers Attach Response object.
     */
    public function build(): ContainersAttachResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
