<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ContainersCreateResponse;

/**
 * Builder for model ContainersCreateResponse
 *
 * @see ContainersCreateResponse
 */
class ContainersCreateResponseBuilder
{
    /**
     * @var ContainersCreateResponse
     */
    private $instance;

    private function __construct(ContainersCreateResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Containers Create Response Builder object.
     *
     * @param string $id
     * @param string[] $warnings
     */
    public static function init(string $id, array $warnings): self
    {
        return new self(new ContainersCreateResponse($id, $warnings));
    }

    /**
     * Initializes a new Containers Create Response object.
     */
    public function build(): ContainersCreateResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
