<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ContainerStatus;

/**
 * Builder for model ContainerStatus
 *
 * @see ContainerStatus
 */
class ContainerStatusBuilder
{
    /**
     * @var ContainerStatus
     */
    private $instance;

    private function __construct(ContainerStatus $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Container Status Builder object.
     */
    public static function init(): self
    {
        return new self(new ContainerStatus());
    }

    /**
     * Sets Container ID field.
     *
     * @param string|null $value
     */
    public function containerID(?string $value): self
    {
        $this->instance->setContainerID($value);
        return $this;
    }

    /**
     * Sets Exit Code field.
     *
     * @param int|null $value
     */
    public function exitCode(?int $value): self
    {
        $this->instance->setExitCode($value);
        return $this;
    }

    /**
     * Sets PID field.
     *
     * @param int|null $value
     */
    public function pID(?int $value): self
    {
        $this->instance->setPID($value);
        return $this;
    }

    /**
     * Initializes a new Container Status object.
     */
    public function build(): ContainerStatus
    {
        return CoreHelper::clone($this->instance);
    }
}
