<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Config3;
use DockerLib\Models\ContainersJsonResponse;
use DockerLib\Models\GraphDriver;
use DockerLib\Models\HostConfig1;
use DockerLib\Models\MountPoint;
use DockerLib\Models\NetworkSettings1;
use DockerLib\Models\State12;

/**
 * Builder for model ContainersJsonResponse
 *
 * @see ContainersJsonResponse
 */
class ContainersJsonResponseBuilder
{
    /**
     * @var ContainersJsonResponse
     */
    private $instance;

    private function __construct(ContainersJsonResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Containers Json Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ContainersJsonResponse());
    }

    /**
     * Sets App Armor Profile field.
     *
     * @param string|null $value
     */
    public function appArmorProfile(?string $value): self
    {
        $this->instance->setAppArmorProfile($value);
        return $this;
    }

    /**
     * Sets Args field.
     *
     * @param string[]|null $value
     */
    public function args(?array $value): self
    {
        $this->instance->setArgs($value);
        return $this;
    }

    /**
     * Sets Config field.
     *
     * @param Config3|null $value
     */
    public function config(?Config3 $value): self
    {
        $this->instance->setConfig($value);
        return $this;
    }

    /**
     * Sets Created field.
     *
     * @param string|null $value
     */
    public function created(?string $value): self
    {
        $this->instance->setCreated($value);
        return $this;
    }

    /**
     * Sets Driver field.
     *
     * @param string|null $value
     */
    public function driver(?string $value): self
    {
        $this->instance->setDriver($value);
        return $this;
    }

    /**
     * Sets Exec I Ds field.
     *
     * @param string|null $value
     */
    public function execIDs(?string $value): self
    {
        $this->instance->setExecIDs($value);
        return $this;
    }

    /**
     * Sets Graph Driver field.
     *
     * @param GraphDriver|null $value
     */
    public function graphDriver(?GraphDriver $value): self
    {
        $this->instance->setGraphDriver($value);
        return $this;
    }

    /**
     * Sets Host Config field.
     *
     * @param HostConfig1|null $value
     */
    public function hostConfig(?HostConfig1 $value): self
    {
        $this->instance->setHostConfig($value);
        return $this;
    }

    /**
     * Sets Hostname Path field.
     *
     * @param string|null $value
     */
    public function hostnamePath(?string $value): self
    {
        $this->instance->setHostnamePath($value);
        return $this;
    }

    /**
     * Sets Hosts Path field.
     *
     * @param string|null $value
     */
    public function hostsPath(?string $value): self
    {
        $this->instance->setHostsPath($value);
        return $this;
    }

    /**
     * Sets Id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets Image field.
     *
     * @param string|null $value
     */
    public function image(?string $value): self
    {
        $this->instance->setImage($value);
        return $this;
    }

    /**
     * Sets Log Path field.
     *
     * @param string|null $value
     */
    public function logPath(?string $value): self
    {
        $this->instance->setLogPath($value);
        return $this;
    }

    /**
     * Sets Mount Label field.
     *
     * @param string|null $value
     */
    public function mountLabel(?string $value): self
    {
        $this->instance->setMountLabel($value);
        return $this;
    }

    /**
     * Sets Mounts field.
     *
     * @param MountPoint[]|null $value
     */
    public function mounts(?array $value): self
    {
        $this->instance->setMounts($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets Network Settings field.
     *
     * @param NetworkSettings1|null $value
     */
    public function networkSettings(?NetworkSettings1 $value): self
    {
        $this->instance->setNetworkSettings($value);
        return $this;
    }

    /**
     * Sets Node field.
     *
     * @param array|null $value
     */
    public function node(?array $value): self
    {
        $this->instance->setNode($value);
        return $this;
    }

    /**
     * Sets Path field.
     *
     * @param string|null $value
     */
    public function path(?string $value): self
    {
        $this->instance->setPath($value);
        return $this;
    }

    /**
     * Sets Process Label field.
     *
     * @param string|null $value
     */
    public function processLabel(?string $value): self
    {
        $this->instance->setProcessLabel($value);
        return $this;
    }

    /**
     * Sets Resolv Conf Path field.
     *
     * @param string|null $value
     */
    public function resolvConfPath(?string $value): self
    {
        $this->instance->setResolvConfPath($value);
        return $this;
    }

    /**
     * Sets Restart Count field.
     *
     * @param int|null $value
     */
    public function restartCount(?int $value): self
    {
        $this->instance->setRestartCount($value);
        return $this;
    }

    /**
     * Sets Size Root Fs field.
     *
     * @param int|null $value
     */
    public function sizeRootFs(?int $value): self
    {
        $this->instance->setSizeRootFs($value);
        return $this;
    }

    /**
     * Sets Size Rw field.
     *
     * @param int|null $value
     */
    public function sizeRw(?int $value): self
    {
        $this->instance->setSizeRw($value);
        return $this;
    }

    /**
     * Sets State field.
     *
     * @param State12|null $value
     */
    public function state(?State12 $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Initializes a new Containers Json Response object.
     */
    public function build(): ContainersJsonResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
