<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ContainerdCommit;

/**
 * Builder for model ContainerdCommit
 *
 * @see ContainerdCommit
 */
class ContainerdCommitBuilder
{
    /**
     * @var ContainerdCommit
     */
    private $instance;

    private function __construct(ContainerdCommit $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Containerd Commit Builder object.
     */
    public static function init(): self
    {
        return new self(new ContainerdCommit());
    }

    /**
     * Sets Expected field.
     *
     * @param string|null $value
     */
    public function expected(?string $value): self
    {
        $this->instance->setExpected($value);
        return $this;
    }

    /**
     * Sets ID field.
     *
     * @param string|null $value
     */
    public function iD(?string $value): self
    {
        $this->instance->setID($value);
        return $this;
    }

    /**
     * Initializes a new Containerd Commit object.
     */
    public function build(): ContainerdCommit
    {
        return CoreHelper::clone($this->instance);
    }
}
