<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\CreateAccessTokenRequest;

/**
 * Builder for model CreateAccessTokenRequest
 *
 * @see CreateAccessTokenRequest
 */
class CreateAccessTokenRequestBuilder
{
    /**
     * @var CreateAccessTokenRequest
     */
    private $instance;

    private function __construct(CreateAccessTokenRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Access Token Request Builder object.
     *
     * @param string[] $scopes
     * @param string $tokenLabel
     */
    public static function init(array $scopes, string $tokenLabel): self
    {
        return new self(new CreateAccessTokenRequest($scopes, $tokenLabel));
    }

    /**
     * Initializes a new Create Access Token Request object.
     */
    public function build(): CreateAccessTokenRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
