<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\CredentialSpec;

/**
 * Builder for model CredentialSpec
 *
 * @see CredentialSpec
 */
class CredentialSpecBuilder
{
    /**
     * @var CredentialSpec
     */
    private $instance;

    private function __construct(CredentialSpec $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Credential Spec Builder object.
     */
    public static function init(): self
    {
        return new self(new CredentialSpec());
    }

    /**
     * Sets File field.
     *
     * @param string|null $value
     */
    public function file(?string $value): self
    {
        $this->instance->setFile($value);
        return $this;
    }

    /**
     * Sets Registry field.
     *
     * @param string|null $value
     */
    public function registry(?string $value): self
    {
        $this->instance->setRegistry($value);
        return $this;
    }

    /**
     * Initializes a new Credential Spec object.
     */
    public function build(): CredentialSpec
    {
        return CoreHelper::clone($this->instance);
    }
}
