<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Descriptor1;

/**
 * Builder for model Descriptor1
 *
 * @see Descriptor1
 */
class Descriptor1Builder
{
    /**
     * @var Descriptor1
     */
    private $instance;

    private function __construct(Descriptor1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Descriptor 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Descriptor1());
    }

    /**
     * Sets Digest field.
     *
     * @param string|null $value
     */
    public function digest(?string $value): self
    {
        $this->instance->setDigest($value);
        return $this;
    }

    /**
     * Sets Media Type field.
     *
     * @param string|null $value
     */
    public function mediaType(?string $value): self
    {
        $this->instance->setMediaType($value);
        return $this;
    }

    /**
     * Sets Size field.
     *
     * @param int|null $value
     */
    public function size(?int $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Sets UR Ls field.
     *
     * @param string[]|null $value
     */
    public function uRLs(?array $value): self
    {
        $this->instance->setURLs($value);
        return $this;
    }

    /**
     * Initializes a new Descriptor 1 object.
     */
    public function build(): Descriptor1
    {
        return CoreHelper::clone($this->instance);
    }
}
