<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\DriverConfig;

/**
 * Builder for model DriverConfig
 *
 * @see DriverConfig
 */
class DriverConfigBuilder
{
    /**
     * @var DriverConfig
     */
    private $instance;

    private function __construct(DriverConfig $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Driver Config Builder object.
     */
    public static function init(): self
    {
        return new self(new DriverConfig());
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets Options field.
     *
     * @param array<string,string>|null $value
     */
    public function options(?array $value): self
    {
        $this->instance->setOptions($value);
        return $this;
    }

    /**
     * Initializes a new Driver Config object.
     */
    public function build(): DriverConfig
    {
        return CoreHelper::clone($this->instance);
    }
}
