<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Driver;

/**
 * Builder for model Driver
 *
 * @see Driver
 */
class DriverBuilder
{
    /**
     * @var Driver
     */
    private $instance;

    private function __construct(Driver $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Driver Builder object.
     *
     * @param string $name
     */
    public static function init(string $name): self
    {
        return new self(new Driver($name));
    }

    /**
     * Sets Options field.
     *
     * @param array<string,string>|null $value
     */
    public function options(?array $value): self
    {
        $this->instance->setOptions($value);
        return $this;
    }

    /**
     * Initializes a new Driver object.
     */
    public function build(): Driver
    {
        return CoreHelper::clone($this->instance);
    }
}
