<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\EngineDescription;
use DockerLib\Models\Plugin2;

/**
 * Builder for model EngineDescription
 *
 * @see EngineDescription
 */
class EngineDescriptionBuilder
{
    /**
     * @var EngineDescription
     */
    private $instance;

    private function __construct(EngineDescription $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Engine Description Builder object.
     */
    public static function init(): self
    {
        return new self(new EngineDescription());
    }

    /**
     * Sets Engine Version field.
     *
     * @param string|null $value
     */
    public function engineVersion(?string $value): self
    {
        $this->instance->setEngineVersion($value);
        return $this;
    }

    /**
     * Sets Labels field.
     *
     * @param array<string,string>|null $value
     */
    public function labels(?array $value): self
    {
        $this->instance->setLabels($value);
        return $this;
    }

    /**
     * Sets Plugins field.
     *
     * @param Plugin2[]|null $value
     */
    public function plugins(?array $value): self
    {
        $this->instance->setPlugins($value);
        return $this;
    }

    /**
     * Initializes a new Engine Description object.
     */
    public function build(): EngineDescription
    {
        return CoreHelper::clone($this->instance);
    }
}
