<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Errinfo2;

/**
 * Builder for model Errinfo2
 *
 * @see Errinfo2
 */
class Errinfo2Builder
{
    /**
     * @var Errinfo2
     */
    private $instance;

    private function __construct(Errinfo2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Errinfo 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new Errinfo2());
    }

    /**
     * Sets api call docker id field.
     *
     * @param string|null $value
     */
    public function apiCallDockerId(?string $value): self
    {
        $this->instance->setApiCallDockerId($value);
        return $this;
    }

    /**
     * Sets api call name field.
     *
     * @param string|null $value
     */
    public function apiCallName(?string $value): self
    {
        $this->instance->setApiCallName($value);
        return $this;
    }

    /**
     * Sets api call start field.
     *
     * @param string|null $value
     */
    public function apiCallStart(?string $value): self
    {
        $this->instance->setApiCallStart($value);
        return $this;
    }

    /**
     * Sets api call txnid field.
     *
     * @param string|null $value
     */
    public function apiCallTxnid(?string $value): self
    {
        $this->instance->setApiCallTxnid($value);
        return $this;
    }

    /**
     * Initializes a new Errinfo 2 object.
     */
    public function build(): Errinfo2
    {
        return CoreHelper::clone($this->instance);
    }
}
