<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ErrorResponse;

/**
 * Builder for model ErrorResponse
 *
 * @see ErrorResponse
 */
class ErrorResponseBuilder
{
    /**
     * @var ErrorResponse
     */
    private $instance;

    private function __construct(ErrorResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Error Response Builder object.
     *
     * @param string $message
     */
    public static function init(string $message): self
    {
        return new self(new ErrorResponse($message));
    }

    /**
     * Initializes a new Error Response object.
     */
    public function build(): ErrorResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
