<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Actor;
use DockerLib\Models\EventsResponse;

/**
 * Builder for model EventsResponse
 *
 * @see EventsResponse
 */
class EventsResponseBuilder
{
    /**
     * @var EventsResponse
     */
    private $instance;

    private function __construct(EventsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Events Response Builder object.
     */
    public static function init(): self
    {
        return new self(new EventsResponse());
    }

    /**
     * Sets Action field.
     *
     * @param string|null $value
     */
    public function action(?string $value): self
    {
        $this->instance->setAction($value);
        return $this;
    }

    /**
     * Sets Actor field.
     *
     * @param Actor|null $value
     */
    public function actor(?Actor $value): self
    {
        $this->instance->setActor($value);
        return $this;
    }

    /**
     * Sets Type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets time field.
     *
     * @param int|null $value
     */
    public function time(?int $value): self
    {
        $this->instance->setTime($value);
        return $this;
    }

    /**
     * Sets time Nano field.
     *
     * @param int|null $value
     */
    public function timeNano(?int $value): self
    {
        $this->instance->setTimeNano($value);
        return $this;
    }

    /**
     * Initializes a new Events Response object.
     */
    public function build(): EventsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
