<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ExecJsonResponse;
use DockerLib\Models\ProcessConfig;

/**
 * Builder for model ExecJsonResponse
 *
 * @see ExecJsonResponse
 */
class ExecJsonResponseBuilder
{
    /**
     * @var ExecJsonResponse
     */
    private $instance;

    private function __construct(ExecJsonResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Exec Json Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ExecJsonResponse());
    }

    /**
     * Sets Container ID field.
     *
     * @param string|null $value
     */
    public function containerID(?string $value): self
    {
        $this->instance->setContainerID($value);
        return $this;
    }

    /**
     * Sets Exit Code field.
     *
     * @param int|null $value
     */
    public function exitCode(?int $value): self
    {
        $this->instance->setExitCode($value);
        return $this;
    }

    /**
     * Sets ID field.
     *
     * @param string|null $value
     */
    public function iD(?string $value): self
    {
        $this->instance->setID($value);
        return $this;
    }

    /**
     * Sets Open Stderr field.
     *
     * @param bool|null $value
     */
    public function openStderr(?bool $value): self
    {
        $this->instance->setOpenStderr($value);
        return $this;
    }

    /**
     * Sets Open Stdin field.
     *
     * @param bool|null $value
     */
    public function openStdin(?bool $value): self
    {
        $this->instance->setOpenStdin($value);
        return $this;
    }

    /**
     * Sets Open Stdout field.
     *
     * @param bool|null $value
     */
    public function openStdout(?bool $value): self
    {
        $this->instance->setOpenStdout($value);
        return $this;
    }

    /**
     * Sets Pid field.
     *
     * @param int|null $value
     */
    public function pid(?int $value): self
    {
        $this->instance->setPid($value);
        return $this;
    }

    /**
     * Sets Process Config field.
     *
     * @param ProcessConfig|null $value
     */
    public function processConfig(?ProcessConfig $value): self
    {
        $this->instance->setProcessConfig($value);
        return $this;
    }

    /**
     * Sets Running field.
     *
     * @param bool|null $value
     */
    public function running(?bool $value): self
    {
        $this->instance->setRunning($value);
        return $this;
    }

    /**
     * Initializes a new Exec Json Response object.
     */
    public function build(): ExecJsonResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
