<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\File1;

/**
 * Builder for model File1
 *
 * @see File1
 */
class File1Builder
{
    /**
     * @var File1
     */
    private $instance;

    private function __construct(File1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new File 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new File1());
    }

    /**
     * Sets GID field.
     *
     * @param string|null $value
     */
    public function gID(?string $value): self
    {
        $this->instance->setGID($value);
        return $this;
    }

    /**
     * Sets Mode field.
     *
     * @param int|null $value
     */
    public function mode(?int $value): self
    {
        $this->instance->setMode($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets UID field.
     *
     * @param string|null $value
     */
    public function uID(?string $value): self
    {
        $this->instance->setUID($value);
        return $this;
    }

    /**
     * Initializes a new File 1 object.
     */
    public function build(): File1
    {
        return CoreHelper::clone($this->instance);
    }
}
