<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\GraphDriverData;

/**
 * Builder for model GraphDriverData
 *
 * @see GraphDriverData
 */
class GraphDriverDataBuilder
{
    /**
     * @var GraphDriverData
     */
    private $instance;

    private function __construct(GraphDriverData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Graph Driver Data Builder object.
     *
     * @param array<string,string> $data
     * @param string $name
     */
    public static function init(array $data, string $name): self
    {
        return new self(new GraphDriverData($data, $name));
    }

    /**
     * Initializes a new Graph Driver Data object.
     */
    public function build(): GraphDriverData
    {
        return CoreHelper::clone($this->instance);
    }
}
