<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\BlkioWeightDevice;
use DockerLib\Models\DeviceMapping;
use DockerLib\Models\HostConfig1;
use DockerLib\Models\LogConfig2;
use DockerLib\Models\Mount;
use DockerLib\Models\PortBindings;
use DockerLib\Models\RestartPolicy3;
use DockerLib\Models\ThrottleDevice;
use DockerLib\Models\Ulimit;

/**
 * Builder for model HostConfig1
 *
 * @see HostConfig1
 */
class HostConfig1Builder
{
    /**
     * @var HostConfig1
     */
    private $instance;

    private function __construct(HostConfig1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Host Config 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new HostConfig1());
    }

    /**
     * Sets Blkio Device Read Bps field.
     *
     * @param ThrottleDevice[]|null $value
     */
    public function blkioDeviceReadBps(?array $value): self
    {
        $this->instance->setBlkioDeviceReadBps($value);
        return $this;
    }

    /**
     * Sets Blkio Device Read I Ops field.
     *
     * @param ThrottleDevice[]|null $value
     */
    public function blkioDeviceReadIOps(?array $value): self
    {
        $this->instance->setBlkioDeviceReadIOps($value);
        return $this;
    }

    /**
     * Sets Blkio Device Write Bps field.
     *
     * @param ThrottleDevice[]|null $value
     */
    public function blkioDeviceWriteBps(?array $value): self
    {
        $this->instance->setBlkioDeviceWriteBps($value);
        return $this;
    }

    /**
     * Sets Blkio Device Write I Ops field.
     *
     * @param ThrottleDevice[]|null $value
     */
    public function blkioDeviceWriteIOps(?array $value): self
    {
        $this->instance->setBlkioDeviceWriteIOps($value);
        return $this;
    }

    /**
     * Sets Blkio Weight field.
     *
     * @param int|null $value
     */
    public function blkioWeight(?int $value): self
    {
        $this->instance->setBlkioWeight($value);
        return $this;
    }

    /**
     * Sets Blkio Weight Device field.
     *
     * @param BlkioWeightDevice[]|null $value
     */
    public function blkioWeightDevice(?array $value): self
    {
        $this->instance->setBlkioWeightDevice($value);
        return $this;
    }

    /**
     * Sets Cgroup Parent field.
     *
     * @param string|null $value
     */
    public function cgroupParent(?string $value): self
    {
        $this->instance->setCgroupParent($value);
        return $this;
    }

    /**
     * Sets Cpu Count field.
     *
     * @param int|null $value
     */
    public function cpuCount(?int $value): self
    {
        $this->instance->setCpuCount($value);
        return $this;
    }

    /**
     * Sets Cpu Percent field.
     *
     * @param int|null $value
     */
    public function cpuPercent(?int $value): self
    {
        $this->instance->setCpuPercent($value);
        return $this;
    }

    /**
     * Sets Cpu Period field.
     *
     * @param int|null $value
     */
    public function cpuPeriod(?int $value): self
    {
        $this->instance->setCpuPeriod($value);
        return $this;
    }

    /**
     * Sets Cpu Quota field.
     *
     * @param int|null $value
     */
    public function cpuQuota(?int $value): self
    {
        $this->instance->setCpuQuota($value);
        return $this;
    }

    /**
     * Sets Cpu Realtime Period field.
     *
     * @param int|null $value
     */
    public function cpuRealtimePeriod(?int $value): self
    {
        $this->instance->setCpuRealtimePeriod($value);
        return $this;
    }

    /**
     * Sets Cpu Realtime Runtime field.
     *
     * @param int|null $value
     */
    public function cpuRealtimeRuntime(?int $value): self
    {
        $this->instance->setCpuRealtimeRuntime($value);
        return $this;
    }

    /**
     * Sets Cpu Shares field.
     *
     * @param int|null $value
     */
    public function cpuShares(?int $value): self
    {
        $this->instance->setCpuShares($value);
        return $this;
    }

    /**
     * Sets Cpuset Cpus field.
     *
     * @param string|null $value
     */
    public function cpusetCpus(?string $value): self
    {
        $this->instance->setCpusetCpus($value);
        return $this;
    }

    /**
     * Sets Cpuset Mems field.
     *
     * @param string|null $value
     */
    public function cpusetMems(?string $value): self
    {
        $this->instance->setCpusetMems($value);
        return $this;
    }

    /**
     * Sets Device Cgroup Rules field.
     *
     * @param string[]|null $value
     */
    public function deviceCgroupRules(?array $value): self
    {
        $this->instance->setDeviceCgroupRules($value);
        return $this;
    }

    /**
     * Sets Devices field.
     *
     * @param DeviceMapping[]|null $value
     */
    public function devices(?array $value): self
    {
        $this->instance->setDevices($value);
        return $this;
    }

    /**
     * Sets Disk Quota field.
     *
     * @param int|null $value
     */
    public function diskQuota(?int $value): self
    {
        $this->instance->setDiskQuota($value);
        return $this;
    }

    /**
     * Sets IO Maximum Bandwidth field.
     *
     * @param int|null $value
     */
    public function iOMaximumBandwidth(?int $value): self
    {
        $this->instance->setIOMaximumBandwidth($value);
        return $this;
    }

    /**
     * Sets IO Maximum I Ops field.
     *
     * @param int|null $value
     */
    public function iOMaximumIOps(?int $value): self
    {
        $this->instance->setIOMaximumIOps($value);
        return $this;
    }

    /**
     * Sets Kernel Memory field.
     *
     * @param int|null $value
     */
    public function kernelMemory(?int $value): self
    {
        $this->instance->setKernelMemory($value);
        return $this;
    }

    /**
     * Sets Memory field.
     *
     * @param int|null $value
     */
    public function memory(?int $value): self
    {
        $this->instance->setMemory($value);
        return $this;
    }

    /**
     * Sets Memory Reservation field.
     *
     * @param int|null $value
     */
    public function memoryReservation(?int $value): self
    {
        $this->instance->setMemoryReservation($value);
        return $this;
    }

    /**
     * Sets Memory Swap field.
     *
     * @param int|null $value
     */
    public function memorySwap(?int $value): self
    {
        $this->instance->setMemorySwap($value);
        return $this;
    }

    /**
     * Sets Memory Swappiness field.
     *
     * @param int|null $value
     */
    public function memorySwappiness(?int $value): self
    {
        $this->instance->setMemorySwappiness($value);
        return $this;
    }

    /**
     * Sets Nano CP Us field.
     *
     * @param int|null $value
     */
    public function nanoCPUs(?int $value): self
    {
        $this->instance->setNanoCPUs($value);
        return $this;
    }

    /**
     * Sets Oom Kill Disable field.
     *
     * @param bool|null $value
     */
    public function oomKillDisable(?bool $value): self
    {
        $this->instance->setOomKillDisable($value);
        return $this;
    }

    /**
     * Sets Pids Limit field.
     *
     * @param int|null $value
     */
    public function pidsLimit(?int $value): self
    {
        $this->instance->setPidsLimit($value);
        return $this;
    }

    /**
     * Sets Ulimits field.
     *
     * @param Ulimit[]|null $value
     */
    public function ulimits(?array $value): self
    {
        $this->instance->setUlimits($value);
        return $this;
    }

    /**
     * Sets Auto Remove field.
     *
     * @param bool|null $value
     */
    public function autoRemove(?bool $value): self
    {
        $this->instance->setAutoRemove($value);
        return $this;
    }

    /**
     * Sets Binds field.
     *
     * @param string[]|null $value
     */
    public function binds(?array $value): self
    {
        $this->instance->setBinds($value);
        return $this;
    }

    /**
     * Sets Cap Add field.
     *
     * @param string[]|null $value
     */
    public function capAdd(?array $value): self
    {
        $this->instance->setCapAdd($value);
        return $this;
    }

    /**
     * Sets Cap Drop field.
     *
     * @param string[]|null $value
     */
    public function capDrop(?array $value): self
    {
        $this->instance->setCapDrop($value);
        return $this;
    }

    /**
     * Sets Cgroup field.
     *
     * @param string|null $value
     */
    public function cgroup(?string $value): self
    {
        $this->instance->setCgroup($value);
        return $this;
    }

    /**
     * Sets Console Size field.
     *
     * @param int[]|null $value
     */
    public function consoleSize(?array $value): self
    {
        $this->instance->setConsoleSize($value);
        return $this;
    }

    /**
     * Sets Container ID File field.
     *
     * @param string|null $value
     */
    public function containerIDFile(?string $value): self
    {
        $this->instance->setContainerIDFile($value);
        return $this;
    }

    /**
     * Sets Dns field.
     *
     * @param string[]|null $value
     */
    public function dns(?array $value): self
    {
        $this->instance->setDns($value);
        return $this;
    }

    /**
     * Sets Dns Options field.
     *
     * @param string[]|null $value
     */
    public function dnsOptions(?array $value): self
    {
        $this->instance->setDnsOptions($value);
        return $this;
    }

    /**
     * Sets Dns Search field.
     *
     * @param string[]|null $value
     */
    public function dnsSearch(?array $value): self
    {
        $this->instance->setDnsSearch($value);
        return $this;
    }

    /**
     * Sets Extra Hosts field.
     *
     * @param string[]|null $value
     */
    public function extraHosts(?array $value): self
    {
        $this->instance->setExtraHosts($value);
        return $this;
    }

    /**
     * Sets Group Add field.
     *
     * @param string[]|null $value
     */
    public function groupAdd(?array $value): self
    {
        $this->instance->setGroupAdd($value);
        return $this;
    }

    /**
     * Sets Ipc Mode field.
     *
     * @param string|null $value
     */
    public function ipcMode(?string $value): self
    {
        $this->instance->setIpcMode($value);
        return $this;
    }

    /**
     * Sets Isolation field.
     *
     * @param string|null $value
     */
    public function isolation(?string $value): self
    {
        $this->instance->setIsolation($value);
        return $this;
    }

    /**
     * Sets Links field.
     *
     * @param string[]|null $value
     */
    public function links(?array $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Sets Log Config field.
     *
     * @param LogConfig2|null $value
     */
    public function logConfig(?LogConfig2 $value): self
    {
        $this->instance->setLogConfig($value);
        return $this;
    }

    /**
     * Sets Mounts field.
     *
     * @param Mount[]|null $value
     */
    public function mounts(?array $value): self
    {
        $this->instance->setMounts($value);
        return $this;
    }

    /**
     * Sets Network Mode field.
     *
     * @param string|null $value
     */
    public function networkMode(?string $value): self
    {
        $this->instance->setNetworkMode($value);
        return $this;
    }

    /**
     * Sets Oom Score Adj field.
     *
     * @param int|null $value
     */
    public function oomScoreAdj(?int $value): self
    {
        $this->instance->setOomScoreAdj($value);
        return $this;
    }

    /**
     * Sets Pid Mode field.
     *
     * @param string|null $value
     */
    public function pidMode(?string $value): self
    {
        $this->instance->setPidMode($value);
        return $this;
    }

    /**
     * Sets Port Bindings field.
     *
     * @param array<string,PortBindings>|null $value
     */
    public function portBindings(?array $value): self
    {
        $this->instance->setPortBindings($value);
        return $this;
    }

    /**
     * Sets Privileged field.
     *
     * @param bool|null $value
     */
    public function privileged(?bool $value): self
    {
        $this->instance->setPrivileged($value);
        return $this;
    }

    /**
     * Sets Publish All Ports field.
     *
     * @param bool|null $value
     */
    public function publishAllPorts(?bool $value): self
    {
        $this->instance->setPublishAllPorts($value);
        return $this;
    }

    /**
     * Sets Readonly Rootfs field.
     *
     * @param bool|null $value
     */
    public function readonlyRootfs(?bool $value): self
    {
        $this->instance->setReadonlyRootfs($value);
        return $this;
    }

    /**
     * Sets Restart Policy field.
     *
     * @param RestartPolicy3|null $value
     */
    public function restartPolicy(?RestartPolicy3 $value): self
    {
        $this->instance->setRestartPolicy($value);
        return $this;
    }

    /**
     * Sets Runtime field.
     *
     * @param string|null $value
     */
    public function runtime(?string $value): self
    {
        $this->instance->setRuntime($value);
        return $this;
    }

    /**
     * Sets Security Opt field.
     *
     * @param string[]|null $value
     */
    public function securityOpt(?array $value): self
    {
        $this->instance->setSecurityOpt($value);
        return $this;
    }

    /**
     * Sets Shm Size field.
     *
     * @param int|null $value
     */
    public function shmSize(?int $value): self
    {
        $this->instance->setShmSize($value);
        return $this;
    }

    /**
     * Sets Storage Opt field.
     *
     * @param array<string,string>|null $value
     */
    public function storageOpt(?array $value): self
    {
        $this->instance->setStorageOpt($value);
        return $this;
    }

    /**
     * Sets Sysctls field.
     *
     * @param array<string,string>|null $value
     */
    public function sysctls(?array $value): self
    {
        $this->instance->setSysctls($value);
        return $this;
    }

    /**
     * Sets Tmpfs field.
     *
     * @param array<string,string>|null $value
     */
    public function tmpfs(?array $value): self
    {
        $this->instance->setTmpfs($value);
        return $this;
    }

    /**
     * Sets UTS Mode field.
     *
     * @param string|null $value
     */
    public function uTSMode(?string $value): self
    {
        $this->instance->setUTSMode($value);
        return $this;
    }

    /**
     * Sets Userns Mode field.
     *
     * @param string|null $value
     */
    public function usernsMode(?string $value): self
    {
        $this->instance->setUsernsMode($value);
        return $this;
    }

    /**
     * Sets Volume Driver field.
     *
     * @param string|null $value
     */
    public function volumeDriver(?string $value): self
    {
        $this->instance->setVolumeDriver($value);
        return $this;
    }

    /**
     * Sets Volumes From field.
     *
     * @param string[]|null $value
     */
    public function volumesFrom(?array $value): self
    {
        $this->instance->setVolumesFrom($value);
        return $this;
    }

    /**
     * Initializes a new Host Config 1 object.
     */
    public function build(): HostConfig1
    {
        return CoreHelper::clone($this->instance);
    }
}
