<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\IdResponse;

/**
 * Builder for model IdResponse
 *
 * @see IdResponse
 */
class IdResponseBuilder
{
    /**
     * @var IdResponse
     */
    private $instance;

    private function __construct(IdResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Id Response Builder object.
     *
     * @param string $id
     */
    public static function init(string $id): self
    {
        return new self(new IdResponse($id));
    }

    /**
     * Initializes a new Id Response object.
     */
    public function build(): IdResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
