<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ImageDeleteResponseItem;

/**
 * Builder for model ImageDeleteResponseItem
 *
 * @see ImageDeleteResponseItem
 */
class ImageDeleteResponseItemBuilder
{
    /**
     * @var ImageDeleteResponseItem
     */
    private $instance;

    private function __construct(ImageDeleteResponseItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Image Delete Response Item Builder object.
     */
    public static function init(): self
    {
        return new self(new ImageDeleteResponseItem());
    }

    /**
     * Sets Deleted field.
     *
     * @param string|null $value
     */
    public function deleted(?string $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Sets Untagged field.
     *
     * @param string|null $value
     */
    public function untagged(?string $value): self
    {
        $this->instance->setUntagged($value);
        return $this;
    }

    /**
     * Initializes a new Image Delete Response Item object.
     */
    public function build(): ImageDeleteResponseItem
    {
        return CoreHelper::clone($this->instance);
    }
}
