<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ImagesHistoryResponse;

/**
 * Builder for model ImagesHistoryResponse
 *
 * @see ImagesHistoryResponse
 */
class ImagesHistoryResponseBuilder
{
    /**
     * @var ImagesHistoryResponse
     */
    private $instance;

    private function __construct(ImagesHistoryResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Images History Response Builder object.
     *
     * @param string $comment
     * @param int $created
     * @param string $createdBy
     * @param string $id
     * @param int $size
     * @param string[] $tags
     */
    public static function init(
        string $comment,
        int $created,
        string $createdBy,
        string $id,
        int $size,
        array $tags
    ): self {
        return new self(new ImagesHistoryResponse($comment, $created, $createdBy, $id, $size, $tags));
    }

    /**
     * Initializes a new Images History Response object.
     */
    public function build(): ImagesHistoryResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
