<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Interface2;
use DockerLib\Models\PluginInterfaceType;

/**
 * Builder for model Interface2
 *
 * @see Interface2
 */
class Interface2Builder
{
    /**
     * @var Interface2
     */
    private $instance;

    private function __construct(Interface2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Interface 2 Builder object.
     *
     * @param string $socket
     * @param PluginInterfaceType[] $types
     */
    public static function init(string $socket, array $types): self
    {
        return new self(new Interface2($socket, $types));
    }

    /**
     * Initializes a new Interface 2 object.
     */
    public function build(): Interface2
    {
        return CoreHelper::clone($this->instance);
    }
}
