<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\JoinTokens;

/**
 * Builder for model JoinTokens
 *
 * @see JoinTokens
 */
class JoinTokensBuilder
{
    /**
     * @var JoinTokens
     */
    private $instance;

    private function __construct(JoinTokens $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Join Tokens Builder object.
     */
    public static function init(): self
    {
        return new self(new JoinTokens());
    }

    /**
     * Sets Manager field.
     *
     * @param string|null $value
     */
    public function manager(?string $value): self
    {
        $this->instance->setManager($value);
        return $this;
    }

    /**
     * Sets Worker field.
     *
     * @param string|null $value
     */
    public function worker(?string $value): self
    {
        $this->instance->setWorker($value);
        return $this;
    }

    /**
     * Initializes a new Join Tokens object.
     */
    public function build(): JoinTokens
    {
        return CoreHelper::clone($this->instance);
    }
}
