<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\JoinTokens1;

/**
 * Builder for model JoinTokens1
 *
 * @see JoinTokens1
 */
class JoinTokens1Builder
{
    /**
     * @var JoinTokens1
     */
    private $instance;

    private function __construct(JoinTokens1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Join Tokens 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new JoinTokens1());
    }

    /**
     * Sets Manager field.
     *
     * @param string|null $value
     */
    public function manager(?string $value): self
    {
        $this->instance->setManager($value);
        return $this;
    }

    /**
     * Sets Worker field.
     *
     * @param string|null $value
     */
    public function worker(?string $value): self
    {
        $this->instance->setWorker($value);
        return $this;
    }

    /**
     * Initializes a new Join Tokens 1 object.
     */
    public function build(): JoinTokens1
    {
        return CoreHelper::clone($this->instance);
    }
}
