<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Layer;

/**
 * Builder for model Layer
 *
 * @see Layer
 */
class LayerBuilder
{
    /**
     * @var Layer
     */
    private $instance;

    private function __construct(Layer $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Layer Builder object.
     */
    public static function init(): self
    {
        return new self(new Layer());
    }

    /**
     * Sets digest field.
     *
     * @param string|null $value
     */
    public function digest(?string $value): self
    {
        $this->instance->setDigest($value);
        return $this;
    }

    /**
     * Unsets digest field.
     */
    public function unsetDigest(): self
    {
        $this->instance->unsetDigest();
        return $this;
    }

    /**
     * Sets instruction field.
     *
     * @param string|null $value
     */
    public function instruction(?string $value): self
    {
        $this->instance->setInstruction($value);
        return $this;
    }

    /**
     * Sets size field.
     *
     * @param int|null $value
     */
    public function size(?int $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Initializes a new Layer object.
     */
    public function build(): Layer
    {
        return CoreHelper::clone($this->instance);
    }
}
