<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\LogDriver12;

/**
 * Builder for model LogDriver12
 *
 * @see LogDriver12
 */
class LogDriver12Builder
{
    /**
     * @var LogDriver12
     */
    private $instance;

    private function __construct(LogDriver12 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Log Driver 12 Builder object.
     */
    public static function init(): self
    {
        return new self(new LogDriver12());
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets Options field.
     *
     * @param array<string,string>|null $value
     */
    public function options(?array $value): self
    {
        $this->instance->setOptions($value);
        return $this;
    }

    /**
     * Initializes a new Log Driver 12 object.
     */
    public function build(): LogDriver12
    {
        return CoreHelper::clone($this->instance);
    }
}
