<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Manifest;

/**
 * Builder for model Manifest
 *
 * @see Manifest
 */
class ManifestBuilder
{
    /**
     * @var Manifest
     */
    private $instance;

    private function __construct(Manifest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Manifest Builder object.
     *
     * @param string $digest
     * @param string $repository
     */
    public static function init(string $digest, string $repository): self
    {
        return new self(new Manifest($digest, $repository));
    }

    /**
     * Initializes a new Manifest object.
     */
    public function build(): Manifest
    {
        return CoreHelper::clone($this->instance);
    }
}
