<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Meta;

/**
 * Builder for model Meta
 *
 * @see Meta
 */
class MetaBuilder
{
    /**
     * @var Meta
     */
    private $instance;

    private function __construct(Meta $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Meta Builder object.
     */
    public static function init(): self
    {
        return new self(new Meta());
    }

    /**
     * Sets created field.
     *
     * @param string|null $value
     */
    public function created(?string $value): self
    {
        $this->instance->setCreated($value);
        return $this;
    }

    /**
     * Sets last Modified field.
     *
     * @param string|null $value
     */
    public function lastModified(?string $value): self
    {
        $this->instance->setLastModified($value);
        return $this;
    }

    /**
     * Sets location field.
     *
     * @param string|null $value
     */
    public function location(?string $value): self
    {
        $this->instance->setLocation($value);
        return $this;
    }

    /**
     * Sets resource Type field.
     *
     * @param string|null $value
     */
    public function resourceType(?string $value): self
    {
        $this->instance->setResourceType($value);
        return $this;
    }

    /**
     * Initializes a new Meta object.
     */
    public function build(): Meta
    {
        return CoreHelper::clone($this->instance);
    }
}
