<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\IPAM;
use DockerLib\Models\NetworksCreateRequest;

/**
 * Builder for model NetworksCreateRequest
 *
 * @see NetworksCreateRequest
 */
class NetworksCreateRequestBuilder
{
    /**
     * @var NetworksCreateRequest
     */
    private $instance;

    private function __construct(NetworksCreateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Networks Create Request Builder object.
     *
     * @param string $name
     */
    public static function init(string $name): self
    {
        return new self(new NetworksCreateRequest($name));
    }

    /**
     * Sets Attachable field.
     *
     * @param bool|null $value
     */
    public function attachable(?bool $value): self
    {
        $this->instance->setAttachable($value);
        return $this;
    }

    /**
     * Sets Check Duplicate field.
     *
     * @param bool|null $value
     */
    public function checkDuplicate(?bool $value): self
    {
        $this->instance->setCheckDuplicate($value);
        return $this;
    }

    /**
     * Sets Driver field.
     *
     * @param string|null $value
     */
    public function driver(?string $value): self
    {
        $this->instance->setDriver($value);
        return $this;
    }

    /**
     * Sets Enable I Pv 6 field.
     *
     * @param bool|null $value
     */
    public function enableIPv6(?bool $value): self
    {
        $this->instance->setEnableIPv6($value);
        return $this;
    }

    /**
     * Sets IPAM field.
     *
     * @param IPAM|null $value
     */
    public function iPAM(?IPAM $value): self
    {
        $this->instance->setIPAM($value);
        return $this;
    }

    /**
     * Sets Ingress field.
     *
     * @param bool|null $value
     */
    public function ingress(?bool $value): self
    {
        $this->instance->setIngress($value);
        return $this;
    }

    /**
     * Sets Internal field.
     *
     * @param bool|null $value
     */
    public function internal(?bool $value): self
    {
        $this->instance->setInternal($value);
        return $this;
    }

    /**
     * Sets Labels field.
     *
     * @param array<string,string>|null $value
     */
    public function labels(?array $value): self
    {
        $this->instance->setLabels($value);
        return $this;
    }

    /**
     * Sets Options field.
     *
     * @param array<string,string>|null $value
     */
    public function options(?array $value): self
    {
        $this->instance->setOptions($value);
        return $this;
    }

    /**
     * Initializes a new Networks Create Request object.
     */
    public function build(): NetworksCreateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
