<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\NetworkContainer;

/**
 * Builder for model NetworkContainer
 *
 * @see NetworkContainer
 */
class NetworkContainerBuilder
{
    /**
     * @var NetworkContainer
     */
    private $instance;

    private function __construct(NetworkContainer $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Network Container Builder object.
     */
    public static function init(): self
    {
        return new self(new NetworkContainer());
    }

    /**
     * Sets Endpoint ID field.
     *
     * @param string|null $value
     */
    public function endpointID(?string $value): self
    {
        $this->instance->setEndpointID($value);
        return $this;
    }

    /**
     * Sets I Pv 4 Address field.
     *
     * @param string|null $value
     */
    public function iPv4Address(?string $value): self
    {
        $this->instance->setIPv4Address($value);
        return $this;
    }

    /**
     * Sets I Pv 6 Address field.
     *
     * @param string|null $value
     */
    public function iPv6Address(?string $value): self
    {
        $this->instance->setIPv6Address($value);
        return $this;
    }

    /**
     * Sets Mac Address field.
     *
     * @param string|null $value
     */
    public function macAddress(?string $value): self
    {
        $this->instance->setMacAddress($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new Network Container object.
     */
    public function build(): NetworkContainer
    {
        return CoreHelper::clone($this->instance);
    }
}
