<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\EndpointSettings;
use DockerLib\Models\NetworkingConfig2;

/**
 * Builder for model NetworkingConfig2
 *
 * @see NetworkingConfig2
 */
class NetworkingConfig2Builder
{
    /**
     * @var NetworkingConfig2
     */
    private $instance;

    private function __construct(NetworkingConfig2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Networking Config 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new NetworkingConfig2());
    }

    /**
     * Sets Endpoints Config field.
     *
     * @param array<string,EndpointSettings>|null $value
     */
    public function endpointsConfig(?array $value): self
    {
        $this->instance->setEndpointsConfig($value);
        return $this;
    }

    /**
     * Initializes a new Networking Config 2 object.
     */
    public function build(): NetworkingConfig2
    {
        return CoreHelper::clone($this->instance);
    }
}
