<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\NetworksDisconnectRequest;

/**
 * Builder for model NetworksDisconnectRequest
 *
 * @see NetworksDisconnectRequest
 */
class NetworksDisconnectRequestBuilder
{
    /**
     * @var NetworksDisconnectRequest
     */
    private $instance;

    private function __construct(NetworksDisconnectRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Networks Disconnect Request Builder object.
     */
    public static function init(): self
    {
        return new self(new NetworksDisconnectRequest());
    }

    /**
     * Sets Container field.
     *
     * @param string|null $value
     */
    public function container(?string $value): self
    {
        $this->instance->setContainer($value);
        return $this;
    }

    /**
     * Sets Force field.
     *
     * @param bool|null $value
     */
    public function force(?bool $value): self
    {
        $this->instance->setForce($value);
        return $this;
    }

    /**
     * Initializes a new Networks Disconnect Request object.
     */
    public function build(): NetworksDisconnectRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
