<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\NodeSpec;

/**
 * Builder for model NodeSpec
 *
 * @see NodeSpec
 */
class NodeSpecBuilder
{
    /**
     * @var NodeSpec
     */
    private $instance;

    private function __construct(NodeSpec $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Node Spec Builder object.
     */
    public static function init(): self
    {
        return new self(new NodeSpec());
    }

    /**
     * Sets Availability field.
     *
     * @param string|null $value
     */
    public function availability(?string $value): self
    {
        $this->instance->setAvailability($value);
        return $this;
    }

    /**
     * Sets Labels field.
     *
     * @param array<string,string>|null $value
     */
    public function labels(?array $value): self
    {
        $this->instance->setLabels($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets Role field.
     *
     * @param string|null $value
     */
    public function role(?string $value): self
    {
        $this->instance->setRole($value);
        return $this;
    }

    /**
     * Initializes a new Node Spec object.
     */
    public function build(): NodeSpec
    {
        return CoreHelper::clone($this->instance);
    }
}
