<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Page;

/**
 * Builder for model Page
 *
 * @see Page
 */
class PageBuilder
{
    /**
     * @var Page
     */
    private $instance;

    private function __construct(Page $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Page Builder object.
     */
    public static function init(): self
    {
        return new self(new Page());
    }

    /**
     * Sets count field.
     *
     * @param int|null $value
     */
    public function count(?int $value): self
    {
        $this->instance->setCount($value);
        return $this;
    }

    /**
     * Sets next field.
     *
     * @param string|null $value
     */
    public function next(?string $value): self
    {
        $this->instance->setNext($value);
        return $this;
    }

    /**
     * Unsets next field.
     */
    public function unsetNext(): self
    {
        $this->instance->unsetNext();
        return $this;
    }

    /**
     * Sets previous field.
     *
     * @param string|null $value
     */
    public function previous(?string $value): self
    {
        $this->instance->setPrevious($value);
        return $this;
    }

    /**
     * Unsets previous field.
     */
    public function unsetPrevious(): self
    {
        $this->instance->unsetPrevious();
        return $this;
    }

    /**
     * Initializes a new Page object.
     */
    public function build(): Page
    {
        return CoreHelper::clone($this->instance);
    }
}
