<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\PaginatedTags;
use DockerLib\Models\Tag;

/**
 * Builder for model PaginatedTags
 *
 * @see PaginatedTags
 */
class PaginatedTagsBuilder
{
    /**
     * @var PaginatedTags
     */
    private $instance;

    private function __construct(PaginatedTags $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Paginated Tags Builder object.
     */
    public static function init(): self
    {
        return new self(new PaginatedTags());
    }

    /**
     * Sets count field.
     *
     * @param int|null $value
     */
    public function count(?int $value): self
    {
        $this->instance->setCount($value);
        return $this;
    }

    /**
     * Sets next field.
     *
     * @param string|null $value
     */
    public function next(?string $value): self
    {
        $this->instance->setNext($value);
        return $this;
    }

    /**
     * Unsets next field.
     */
    public function unsetNext(): self
    {
        $this->instance->unsetNext();
        return $this;
    }

    /**
     * Sets previous field.
     *
     * @param string|null $value
     */
    public function previous(?string $value): self
    {
        $this->instance->setPrevious($value);
        return $this;
    }

    /**
     * Unsets previous field.
     */
    public function unsetPrevious(): self
    {
        $this->instance->unsetPrevious();
        return $this;
    }

    /**
     * Sets results field.
     *
     * @param Tag[]|null $value
     */
    public function results(?array $value): self
    {
        $this->instance->setResults($value);
        return $this;
    }

    /**
     * Initializes a new Paginated Tags object.
     */
    public function build(): PaginatedTags
    {
        return CoreHelper::clone($this->instance);
    }
}
