<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Config22;
use DockerLib\Models\Plugin;
use DockerLib\Models\Settings2;

/**
 * Builder for model Plugin
 *
 * @see Plugin
 */
class PluginBuilder
{
    /**
     * @var Plugin
     */
    private $instance;

    private function __construct(Plugin $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Plugin Builder object.
     *
     * @param Config22 $config
     * @param bool $enabled
     * @param string $name
     * @param Settings2 $settings
     */
    public static function init(Config22 $config, bool $enabled, string $name, Settings2 $settings): self
    {
        return new self(new Plugin($config, $enabled, $name, $settings));
    }

    /**
     * Sets Id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets Plugin Reference field.
     *
     * @param string|null $value
     */
    public function pluginReference(?string $value): self
    {
        $this->instance->setPluginReference($value);
        return $this;
    }

    /**
     * Initializes a new Plugin object.
     */
    public function build(): Plugin
    {
        return CoreHelper::clone($this->instance);
    }
}
