<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\PluginDevice;

/**
 * Builder for model PluginDevice
 *
 * @see PluginDevice
 */
class PluginDeviceBuilder
{
    /**
     * @var PluginDevice
     */
    private $instance;

    private function __construct(PluginDevice $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Plugin Device Builder object.
     *
     * @param string $description
     * @param string $name
     * @param string $path
     * @param string[] $settable
     */
    public static function init(string $description, string $name, string $path, array $settable): self
    {
        return new self(new PluginDevice($description, $name, $path, $settable));
    }

    /**
     * Initializes a new Plugin Device object.
     */
    public function build(): PluginDevice
    {
        return CoreHelper::clone($this->instance);
    }
}
