<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\PluginPrivilege;
use DockerLib\Models\PluginSpec;

/**
 * Builder for model PluginSpec
 *
 * @see PluginSpec
 */
class PluginSpecBuilder
{
    /**
     * @var PluginSpec
     */
    private $instance;

    private function __construct(PluginSpec $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Plugin Spec Builder object.
     */
    public static function init(): self
    {
        return new self(new PluginSpec());
    }

    /**
     * Sets Disabled field.
     *
     * @param bool|null $value
     */
    public function disabled(?bool $value): self
    {
        $this->instance->setDisabled($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets Plugin Privilege field.
     *
     * @param PluginPrivilege[]|null $value
     */
    public function pluginPrivilege(?array $value): self
    {
        $this->instance->setPluginPrivilege($value);
        return $this;
    }

    /**
     * Sets Remote field.
     *
     * @param string|null $value
     */
    public function remote(?string $value): self
    {
        $this->instance->setRemote($value);
        return $this;
    }

    /**
     * Initializes a new Plugin Spec object.
     */
    public function build(): PluginSpec
    {
        return CoreHelper::clone($this->instance);
    }
}
