<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\PluginEnv;

/**
 * Builder for model PluginEnv
 *
 * @see PluginEnv
 */
class PluginEnvBuilder
{
    /**
     * @var PluginEnv
     */
    private $instance;

    private function __construct(PluginEnv $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Plugin Env Builder object.
     *
     * @param string $description
     * @param string $name
     * @param string[] $settable
     * @param string $value
     */
    public static function init(string $description, string $name, array $settable, string $value): self
    {
        return new self(new PluginEnv($description, $name, $settable, $value));
    }

    /**
     * Initializes a new Plugin Env object.
     */
    public function build(): PluginEnv
    {
        return CoreHelper::clone($this->instance);
    }
}
