<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\PostUsersLoginErrorResponse;

/**
 * Builder for model PostUsersLoginErrorResponse
 *
 * @see PostUsersLoginErrorResponse
 */
class PostUsersLoginErrorResponseBuilder
{
    /**
     * @var PostUsersLoginErrorResponse
     */
    private $instance;

    private function __construct(PostUsersLoginErrorResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Post Users Login Error Response Builder object.
     *
     * @param string $detail
     */
    public static function init(string $detail): self
    {
        return new self(new PostUsersLoginErrorResponse($detail));
    }

    /**
     * Sets login 2 fa token field.
     *
     * @param string|null $value
     */
    public function login2faToken(?string $value): self
    {
        $this->instance->setLogin2faToken($value);
        return $this;
    }

    /**
     * Unsets login 2 fa token field.
     */
    public function unsetLogin2faToken(): self
    {
        $this->instance->unsetLogin2faToken();
        return $this;
    }

    /**
     * Initializes a new Post Users Login Error Response object.
     */
    public function build(): PostUsersLoginErrorResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
