<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Metrics;
use DockerLib\Models\PostNamespacesDeleteImagesResponseSuccess;

/**
 * Builder for model PostNamespacesDeleteImagesResponseSuccess
 *
 * @see PostNamespacesDeleteImagesResponseSuccess
 */
class PostNamespacesDeleteImagesResponseSuccessBuilder
{
    /**
     * @var PostNamespacesDeleteImagesResponseSuccess
     */
    private $instance;

    private function __construct(PostNamespacesDeleteImagesResponseSuccess $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Post Namespaces Delete Images Response Success Builder object.
     */
    public static function init(): self
    {
        return new self(new PostNamespacesDeleteImagesResponseSuccess());
    }

    /**
     * Sets dry run field.
     *
     * @param bool|null $value
     */
    public function dryRun(?bool $value): self
    {
        $this->instance->setDryRun($value);
        return $this;
    }

    /**
     * Sets metrics field.
     *
     * @param Metrics|null $value
     */
    public function metrics(?Metrics $value): self
    {
        $this->instance->setMetrics($value);
        return $this;
    }

    /**
     * Initializes a new Post Namespaces Delete Images Response Success object.
     */
    public function build(): PostNamespacesDeleteImagesResponseSuccess
    {
        return CoreHelper::clone($this->instance);
    }
}
