<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\CredentialSpec2;
use DockerLib\Models\Privileges;
use DockerLib\Models\SELinuxContext2;

/**
 * Builder for model Privileges
 *
 * @see Privileges
 */
class PrivilegesBuilder
{
    /**
     * @var Privileges
     */
    private $instance;

    private function __construct(Privileges $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Privileges Builder object.
     */
    public static function init(): self
    {
        return new self(new Privileges());
    }

    /**
     * Sets Credential Spec field.
     *
     * @param CredentialSpec2|null $value
     */
    public function credentialSpec(?CredentialSpec2 $value): self
    {
        $this->instance->setCredentialSpec($value);
        return $this;
    }

    /**
     * Sets SE Linux Context field.
     *
     * @param SELinuxContext2|null $value
     */
    public function sELinuxContext(?SELinuxContext2 $value): self
    {
        $this->instance->setSELinuxContext($value);
        return $this;
    }

    /**
     * Initializes a new Privileges object.
     */
    public function build(): Privileges
    {
        return CoreHelper::clone($this->instance);
    }
}
