<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ProcessConfig;

/**
 * Builder for model ProcessConfig
 *
 * @see ProcessConfig
 */
class ProcessConfigBuilder
{
    /**
     * @var ProcessConfig
     */
    private $instance;

    private function __construct(ProcessConfig $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Process Config Builder object.
     */
    public static function init(): self
    {
        return new self(new ProcessConfig());
    }

    /**
     * Sets arguments field.
     *
     * @param string[]|null $value
     */
    public function arguments(?array $value): self
    {
        $this->instance->setArguments($value);
        return $this;
    }

    /**
     * Sets entrypoint field.
     *
     * @param string|null $value
     */
    public function entrypoint(?string $value): self
    {
        $this->instance->setEntrypoint($value);
        return $this;
    }

    /**
     * Sets privileged field.
     *
     * @param bool|null $value
     */
    public function privileged(?bool $value): self
    {
        $this->instance->setPrivileged($value);
        return $this;
    }

    /**
     * Sets tty field.
     *
     * @param bool|null $value
     */
    public function tty(?bool $value): self
    {
        $this->instance->setTty($value);
        return $this;
    }

    /**
     * Sets user field.
     *
     * @param string|null $value
     */
    public function user(?string $value): self
    {
        $this->instance->setUser($value);
        return $this;
    }

    /**
     * Initializes a new Process Config object.
     */
    public function build(): ProcessConfig
    {
        return CoreHelper::clone($this->instance);
    }
}
