<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ProgressDetail;

/**
 * Builder for model ProgressDetail
 *
 * @see ProgressDetail
 */
class ProgressDetailBuilder
{
    /**
     * @var ProgressDetail
     */
    private $instance;

    private function __construct(ProgressDetail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Progress Detail Builder object.
     */
    public static function init(): self
    {
        return new self(new ProgressDetail());
    }

    /**
     * Sets code field.
     *
     * @param int|null $value
     */
    public function code(?int $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param int|null $value
     */
    public function message(?int $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Initializes a new Progress Detail object.
     */
    public function build(): ProgressDetail
    {
        return CoreHelper::clone($this->instance);
    }
}
