<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ProgressDetail;
use DockerLib\Models\PushImageInfo;

/**
 * Builder for model PushImageInfo
 *
 * @see PushImageInfo
 */
class PushImageInfoBuilder
{
    /**
     * @var PushImageInfo
     */
    private $instance;

    private function __construct(PushImageInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Push Image Info Builder object.
     */
    public static function init(): self
    {
        return new self(new PushImageInfo());
    }

    /**
     * Sets error field.
     *
     * @param string|null $value
     */
    public function error(?string $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Sets progress field.
     *
     * @param string|null $value
     */
    public function progress(?string $value): self
    {
        $this->instance->setProgress($value);
        return $this;
    }

    /**
     * Sets progress Detail field.
     *
     * @param ProgressDetail|null $value
     */
    public function progressDetail(?ProgressDetail $value): self
    {
        $this->instance->setProgressDetail($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new Push Image Info object.
     */
    public function build(): PushImageInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
