<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\RestartPolicy1;

/**
 * Builder for model RestartPolicy1
 *
 * @see RestartPolicy1
 */
class RestartPolicy1Builder
{
    /**
     * @var RestartPolicy1
     */
    private $instance;

    private function __construct(RestartPolicy1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Restart Policy 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new RestartPolicy1());
    }

    /**
     * Sets Condition field.
     *
     * @param string|null $value
     */
    public function condition(?string $value): self
    {
        $this->instance->setCondition($value);
        return $this;
    }

    /**
     * Sets Delay field.
     *
     * @param int|null $value
     */
    public function delay(?int $value): self
    {
        $this->instance->setDelay($value);
        return $this;
    }

    /**
     * Sets Max Attempts field.
     *
     * @param int|null $value
     */
    public function maxAttempts(?int $value): self
    {
        $this->instance->setMaxAttempts($value);
        return $this;
    }

    /**
     * Sets Window field.
     *
     * @param int|null $value
     */
    public function window(?int $value): self
    {
        $this->instance->setWindow($value);
        return $this;
    }

    /**
     * Initializes a new Restart Policy 1 object.
     */
    public function build(): RestartPolicy1
    {
        return CoreHelper::clone($this->instance);
    }
}
