<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\RollbackConfig2;

/**
 * Builder for model RollbackConfig2
 *
 * @see RollbackConfig2
 */
class RollbackConfig2Builder
{
    /**
     * @var RollbackConfig2
     */
    private $instance;

    private function __construct(RollbackConfig2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Rollback Config 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new RollbackConfig2());
    }

    /**
     * Sets Delay field.
     *
     * @param int|null $value
     */
    public function delay(?int $value): self
    {
        $this->instance->setDelay($value);
        return $this;
    }

    /**
     * Sets Failure Action field.
     *
     * @param string|null $value
     */
    public function failureAction(?string $value): self
    {
        $this->instance->setFailureAction($value);
        return $this;
    }

    /**
     * Sets Max Failure Ratio field.
     *
     * @param float|null $value
     */
    public function maxFailureRatio(?float $value): self
    {
        $this->instance->setMaxFailureRatio($value);
        return $this;
    }

    /**
     * Sets Monitor field.
     *
     * @param int|null $value
     */
    public function monitor(?int $value): self
    {
        $this->instance->setMonitor($value);
        return $this;
    }

    /**
     * Sets Order field.
     *
     * @param string|null $value
     */
    public function order(?string $value): self
    {
        $this->instance->setOrder($value);
        return $this;
    }

    /**
     * Sets Parallelism field.
     *
     * @param int|null $value
     */
    public function parallelism(?int $value): self
    {
        $this->instance->setParallelism($value);
        return $this;
    }

    /**
     * Initializes a new Rollback Config 2 object.
     */
    public function build(): RollbackConfig2
    {
        return CoreHelper::clone($this->instance);
    }
}
