<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\RootFS;

/**
 * Builder for model RootFS
 *
 * @see RootFS
 */
class RootFSBuilder
{
    /**
     * @var RootFS
     */
    private $instance;

    private function __construct(RootFS $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Root FS Builder object.
     *
     * @param string $type
     */
    public static function init(string $type): self
    {
        return new self(new RootFS($type));
    }

    /**
     * Sets Base Layer field.
     *
     * @param string|null $value
     */
    public function baseLayer(?string $value): self
    {
        $this->instance->setBaseLayer($value);
        return $this;
    }

    /**
     * Sets Layers field.
     *
     * @param string[]|null $value
     */
    public function layers(?array $value): self
    {
        $this->instance->setLayers($value);
        return $this;
    }

    /**
     * Initializes a new Root FS object.
     */
    public function build(): RootFS
    {
        return CoreHelper::clone($this->instance);
    }
}
