<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\AuthenticationSchemes;
use DockerLib\Models\Bulk;
use DockerLib\Models\ChangePassword;
use DockerLib\Models\Etag;
use DockerLib\Models\Filter;
use DockerLib\Models\Patch;
use DockerLib\Models\ScimServiceProviderConfig;
use DockerLib\Models\Sort;

/**
 * Builder for model ScimServiceProviderConfig
 *
 * @see ScimServiceProviderConfig
 */
class ScimServiceProviderConfigBuilder
{
    /**
     * @var ScimServiceProviderConfig
     */
    private $instance;

    private function __construct(ScimServiceProviderConfig $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Scim Service Provider Config Builder object.
     */
    public static function init(): self
    {
        return new self(new ScimServiceProviderConfig());
    }

    /**
     * Sets authentication Schemes field.
     *
     * @param AuthenticationSchemes|null $value
     */
    public function authenticationSchemes(?AuthenticationSchemes $value): self
    {
        $this->instance->setAuthenticationSchemes($value);
        return $this;
    }

    /**
     * Sets bulk field.
     *
     * @param Bulk|null $value
     */
    public function bulk(?Bulk $value): self
    {
        $this->instance->setBulk($value);
        return $this;
    }

    /**
     * Sets change Password field.
     *
     * @param ChangePassword|null $value
     */
    public function changePassword(?ChangePassword $value): self
    {
        $this->instance->setChangePassword($value);
        return $this;
    }

    /**
     * Sets documentation Uri field.
     *
     * @param string|null $value
     */
    public function documentationUri(?string $value): self
    {
        $this->instance->setDocumentationUri($value);
        return $this;
    }

    /**
     * Sets etag field.
     *
     * @param Etag|null $value
     */
    public function etag(?Etag $value): self
    {
        $this->instance->setEtag($value);
        return $this;
    }

    /**
     * Sets filter field.
     *
     * @param Filter|null $value
     */
    public function filter(?Filter $value): self
    {
        $this->instance->setFilter($value);
        return $this;
    }

    /**
     * Sets patch field.
     *
     * @param Patch|null $value
     */
    public function patch(?Patch $value): self
    {
        $this->instance->setPatch($value);
        return $this;
    }

    /**
     * Sets schemas field.
     *
     * @param string[]|null $value
     */
    public function schemas(?array $value): self
    {
        $this->instance->setSchemas($value);
        return $this;
    }

    /**
     * Sets sort field.
     *
     * @param Sort|null $value
     */
    public function sort(?Sort $value): self
    {
        $this->instance->setSort($value);
        return $this;
    }

    /**
     * Initializes a new Scim Service Provider Config object.
     */
    public function build(): ScimServiceProviderConfig
    {
        return CoreHelper::clone($this->instance);
    }
}
