<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Meta;
use DockerLib\Models\ScimEmail;
use DockerLib\Models\ScimGroup;
use DockerLib\Models\ScimUser;
use DockerLib\Models\ScimUserName;

/**
 * Builder for model ScimUser
 *
 * @see ScimUser
 */
class ScimUserBuilder
{
    /**
     * @var ScimUser
     */
    private $instance;

    private function __construct(ScimUser $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Scim User Builder object.
     */
    public static function init(): self
    {
        return new self(new ScimUser());
    }

    /**
     * Sets active field.
     *
     * @param bool|null $value
     */
    public function active(?bool $value): self
    {
        $this->instance->setActive($value);
        return $this;
    }

    /**
     * Sets display Name field.
     *
     * @param string|null $value
     */
    public function displayName(?string $value): self
    {
        $this->instance->setDisplayName($value);
        return $this;
    }

    /**
     * Sets emails field.
     *
     * @param ScimEmail[]|null $value
     */
    public function emails(?array $value): self
    {
        $this->instance->setEmails($value);
        return $this;
    }

    /**
     * Sets groups field.
     *
     * @param ScimGroup[]|null $value
     */
    public function groups(?array $value): self
    {
        $this->instance->setGroups($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets meta field.
     *
     * @param Meta|null $value
     */
    public function meta(?Meta $value): self
    {
        $this->instance->setMeta($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param ScimUserName|null $value
     */
    public function name(?ScimUserName $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets schemas field.
     *
     * @param string[]|null $value
     */
    public function schemas(?array $value): self
    {
        $this->instance->setSchemas($value);
        return $this;
    }

    /**
     * Sets user Name field.
     *
     * @param string|null $value
     */
    public function userName(?string $value): self
    {
        $this->instance->setUserName($value);
        return $this;
    }

    /**
     * Initializes a new Scim User object.
     */
    public function build(): ScimUser
    {
        return CoreHelper::clone($this->instance);
    }
}
