<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ScimUpdateUserRequest;
use DockerLib\Models\ScimUserName;

/**
 * Builder for model ScimUpdateUserRequest
 *
 * @see ScimUpdateUserRequest
 */
class ScimUpdateUserRequestBuilder
{
    /**
     * @var ScimUpdateUserRequest
     */
    private $instance;

    private function __construct(ScimUpdateUserRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Scim Update User Request Builder object.
     *
     * @param string[] $schemas
     */
    public static function init(array $schemas): self
    {
        return new self(new ScimUpdateUserRequest($schemas));
    }

    /**
     * Sets enabled field.
     *
     * @param bool|null $value
     */
    public function enabled(?bool $value): self
    {
        $this->instance->setEnabled($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param ScimUserName|null $value
     */
    public function name(?ScimUserName $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new Scim Update User Request object.
     */
    public function build(): ScimUpdateUserRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
