<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ScimEmail;

/**
 * Builder for model ScimEmail
 *
 * @see ScimEmail
 */
class ScimEmailBuilder
{
    /**
     * @var ScimEmail
     */
    private $instance;

    private function __construct(ScimEmail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Scim Email Builder object.
     */
    public static function init(): self
    {
        return new self(new ScimEmail());
    }

    /**
     * Sets display field.
     *
     * @param string|null $value
     */
    public function display(?string $value): self
    {
        $this->instance->setDisplay($value);
        return $this;
    }

    /**
     * Sets primary field.
     *
     * @param bool|null $value
     */
    public function primary(?bool $value): self
    {
        $this->instance->setPrimary($value);
        return $this;
    }

    /**
     * Sets value field.
     *
     * @param string|null $value
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Initializes a new Scim Email object.
     */
    public function build(): ScimEmail
    {
        return CoreHelper::clone($this->instance);
    }
}
