<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ScimSchemaAttribute;
use DockerLib\Models\ScimSchemaParentAttribute;

/**
 * Builder for model ScimSchemaParentAttribute
 *
 * @see ScimSchemaParentAttribute
 */
class ScimSchemaParentAttributeBuilder
{
    /**
     * @var ScimSchemaParentAttribute
     */
    private $instance;

    private function __construct(ScimSchemaParentAttribute $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Scim Schema Parent Attribute Builder object.
     */
    public static function init(): self
    {
        return new self(new ScimSchemaParentAttribute());
    }

    /**
     * Sets case Exact field.
     *
     * @param bool|null $value
     */
    public function caseExact(?bool $value): self
    {
        $this->instance->setCaseExact($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets multi Valued field.
     *
     * @param bool|null $value
     */
    public function multiValued(?bool $value): self
    {
        $this->instance->setMultiValued($value);
        return $this;
    }

    /**
     * Sets mutability field.
     *
     * @param string|null $value
     */
    public function mutability(?string $value): self
    {
        $this->instance->setMutability($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets required field.
     *
     * @param bool|null $value
     */
    public function required(?bool $value): self
    {
        $this->instance->setRequired($value);
        return $this;
    }

    /**
     * Sets returned field.
     *
     * @param string|null $value
     */
    public function returned(?string $value): self
    {
        $this->instance->setReturned($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets uniqueness field.
     *
     * @param string|null $value
     */
    public function uniqueness(?string $value): self
    {
        $this->instance->setUniqueness($value);
        return $this;
    }

    /**
     * Sets sub Attributes field.
     *
     * @param ScimSchemaAttribute[]|null $value
     */
    public function subAttributes(?array $value): self
    {
        $this->instance->setSubAttributes($value);
        return $this;
    }

    /**
     * Initializes a new Scim Schema Parent Attribute object.
     */
    public function build(): ScimSchemaParentAttribute
    {
        return CoreHelper::clone($this->instance);
    }
}
