<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\SecretsCreateResponse;

/**
 * Builder for model SecretsCreateResponse
 *
 * @see SecretsCreateResponse
 */
class SecretsCreateResponseBuilder
{
    /**
     * @var SecretsCreateResponse
     */
    private $instance;

    private function __construct(SecretsCreateResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Secrets Create Response Builder object.
     */
    public static function init(): self
    {
        return new self(new SecretsCreateResponse());
    }

    /**
     * Sets ID field.
     *
     * @param string|null $value
     */
    public function iD(?string $value): self
    {
        $this->instance->setID($value);
        return $this;
    }

    /**
     * Initializes a new Secrets Create Response object.
     */
    public function build(): SecretsCreateResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
