<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Driver1;
use DockerLib\Models\SecretSpec;

/**
 * Builder for model SecretSpec
 *
 * @see SecretSpec
 */
class SecretSpecBuilder
{
    /**
     * @var SecretSpec
     */
    private $instance;

    private function __construct(SecretSpec $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Secret Spec Builder object.
     */
    public static function init(): self
    {
        return new self(new SecretSpec());
    }

    /**
     * Sets Data field.
     *
     * @param string|null $value
     */
    public function data(?string $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets Driver field.
     *
     * @param Driver1|null $value
     */
    public function driver(?Driver1 $value): self
    {
        $this->instance->setDriver($value);
        return $this;
    }

    /**
     * Sets Labels field.
     *
     * @param array<string,string>|null $value
     */
    public function labels(?array $value): self
    {
        $this->instance->setLabels($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new Secret Spec object.
     */
    public function build(): SecretSpec
    {
        return CoreHelper::clone($this->instance);
    }
}
