<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\SELinuxContext2;

/**
 * Builder for model SELinuxContext2
 *
 * @see SELinuxContext2
 */
class SELinuxContext2Builder
{
    /**
     * @var SELinuxContext2
     */
    private $instance;

    private function __construct(SELinuxContext2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new SE Linux Context 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new SELinuxContext2());
    }

    /**
     * Sets Disable field.
     *
     * @param bool|null $value
     */
    public function disable(?bool $value): self
    {
        $this->instance->setDisable($value);
        return $this;
    }

    /**
     * Sets Level field.
     *
     * @param string|null $value
     */
    public function level(?string $value): self
    {
        $this->instance->setLevel($value);
        return $this;
    }

    /**
     * Sets Role field.
     *
     * @param string|null $value
     */
    public function role(?string $value): self
    {
        $this->instance->setRole($value);
        return $this;
    }

    /**
     * Sets Type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets User field.
     *
     * @param string|null $value
     */
    public function user(?string $value): self
    {
        $this->instance->setUser($value);
        return $this;
    }

    /**
     * Initializes a new SE Linux Context 2 object.
     */
    public function build(): SELinuxContext2
    {
        return CoreHelper::clone($this->instance);
    }
}
