<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Endpoint;
use DockerLib\Models\Service;
use DockerLib\Models\ServicesCreateRequest;
use DockerLib\Models\UpdateStatus2;
use DockerLib\Models\Version;

/**
 * Builder for model Service
 *
 * @see Service
 */
class ServiceBuilder
{
    /**
     * @var Service
     */
    private $instance;

    private function __construct(Service $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Service Builder object.
     */
    public static function init(): self
    {
        return new self(new Service());
    }

    /**
     * Sets Created At field.
     *
     * @param string|null $value
     */
    public function createdAt(?string $value): self
    {
        $this->instance->setCreatedAt($value);
        return $this;
    }

    /**
     * Sets Endpoint field.
     *
     * @param Endpoint|null $value
     */
    public function endpoint(?Endpoint $value): self
    {
        $this->instance->setEndpoint($value);
        return $this;
    }

    /**
     * Sets ID field.
     *
     * @param string|null $value
     */
    public function iD(?string $value): self
    {
        $this->instance->setID($value);
        return $this;
    }

    /**
     * Sets Spec field.
     *
     * @param ServicesCreateRequest|null $value
     */
    public function spec(?ServicesCreateRequest $value): self
    {
        $this->instance->setSpec($value);
        return $this;
    }

    /**
     * Sets Update Status field.
     *
     * @param UpdateStatus2|null $value
     */
    public function updateStatus(?UpdateStatus2 $value): self
    {
        $this->instance->setUpdateStatus($value);
        return $this;
    }

    /**
     * Sets Updated At field.
     *
     * @param string|null $value
     */
    public function updatedAt(?string $value): self
    {
        $this->instance->setUpdatedAt($value);
        return $this;
    }

    /**
     * Sets Version field.
     *
     * @param Version|null $value
     */
    public function version(?Version $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Initializes a new Service object.
     */
    public function build(): Service
    {
        return CoreHelper::clone($this->instance);
    }
}
