<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Sort;

/**
 * Builder for model Sort
 *
 * @see Sort
 */
class SortBuilder
{
    /**
     * @var Sort
     */
    private $instance;

    private function __construct(Sort $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Sort Builder object.
     */
    public static function init(): self
    {
        return new self(new Sort());
    }

    /**
     * Sets supported field.
     *
     * @param bool|null $value
     */
    public function supported(?bool $value): self
    {
        $this->instance->setSupported($value);
        return $this;
    }

    /**
     * Initializes a new Sort object.
     */
    public function build(): Sort
    {
        return CoreHelper::clone($this->instance);
    }
}
