<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ContainerdCommit;
use DockerLib\Models\GenericResource;
use DockerLib\Models\InitCommit;
use DockerLib\Models\Plugins;
use DockerLib\Models\RuncCommit;
use DockerLib\Models\Runtime;
use DockerLib\Models\Swarm1;
use DockerLib\Models\SystemInfo;

/**
 * Builder for model SystemInfo
 *
 * @see SystemInfo
 */
class SystemInfoBuilder
{
    /**
     * @var SystemInfo
     */
    private $instance;

    private function __construct(SystemInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new System Info Builder object.
     */
    public static function init(): self
    {
        return new self(new SystemInfo());
    }

    /**
     * Sets Architecture field.
     *
     * @param string|null $value
     */
    public function architecture(?string $value): self
    {
        $this->instance->setArchitecture($value);
        return $this;
    }

    /**
     * Sets Bridge Nf Ip 6 tables field.
     *
     * @param bool|null $value
     */
    public function bridgeNfIp6tables(?bool $value): self
    {
        $this->instance->setBridgeNfIp6tables($value);
        return $this;
    }

    /**
     * Sets Bridge Nf Iptables field.
     *
     * @param bool|null $value
     */
    public function bridgeNfIptables(?bool $value): self
    {
        $this->instance->setBridgeNfIptables($value);
        return $this;
    }

    /**
     * Sets CPU Set field.
     *
     * @param bool|null $value
     */
    public function cPUSet(?bool $value): self
    {
        $this->instance->setCPUSet($value);
        return $this;
    }

    /**
     * Sets CPU Shares field.
     *
     * @param bool|null $value
     */
    public function cPUShares(?bool $value): self
    {
        $this->instance->setCPUShares($value);
        return $this;
    }

    /**
     * Sets Cgroup Driver field.
     *
     * @param string|null $value
     */
    public function cgroupDriver(?string $value): self
    {
        $this->instance->setCgroupDriver($value);
        return $this;
    }

    /**
     * Sets Cluster Advertise field.
     *
     * @param string|null $value
     */
    public function clusterAdvertise(?string $value): self
    {
        $this->instance->setClusterAdvertise($value);
        return $this;
    }

    /**
     * Sets Cluster Store field.
     *
     * @param string|null $value
     */
    public function clusterStore(?string $value): self
    {
        $this->instance->setClusterStore($value);
        return $this;
    }

    /**
     * Sets Containerd Commit field.
     *
     * @param ContainerdCommit|null $value
     */
    public function containerdCommit(?ContainerdCommit $value): self
    {
        $this->instance->setContainerdCommit($value);
        return $this;
    }

    /**
     * Sets Containers field.
     *
     * @param int|null $value
     */
    public function containers(?int $value): self
    {
        $this->instance->setContainers($value);
        return $this;
    }

    /**
     * Sets Containers Paused field.
     *
     * @param int|null $value
     */
    public function containersPaused(?int $value): self
    {
        $this->instance->setContainersPaused($value);
        return $this;
    }

    /**
     * Sets Containers Running field.
     *
     * @param int|null $value
     */
    public function containersRunning(?int $value): self
    {
        $this->instance->setContainersRunning($value);
        return $this;
    }

    /**
     * Sets Containers Stopped field.
     *
     * @param int|null $value
     */
    public function containersStopped(?int $value): self
    {
        $this->instance->setContainersStopped($value);
        return $this;
    }

    /**
     * Sets Cpu Cfs Period field.
     *
     * @param bool|null $value
     */
    public function cpuCfsPeriod(?bool $value): self
    {
        $this->instance->setCpuCfsPeriod($value);
        return $this;
    }

    /**
     * Sets Cpu Cfs Quota field.
     *
     * @param bool|null $value
     */
    public function cpuCfsQuota(?bool $value): self
    {
        $this->instance->setCpuCfsQuota($value);
        return $this;
    }

    /**
     * Sets Debug field.
     *
     * @param bool|null $value
     */
    public function debug(?bool $value): self
    {
        $this->instance->setDebug($value);
        return $this;
    }

    /**
     * Sets Default Runtime field.
     *
     * @param string|null $value
     */
    public function defaultRuntime(?string $value): self
    {
        $this->instance->setDefaultRuntime($value);
        return $this;
    }

    /**
     * Sets Docker Root Dir field.
     *
     * @param string|null $value
     */
    public function dockerRootDir(?string $value): self
    {
        $this->instance->setDockerRootDir($value);
        return $this;
    }

    /**
     * Sets Driver field.
     *
     * @param string|null $value
     */
    public function driver(?string $value): self
    {
        $this->instance->setDriver($value);
        return $this;
    }

    /**
     * Sets Driver Status field.
     *
     * @param string[][]|null $value
     */
    public function driverStatus(?array $value): self
    {
        $this->instance->setDriverStatus($value);
        return $this;
    }

    /**
     * Sets Experimental Build field.
     *
     * @param bool|null $value
     */
    public function experimentalBuild(?bool $value): self
    {
        $this->instance->setExperimentalBuild($value);
        return $this;
    }

    /**
     * Sets Generic Resources field.
     *
     * @param GenericResource[]|null $value
     */
    public function genericResources(?array $value): self
    {
        $this->instance->setGenericResources($value);
        return $this;
    }

    /**
     * Sets Http Proxy field.
     *
     * @param string|null $value
     */
    public function httpProxy(?string $value): self
    {
        $this->instance->setHttpProxy($value);
        return $this;
    }

    /**
     * Sets Https Proxy field.
     *
     * @param string|null $value
     */
    public function httpsProxy(?string $value): self
    {
        $this->instance->setHttpsProxy($value);
        return $this;
    }

    /**
     * Sets ID field.
     *
     * @param string|null $value
     */
    public function iD(?string $value): self
    {
        $this->instance->setID($value);
        return $this;
    }

    /**
     * Sets I Pv 4 Forwarding field.
     *
     * @param bool|null $value
     */
    public function iPv4Forwarding(?bool $value): self
    {
        $this->instance->setIPv4Forwarding($value);
        return $this;
    }

    /**
     * Sets Images field.
     *
     * @param int|null $value
     */
    public function images(?int $value): self
    {
        $this->instance->setImages($value);
        return $this;
    }

    /**
     * Sets Index Server Address field.
     *
     * @param string|null $value
     */
    public function indexServerAddress(?string $value): self
    {
        $this->instance->setIndexServerAddress($value);
        return $this;
    }

    /**
     * Sets Init Binary field.
     *
     * @param string|null $value
     */
    public function initBinary(?string $value): self
    {
        $this->instance->setInitBinary($value);
        return $this;
    }

    /**
     * Sets Init Commit field.
     *
     * @param InitCommit|null $value
     */
    public function initCommit(?InitCommit $value): self
    {
        $this->instance->setInitCommit($value);
        return $this;
    }

    /**
     * Sets Isolation field.
     *
     * @param string|null $value
     */
    public function isolation(?string $value): self
    {
        $this->instance->setIsolation($value);
        return $this;
    }

    /**
     * Sets Kernel Memory field.
     *
     * @param bool|null $value
     */
    public function kernelMemory(?bool $value): self
    {
        $this->instance->setKernelMemory($value);
        return $this;
    }

    /**
     * Sets Kernel Version field.
     *
     * @param string|null $value
     */
    public function kernelVersion(?string $value): self
    {
        $this->instance->setKernelVersion($value);
        return $this;
    }

    /**
     * Sets Labels field.
     *
     * @param string[]|null $value
     */
    public function labels(?array $value): self
    {
        $this->instance->setLabels($value);
        return $this;
    }

    /**
     * Sets Live Restore Enabled field.
     *
     * @param bool|null $value
     */
    public function liveRestoreEnabled(?bool $value): self
    {
        $this->instance->setLiveRestoreEnabled($value);
        return $this;
    }

    /**
     * Sets Logging Driver field.
     *
     * @param string|null $value
     */
    public function loggingDriver(?string $value): self
    {
        $this->instance->setLoggingDriver($value);
        return $this;
    }

    /**
     * Sets Mem Total field.
     *
     * @param int|null $value
     */
    public function memTotal(?int $value): self
    {
        $this->instance->setMemTotal($value);
        return $this;
    }

    /**
     * Sets Memory Limit field.
     *
     * @param bool|null $value
     */
    public function memoryLimit(?bool $value): self
    {
        $this->instance->setMemoryLimit($value);
        return $this;
    }

    /**
     * Sets NCPU field.
     *
     * @param int|null $value
     */
    public function nCPU(?int $value): self
    {
        $this->instance->setNCPU($value);
        return $this;
    }

    /**
     * Sets N Events Listener field.
     *
     * @param int|null $value
     */
    public function nEventsListener(?int $value): self
    {
        $this->instance->setNEventsListener($value);
        return $this;
    }

    /**
     * Sets N Fd field.
     *
     * @param int|null $value
     */
    public function nFd(?int $value): self
    {
        $this->instance->setNFd($value);
        return $this;
    }

    /**
     * Sets N Goroutines field.
     *
     * @param int|null $value
     */
    public function nGoroutines(?int $value): self
    {
        $this->instance->setNGoroutines($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets No Proxy field.
     *
     * @param string|null $value
     */
    public function noProxy(?string $value): self
    {
        $this->instance->setNoProxy($value);
        return $this;
    }

    /**
     * Sets OS Type field.
     *
     * @param string|null $value
     */
    public function oSType(?string $value): self
    {
        $this->instance->setOSType($value);
        return $this;
    }

    /**
     * Sets Oom Kill Disable field.
     *
     * @param bool|null $value
     */
    public function oomKillDisable(?bool $value): self
    {
        $this->instance->setOomKillDisable($value);
        return $this;
    }

    /**
     * Sets Operating System field.
     *
     * @param string|null $value
     */
    public function operatingSystem(?string $value): self
    {
        $this->instance->setOperatingSystem($value);
        return $this;
    }

    /**
     * Sets Plugins field.
     *
     * @param Plugins|null $value
     */
    public function plugins(?Plugins $value): self
    {
        $this->instance->setPlugins($value);
        return $this;
    }

    /**
     * Sets Registry Config field.
     *
     * @param array|null $value
     */
    public function registryConfig(?array $value): self
    {
        $this->instance->setRegistryConfig($value);
        return $this;
    }

    /**
     * Sets Runc Commit field.
     *
     * @param RuncCommit|null $value
     */
    public function runcCommit(?RuncCommit $value): self
    {
        $this->instance->setRuncCommit($value);
        return $this;
    }

    /**
     * Sets Runtimes field.
     *
     * @param array<string,Runtime>|null $value
     */
    public function runtimes(?array $value): self
    {
        $this->instance->setRuntimes($value);
        return $this;
    }

    /**
     * Sets Security Options field.
     *
     * @param string[]|null $value
     */
    public function securityOptions(?array $value): self
    {
        $this->instance->setSecurityOptions($value);
        return $this;
    }

    /**
     * Sets Server Version field.
     *
     * @param string|null $value
     */
    public function serverVersion(?string $value): self
    {
        $this->instance->setServerVersion($value);
        return $this;
    }

    /**
     * Sets Swap Limit field.
     *
     * @param bool|null $value
     */
    public function swapLimit(?bool $value): self
    {
        $this->instance->setSwapLimit($value);
        return $this;
    }

    /**
     * Sets Swarm field.
     *
     * @param Swarm1|null $value
     */
    public function swarm(?Swarm1 $value): self
    {
        $this->instance->setSwarm($value);
        return $this;
    }

    /**
     * Sets System Status field.
     *
     * @param string[][]|null $value
     */
    public function systemStatus(?array $value): self
    {
        $this->instance->setSystemStatus($value);
        return $this;
    }

    /**
     * Sets System Time field.
     *
     * @param string|null $value
     */
    public function systemTime(?string $value): self
    {
        $this->instance->setSystemTime($value);
        return $this;
    }

    /**
     * Initializes a new System Info object.
     */
    public function build(): SystemInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
