<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Image1;
use DockerLib\Models\Tag;

/**
 * Builder for model Tag
 *
 * @see Tag
 */
class TagBuilder
{
    /**
     * @var Tag
     */
    private $instance;

    private function __construct(Tag $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Tag Builder object.
     */
    public static function init(): self
    {
        return new self(new Tag());
    }

    /**
     * Sets creator field.
     *
     * @param int|null $value
     */
    public function creator(?int $value): self
    {
        $this->instance->setCreator($value);
        return $this;
    }

    /**
     * Sets full size field.
     *
     * @param int|null $value
     */
    public function fullSize(?int $value): self
    {
        $this->instance->setFullSize($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param int|null $value
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets images field.
     *
     * @param Image1|null $value
     */
    public function images(?Image1 $value): self
    {
        $this->instance->setImages($value);
        return $this;
    }

    /**
     * Sets last updated field.
     *
     * @param string|null $value
     */
    public function lastUpdated(?string $value): self
    {
        $this->instance->setLastUpdated($value);
        return $this;
    }

    /**
     * Unsets last updated field.
     */
    public function unsetLastUpdated(): self
    {
        $this->instance->unsetLastUpdated();
        return $this;
    }

    /**
     * Sets last updater field.
     *
     * @param int|null $value
     */
    public function lastUpdater(?int $value): self
    {
        $this->instance->setLastUpdater($value);
        return $this;
    }

    /**
     * Sets last updater username field.
     *
     * @param string|null $value
     */
    public function lastUpdaterUsername(?string $value): self
    {
        $this->instance->setLastUpdaterUsername($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets repository field.
     *
     * @param int|null $value
     */
    public function repository(?int $value): self
    {
        $this->instance->setRepository($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets tag last pulled field.
     *
     * @param string|null $value
     */
    public function tagLastPulled(?string $value): self
    {
        $this->instance->setTagLastPulled($value);
        return $this;
    }

    /**
     * Unsets tag last pulled field.
     */
    public function unsetTagLastPulled(): self
    {
        $this->instance->unsetTagLastPulled();
        return $this;
    }

    /**
     * Sets tag last pushed field.
     *
     * @param string|null $value
     */
    public function tagLastPushed(?string $value): self
    {
        $this->instance->setTagLastPushed($value);
        return $this;
    }

    /**
     * Unsets tag last pushed field.
     */
    public function unsetTagLastPushed(): self
    {
        $this->instance->unsetTagLastPushed();
        return $this;
    }

    /**
     * Sets v 2 field.
     *
     * @param string|null $value
     */
    public function v2(?string $value): self
    {
        $this->instance->setV2($value);
        return $this;
    }

    /**
     * Initializes a new Tag object.
     */
    public function build(): Tag
    {
        return CoreHelper::clone($this->instance);
    }
}
