<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\ThrottleDevice;

/**
 * Builder for model ThrottleDevice
 *
 * @see ThrottleDevice
 */
class ThrottleDeviceBuilder
{
    /**
     * @var ThrottleDevice
     */
    private $instance;

    private function __construct(ThrottleDevice $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Throttle Device Builder object.
     */
    public static function init(): self
    {
        return new self(new ThrottleDevice());
    }

    /**
     * Sets Path field.
     *
     * @param string|null $value
     */
    public function path(?string $value): self
    {
        $this->instance->setPath($value);
        return $this;
    }

    /**
     * Sets Rate field.
     *
     * @param int|null $value
     */
    public function rate(?int $value): self
    {
        $this->instance->setRate($value);
        return $this;
    }

    /**
     * Initializes a new Throttle Device object.
     */
    public function build(): ThrottleDevice
    {
        return CoreHelper::clone($this->instance);
    }
}
