<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\AuditLog;
use DockerLib\Models\V2AuditlogsResponse;

/**
 * Builder for model V2AuditlogsResponse
 *
 * @see V2AuditlogsResponse
 */
class V2AuditlogsResponseBuilder
{
    /**
     * @var V2AuditlogsResponse
     */
    private $instance;

    private function __construct(V2AuditlogsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new V2 Auditlogs Response Builder object.
     */
    public static function init(): self
    {
        return new self(new V2AuditlogsResponse());
    }

    /**
     * Sets logs field.
     *
     * @param AuditLog[]|null $value
     */
    public function logs(?array $value): self
    {
        $this->instance->setLogs($value);
        return $this;
    }

    /**
     * Initializes a new V2 Auditlogs Response object.
     */
    public function build(): V2AuditlogsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
