<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Result;
use DockerLib\Models\V2NamespacesRepositoriesImagesResponse;

/**
 * Builder for model V2NamespacesRepositoriesImagesResponse
 *
 * @see V2NamespacesRepositoriesImagesResponse
 */
class V2NamespacesRepositoriesImagesResponseBuilder
{
    /**
     * @var V2NamespacesRepositoriesImagesResponse
     */
    private $instance;

    private function __construct(V2NamespacesRepositoriesImagesResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new V2 Namespaces Repositories Images Response Builder object.
     */
    public static function init(): self
    {
        return new self(new V2NamespacesRepositoriesImagesResponse());
    }

    /**
     * Sets count field.
     *
     * @param int|null $value
     */
    public function count(?int $value): self
    {
        $this->instance->setCount($value);
        return $this;
    }

    /**
     * Sets next field.
     *
     * @param string|null $value
     */
    public function next(?string $value): self
    {
        $this->instance->setNext($value);
        return $this;
    }

    /**
     * Unsets next field.
     */
    public function unsetNext(): self
    {
        $this->instance->unsetNext();
        return $this;
    }

    /**
     * Sets previous field.
     *
     * @param string|null $value
     */
    public function previous(?string $value): self
    {
        $this->instance->setPrevious($value);
        return $this;
    }

    /**
     * Unsets previous field.
     */
    public function unsetPrevious(): self
    {
        $this->instance->unsetPrevious();
        return $this;
    }

    /**
     * Sets results field.
     *
     * @param Result[]|null $value
     */
    public function results(?array $value): self
    {
        $this->instance->setResults($value);
        return $this;
    }

    /**
     * Initializes a new V2 Namespaces Repositories Images Response object.
     */
    public function build(): V2NamespacesRepositoriesImagesResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
