<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\V2Users2faLoginResponse;

/**
 * Builder for model V2Users2faLoginResponse
 *
 * @see V2Users2faLoginResponse
 */
class V2Users2faLoginResponseBuilder
{
    /**
     * @var V2Users2faLoginResponse
     */
    private $instance;

    private function __construct(V2Users2faLoginResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new V2 Users 2 fa Login Response Builder object.
     */
    public static function init(): self
    {
        return new self(new V2Users2faLoginResponse());
    }

    /**
     * Sets token field.
     *
     * @param string|null $value
     */
    public function token(?string $value): self
    {
        $this->instance->setToken($value);
        return $this;
    }

    /**
     * Initializes a new V2 Users 2 fa Login Response object.
     */
    public function build(): V2Users2faLoginResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
