<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\VersionResponse;

/**
 * Builder for model VersionResponse
 *
 * @see VersionResponse
 */
class VersionResponseBuilder
{
    /**
     * @var VersionResponse
     */
    private $instance;

    private function __construct(VersionResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Version Response Builder object.
     */
    public static function init(): self
    {
        return new self(new VersionResponse());
    }

    /**
     * Sets Api Version field.
     *
     * @param string|null $value
     */
    public function apiVersion(?string $value): self
    {
        $this->instance->setApiVersion($value);
        return $this;
    }

    /**
     * Sets Arch field.
     *
     * @param string|null $value
     */
    public function arch(?string $value): self
    {
        $this->instance->setArch($value);
        return $this;
    }

    /**
     * Sets Build Time field.
     *
     * @param string|null $value
     */
    public function buildTime(?string $value): self
    {
        $this->instance->setBuildTime($value);
        return $this;
    }

    /**
     * Sets Experimental field.
     *
     * @param bool|null $value
     */
    public function experimental(?bool $value): self
    {
        $this->instance->setExperimental($value);
        return $this;
    }

    /**
     * Sets Git Commit field.
     *
     * @param string|null $value
     */
    public function gitCommit(?string $value): self
    {
        $this->instance->setGitCommit($value);
        return $this;
    }

    /**
     * Sets Go Version field.
     *
     * @param string|null $value
     */
    public function goVersion(?string $value): self
    {
        $this->instance->setGoVersion($value);
        return $this;
    }

    /**
     * Sets Kernel Version field.
     *
     * @param string|null $value
     */
    public function kernelVersion(?string $value): self
    {
        $this->instance->setKernelVersion($value);
        return $this;
    }

    /**
     * Sets Min API Version field.
     *
     * @param string|null $value
     */
    public function minAPIVersion(?string $value): self
    {
        $this->instance->setMinAPIVersion($value);
        return $this;
    }

    /**
     * Sets Os field.
     *
     * @param string|null $value
     */
    public function os(?string $value): self
    {
        $this->instance->setOs($value);
        return $this;
    }

    /**
     * Sets Version field.
     *
     * @param string|null $value
     */
    public function version(?string $value): self
    {
        $this->instance->setVersion($value);
        return $this;
    }

    /**
     * Initializes a new Version Response object.
     */
    public function build(): VersionResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
