<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\DriverConfig2;
use DockerLib\Models\VolumeOptions2;

/**
 * Builder for model VolumeOptions2
 *
 * @see VolumeOptions2
 */
class VolumeOptions2Builder
{
    /**
     * @var VolumeOptions2
     */
    private $instance;

    private function __construct(VolumeOptions2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Volume Options 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new VolumeOptions2());
    }

    /**
     * Sets Driver Config field.
     *
     * @param DriverConfig2|null $value
     */
    public function driverConfig(?DriverConfig2 $value): self
    {
        $this->instance->setDriverConfig($value);
        return $this;
    }

    /**
     * Sets Labels field.
     *
     * @param array<string,string>|null $value
     */
    public function labels(?array $value): self
    {
        $this->instance->setLabels($value);
        return $this;
    }

    /**
     * Sets No Copy field.
     *
     * @param bool|null $value
     */
    public function noCopy(?bool $value): self
    {
        $this->instance->setNoCopy($value);
        return $this;
    }

    /**
     * Initializes a new Volume Options 2 object.
     */
    public function build(): VolumeOptions2
    {
        return CoreHelper::clone($this->instance);
    }
}
