<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\VolumesCreateRequest;

/**
 * Builder for model VolumesCreateRequest
 *
 * @see VolumesCreateRequest
 */
class VolumesCreateRequestBuilder
{
    /**
     * @var VolumesCreateRequest
     */
    private $instance;

    private function __construct(VolumesCreateRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Volumes Create Request Builder object.
     */
    public static function init(): self
    {
        return new self(new VolumesCreateRequest());
    }

    /**
     * Sets Driver field.
     *
     * @param string|null $value
     */
    public function driver(?string $value): self
    {
        $this->instance->setDriver($value);
        return $this;
    }

    /**
     * Sets Driver Opts field.
     *
     * @param array<string,string>|null $value
     */
    public function driverOpts(?array $value): self
    {
        $this->instance->setDriverOpts($value);
        return $this;
    }

    /**
     * Sets Labels field.
     *
     * @param array<string,string>|null $value
     */
    public function labels(?array $value): self
    {
        $this->instance->setLabels($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new Volumes Create Request object.
     */
    public function build(): VolumesCreateRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
