<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models\Builders;

use Core\Utils\CoreHelper;
use DockerLib\Models\Warning1;

/**
 * Builder for model Warning1
 *
 * @see Warning1
 */
class Warning1Builder
{
    /**
     * @var Warning1
     */
    private $instance;

    private function __construct(Warning1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Warning 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Warning1());
    }

    /**
     * Sets digest field.
     *
     * @param string|null $value
     */
    public function digest(?string $value): self
    {
        $this->instance->setDigest($value);
        return $this;
    }

    /**
     * Sets repository field.
     *
     * @param string|null $value
     */
    public function repository(?string $value): self
    {
        $this->instance->setRepository($value);
        return $this;
    }

    /**
     * Sets tags field.
     *
     * @param string[]|null $value
     */
    public function tags(?array $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Sets warning field.
     *
     * @param string|null $value
     */
    public function warning(?string $value): self
    {
        $this->instance->setWarning($value);
        return $this;
    }

    /**
     * Initializes a new Warning 1 object.
     */
    public function build(): Warning1
    {
        return CoreHelper::clone($this->instance);
    }
}
