<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Exceptions;

use DockerLib\ApiHelper;

class ErrorException extends ApiException
{
    /**
     * @var string|null
     */
    private $detail;

    /**
     * @var string|null
     */
    private $messageProperty;

    /**
     * Returns Detail.
     */
    public function getDetail(): ?string
    {
        return $this->detail;
    }

    /**
     * Sets Detail.
     *
     * @maps detail
     */
    public function setDetail(?string $detail): void
    {
        $this->detail = $detail;
    }

    /**
     * Returns Message Property.
     */
    public function getMessageProperty(): ?string
    {
        return $this->messageProperty;
    }

    /**
     * Sets Message Property.
     *
     * @maps message
     */
    public function setMessageProperty(?string $messageProperty): void
    {
        $this->messageProperty = $messageProperty;
    }

    /**
     * Converts the ErrorException object to a human-readable string representation.
     *
     * @return string The string representation of the ErrorException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ErrorException',
            ['detail' => $this->detail, 'messageProperty' => $this->messageProperty],
            parent::__toString()
        );
    }
}
