<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Exceptions;

use DockerLib\ApiHelper;

class ScimErrorException extends ApiException
{
    /**
     * @var string|null
     */
    private $detail;

    /**
     * @var string[]|null
     */
    private $schemas;

    /**
     * @var string|null
     */
    private $status;

    /**
     * Returns Detail.
     * Details about why the request failed.
     */
    public function getDetail(): ?string
    {
        return $this->detail;
    }

    /**
     * Sets Detail.
     * Details about why the request failed.
     *
     * @maps detail
     */
    public function setDetail(?string $detail): void
    {
        $this->detail = $detail;
    }

    /**
     * Returns Schemas.
     *
     * @return string[]|null
     */
    public function getSchemas(): ?array
    {
        return $this->schemas;
    }

    /**
     * Sets Schemas.
     *
     * @maps schemas
     *
     * @param string[]|null $schemas
     */
    public function setSchemas(?array $schemas): void
    {
        $this->schemas = $schemas;
    }

    /**
     * Returns Status.
     * The status code for the response in string format.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status code for the response in string format.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Converts the ScimErrorException object to a human-readable string representation.
     *
     * @return string The string representation of the ScimErrorException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ScimErrorException',
            ['detail' => $this->detail, 'schemas' => $this->schemas, 'status' => $this->status],
            parent::__toString()
        );
    }
}
