<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Exceptions;

use DockerLib\ApiHelper;

class V2NamespacesDeleteImages403ErrorException extends ApiException
{
    /**
     * @var \DockerLib\Models\Errinfo2|null
     */
    private $errinfo;

    /**
     * @var string|null
     */
    private $messageProperty;

    /**
     * @var string|null
     */
    private $txnid;

    /**
     * Returns Errinfo.
     */
    public function getErrinfo(): ?\DockerLib\Models\Errinfo2
    {
        return $this->errinfo;
    }

    /**
     * Sets Errinfo.
     *
     * @maps errinfo
     */
    public function setErrinfo(?\DockerLib\Models\Errinfo2 $errinfo): void
    {
        $this->errinfo = $errinfo;
    }

    /**
     * Returns Message Property.
     * The error message.
     */
    public function getMessageProperty(): ?string
    {
        return $this->messageProperty;
    }

    /**
     * Sets Message Property.
     * The error message.
     *
     * @maps message
     */
    public function setMessageProperty(?string $messageProperty): void
    {
        $this->messageProperty = $messageProperty;
    }

    /**
     * Returns Txnid.
     * Unique ID for this call.
     */
    public function getTxnid(): ?string
    {
        return $this->txnid;
    }

    /**
     * Sets Txnid.
     * Unique ID for this call.
     *
     * @maps txnid
     */
    public function setTxnid(?string $txnid): void
    {
        $this->txnid = $txnid;
    }

    /**
     * Converts the V2NamespacesDeleteImages403ErrorException object to a human-readable string
     * representation.
     *
     * @return string The string representation of the V2NamespacesDeleteImages403ErrorException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'V2NamespacesDeleteImages403ErrorException',
            ['errinfo' => $this->errinfo, 'messageProperty' => $this->messageProperty, 'txnid' => $this->txnid],
            parent::__toString()
        );
    }
}
