<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Exceptions;

use DockerLib\ApiHelper;

class V2UsersLogin401ErrorException extends ApiException
{
    /**
     * @var string
     */
    private $detail;

    /**
     * @var array
     */
    private $login2faToken = [];

    /**
     * @param string $reason
     * @param \DockerLib\Http\HttpRequest $request
     * @param \DockerLib\Http\HttpResponse $response
     * @param string $detail
     */
    public function __construct(
        string $reason,
        \DockerLib\Http\HttpRequest $request,
        \DockerLib\Http\HttpResponse $response,
        string $detail
    ) {
        parent::__construct($reason, $request, $response);
        $this->detail = $detail;
    }

    /**
     * Returns Detail.
     * Description of the error.
     */
    public function getDetail(): string
    {
        return $this->detail;
    }

    /**
     * Sets Detail.
     * Description of the error.
     *
     * @required
     * @maps detail
     */
    public function setDetail(string $detail): void
    {
        $this->detail = $detail;
    }

    /**
     * Returns Login 2 Fa Token.
     * Short time lived token to be used on `/v2/users/2fa-login` to complete the authentication. This
     * field is present only if 2FA is enabled.
     */
    public function getLogin2faToken(): ?string
    {
        if (count($this->login2faToken) == 0) {
            return null;
        }
        return $this->login2faToken['value'];
    }

    /**
     * Sets Login 2 Fa Token.
     * Short time lived token to be used on `/v2/users/2fa-login` to complete the authentication. This
     * field is present only if 2FA is enabled.
     *
     * @maps login_2fa_token
     */
    public function setLogin2faToken(?string $login2faToken): void
    {
        $this->login2faToken['value'] = $login2faToken;
    }

    /**
     * Unsets Login 2 Fa Token.
     * Short time lived token to be used on `/v2/users/2fa-login` to complete the authentication. This
     * field is present only if 2FA is enabled.
     */
    public function unsetLogin2faToken(): void
    {
        $this->login2faToken = [];
    }

    /**
     * Converts the V2UsersLogin401ErrorException object to a human-readable string representation.
     *
     * @return string The string representation of the V2UsersLogin401ErrorException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'V2UsersLogin401ErrorException',
            ['detail' => $this->detail, 'login2faToken' => $this->getLogin2faToken()],
            parent::__toString()
        );
    }
}
