<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Actor implements \JsonSerializable
{
    /**
     * @var array<string,string>|null
     */
    private $attributes;

    /**
     * @var string|null
     */
    private $iD;

    /**
     * Returns Attributes.
     * Various key/value attributes of the object, depending on its type
     *
     * @return array<string,string>|null
     */
    public function getAttributes(): ?array
    {
        return $this->attributes;
    }

    /**
     * Sets Attributes.
     * Various key/value attributes of the object, depending on its type
     *
     * @maps Attributes
     *
     * @param array<string,string>|null $attributes
     */
    public function setAttributes(?array $attributes): void
    {
        $this->attributes = $attributes;
    }

    /**
     * Returns I D.
     * The ID of the object emitting the event
     */
    public function getID(): ?string
    {
        return $this->iD;
    }

    /**
     * Sets I D.
     * The ID of the object emitting the event
     *
     * @maps ID
     */
    public function setID(?string $iD): void
    {
        $this->iD = $iD;
    }

    /**
     * Converts the Actor object to a human-readable string representation.
     *
     * @return string The string representation of the Actor object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Actor', ['attributes' => $this->attributes, 'iD' => $this->iD]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->attributes)) {
            $json['Attributes'] = $this->attributes;
        }
        if (isset($this->iD)) {
            $json['ID']         = $this->iD;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
