<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Args implements \JsonSerializable
{
    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string[]
     */
    private $settable;

    /**
     * @var string[]
     */
    private $value;

    /**
     * @param string $description
     * @param string $name
     * @param string[] $settable
     * @param string[] $value
     */
    public function __construct(string $description, string $name, array $settable, array $value)
    {
        $this->description = $description;
        $this->name = $name;
        $this->settable = $settable;
        $this->value = $value;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @required
     * @maps Description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps Name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Settable.
     *
     * @return string[]
     */
    public function getSettable(): array
    {
        return $this->settable;
    }

    /**
     * Sets Settable.
     *
     * @required
     * @maps Settable
     *
     * @param string[] $settable
     */
    public function setSettable(array $settable): void
    {
        $this->settable = $settable;
    }

    /**
     * Returns Value.
     *
     * @return string[]
     */
    public function getValue(): array
    {
        return $this->value;
    }

    /**
     * Sets Value.
     *
     * @required
     * @maps Value
     *
     * @param string[] $value
     */
    public function setValue(array $value): void
    {
        $this->value = $value;
    }

    /**
     * Converts the Args object to a human-readable string representation.
     *
     * @return string The string representation of the Args object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Args',
            [
                'description' => $this->description,
                'name' => $this->name,
                'settable' => $this->settable,
                'value' => $this->value
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Description'] = $this->description;
        $json['Name']        = $this->name;
        $json['Settable']    = $this->settable;
        $json['Value']       = $this->value;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
