<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class AuthResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $identityToken;

    /**
     * @var string
     */
    private $status;

    /**
     * @param string $status
     */
    public function __construct(string $status)
    {
        $this->status = $status;
    }

    /**
     * Returns Identity Token.
     * An opaque token used to authenticate a user after a successful login
     */
    public function getIdentityToken(): ?string
    {
        return $this->identityToken;
    }

    /**
     * Sets Identity Token.
     * An opaque token used to authenticate a user after a successful login
     *
     * @maps IdentityToken
     */
    public function setIdentityToken(?string $identityToken): void
    {
        $this->identityToken = $identityToken;
    }

    /**
     * Returns Status.
     * The status of the authentication
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of the authentication
     *
     * @required
     * @maps Status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Converts the AuthResponse object to a human-readable string representation.
     *
     * @return string The string representation of the AuthResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AuthResponse',
            ['identityToken' => $this->identityToken, 'status' => $this->status]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->identityToken)) {
            $json['IdentityToken'] = $this->identityToken;
        }
        $json['Status']            = $this->status;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
