<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class AuthenticationSchemes implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $specUri;

    /**
     * @var string|null
     */
    private $type;

    /**
     * Returns Description.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Spec Uri.
     */
    public function getSpecUri(): ?string
    {
        return $this->specUri;
    }

    /**
     * Sets Spec Uri.
     *
     * @maps specUri
     */
    public function setSpecUri(?string $specUri): void
    {
        $this->specUri = $specUri;
    }

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the AuthenticationSchemes object to a human-readable string representation.
     *
     * @return string The string representation of the AuthenticationSchemes object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AuthenticationSchemes',
            [
                'description' => $this->description,
                'name' => $this->name,
                'specUri' => $this->specUri,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->description)) {
            $json['description'] = $this->description;
        }
        if (isset($this->name)) {
            $json['name']        = $this->name;
        }
        if (isset($this->specUri)) {
            $json['specUri']     = $this->specUri;
        }
        if (isset($this->type)) {
            $json['type']        = $this->type;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
