<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class BuildInfo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $error;

    /**
     * @var ErrorDetail|null
     */
    private $errorDetail;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $progress;

    /**
     * @var ProgressDetail|null
     */
    private $progressDetail;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $stream;

    /**
     * Returns Error.
     */
    public function getError(): ?string
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps error
     */
    public function setError(?string $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Error Detail.
     */
    public function getErrorDetail(): ?ErrorDetail
    {
        return $this->errorDetail;
    }

    /**
     * Sets Error Detail.
     *
     * @maps errorDetail
     */
    public function setErrorDetail(?ErrorDetail $errorDetail): void
    {
        $this->errorDetail = $errorDetail;
    }

    /**
     * Returns Id.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Progress.
     */
    public function getProgress(): ?string
    {
        return $this->progress;
    }

    /**
     * Sets Progress.
     *
     * @maps progress
     */
    public function setProgress(?string $progress): void
    {
        $this->progress = $progress;
    }

    /**
     * Returns Progress Detail.
     */
    public function getProgressDetail(): ?ProgressDetail
    {
        return $this->progressDetail;
    }

    /**
     * Sets Progress Detail.
     *
     * @maps progressDetail
     */
    public function setProgressDetail(?ProgressDetail $progressDetail): void
    {
        $this->progressDetail = $progressDetail;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Stream.
     */
    public function getStream(): ?string
    {
        return $this->stream;
    }

    /**
     * Sets Stream.
     *
     * @maps stream
     */
    public function setStream(?string $stream): void
    {
        $this->stream = $stream;
    }

    /**
     * Converts the BuildInfo object to a human-readable string representation.
     *
     * @return string The string representation of the BuildInfo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BuildInfo',
            [
                'error' => $this->error,
                'errorDetail' => $this->errorDetail,
                'id' => $this->id,
                'progress' => $this->progress,
                'progressDetail' => $this->progressDetail,
                'status' => $this->status,
                'stream' => $this->stream
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->error)) {
            $json['error']          = $this->error;
        }
        if (isset($this->errorDetail)) {
            $json['errorDetail']    = $this->errorDetail;
        }
        if (isset($this->id)) {
            $json['id']             = $this->id;
        }
        if (isset($this->progress)) {
            $json['progress']       = $this->progress;
        }
        if (isset($this->progressDetail)) {
            $json['progressDetail'] = $this->progressDetail;
        }
        if (isset($this->status)) {
            $json['status']         = $this->status;
        }
        if (isset($this->stream)) {
            $json['stream']         = $this->stream;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
