<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class BuildPruneResponse implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $spaceReclaimed;

    /**
     * Returns Space Reclaimed.
     * Disk space reclaimed in bytes
     */
    public function getSpaceReclaimed(): ?int
    {
        return $this->spaceReclaimed;
    }

    /**
     * Sets Space Reclaimed.
     * Disk space reclaimed in bytes
     *
     * @maps SpaceReclaimed
     */
    public function setSpaceReclaimed(?int $spaceReclaimed): void
    {
        $this->spaceReclaimed = $spaceReclaimed;
    }

    /**
     * Converts the BuildPruneResponse object to a human-readable string representation.
     *
     * @return string The string representation of the BuildPruneResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('BuildPruneResponse', ['spaceReclaimed' => $this->spaceReclaimed]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->spaceReclaimed)) {
            $json['SpaceReclaimed'] = $this->spaceReclaimed;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
