<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ConfigSpec implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $data;

    /**
     * @var array<string,string>|null
     */
    private $labels;

    /**
     * @var string|null
     */
    private $name;

    /**
     * Returns Data.
     * Base64-url-safe-encoded ([RFC 4648](https://tools.ietf.org/html/rfc4648#section-3.2))
     * config data.
     */
    public function getData(): ?string
    {
        return $this->data;
    }

    /**
     * Sets Data.
     * Base64-url-safe-encoded ([RFC 4648](https://tools.ietf.org/html/rfc4648#section-3.2))
     * config data.
     *
     * @maps Data
     */
    public function setData(?string $data): void
    {
        $this->data = $data;
    }

    /**
     * Returns Labels.
     * User-defined key/value metadata.
     *
     * @return array<string,string>|null
     */
    public function getLabels(): ?array
    {
        return $this->labels;
    }

    /**
     * Sets Labels.
     * User-defined key/value metadata.
     *
     * @maps Labels
     *
     * @param array<string,string>|null $labels
     */
    public function setLabels(?array $labels): void
    {
        $this->labels = $labels;
    }

    /**
     * Returns Name.
     * User-defined name of the config.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * User-defined name of the config.
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Converts the ConfigSpec object to a human-readable string representation.
     *
     * @return string The string representation of the ConfigSpec object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ConfigSpec',
            ['data' => $this->data, 'labels' => $this->labels, 'name' => $this->name]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->data)) {
            $json['Data']   = $this->data;
        }
        if (isset($this->labels)) {
            $json['Labels'] = $this->labels;
        }
        if (isset($this->name)) {
            $json['Name']   = $this->name;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
