<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ContainerdCommit implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $expected;

    /**
     * @var string|null
     */
    private $iD;

    /**
     * Returns Expected.
     * Commit ID of external tool expected by dockerd as set at build time.
     */
    public function getExpected(): ?string
    {
        return $this->expected;
    }

    /**
     * Sets Expected.
     * Commit ID of external tool expected by dockerd as set at build time.
     *
     * @maps Expected
     */
    public function setExpected(?string $expected): void
    {
        $this->expected = $expected;
    }

    /**
     * Returns I D.
     * Actual commit ID of external tool.
     */
    public function getID(): ?string
    {
        return $this->iD;
    }

    /**
     * Sets I D.
     * Actual commit ID of external tool.
     *
     * @maps ID
     */
    public function setID(?string $iD): void
    {
        $this->iD = $iD;
    }

    /**
     * Converts the ContainerdCommit object to a human-readable string representation.
     *
     * @return string The string representation of the ContainerdCommit object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ContainerdCommit', ['expected' => $this->expected, 'iD' => $this->iD]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->expected)) {
            $json['Expected'] = $this->expected;
        }
        if (isset($this->iD)) {
            $json['ID']       = $this->iD;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
