<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * Invalid when specified with `PluginSpec`.
 */
class ContainerSpec implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $args;

    /**
     * @var string[]|null
     */
    private $command;

    /**
     * @var Config2[]|null
     */
    private $configs;

    /**
     * @var DNSConfig2|null
     */
    private $dNSConfig;

    /**
     * @var string|null
     */
    private $dir;

    /**
     * @var string[]|null
     */
    private $env;

    /**
     * @var string[]|null
     */
    private $groups;

    /**
     * @var Healthcheck|null
     */
    private $healthCheck;

    /**
     * @var string|null
     */
    private $hostname;

    /**
     * @var string[]|null
     */
    private $hosts;

    /**
     * @var string|null
     */
    private $image;

    /**
     * @var array<string,string>|null
     */
    private $labels;

    /**
     * @var Mount[]|null
     */
    private $mounts;

    /**
     * @var bool|null
     */
    private $openStdin;

    /**
     * @var Privileges2|null
     */
    private $privileges;

    /**
     * @var bool|null
     */
    private $readOnly;

    /**
     * @var Secret1[]|null
     */
    private $secrets;

    /**
     * @var int|null
     */
    private $stopGracePeriod;

    /**
     * @var string|null
     */
    private $stopSignal;

    /**
     * @var bool|null
     */
    private $tTY;

    /**
     * @var string|null
     */
    private $user;

    /**
     * Returns Args.
     * Arguments to the command.
     *
     * @return string[]|null
     */
    public function getArgs(): ?array
    {
        return $this->args;
    }

    /**
     * Sets Args.
     * Arguments to the command.
     *
     * @maps Args
     *
     * @param string[]|null $args
     */
    public function setArgs(?array $args): void
    {
        $this->args = $args;
    }

    /**
     * Returns Command.
     * The command to be run in the image.
     *
     * @return string[]|null
     */
    public function getCommand(): ?array
    {
        return $this->command;
    }

    /**
     * Sets Command.
     * The command to be run in the image.
     *
     * @maps Command
     *
     * @param string[]|null $command
     */
    public function setCommand(?array $command): void
    {
        $this->command = $command;
    }

    /**
     * Returns Configs.
     * Configs contains references to zero or more configs that will be exposed to the service.
     *
     * @return Config2[]|null
     */
    public function getConfigs(): ?array
    {
        return $this->configs;
    }

    /**
     * Sets Configs.
     * Configs contains references to zero or more configs that will be exposed to the service.
     *
     * @maps Configs
     *
     * @param Config2[]|null $configs
     */
    public function setConfigs(?array $configs): void
    {
        $this->configs = $configs;
    }

    /**
     * Returns D NS Config.
     */
    public function getDNSConfig(): ?DNSConfig2
    {
        return $this->dNSConfig;
    }

    /**
     * Sets D NS Config.
     *
     * @maps DNSConfig
     */
    public function setDNSConfig(?DNSConfig2 $dNSConfig): void
    {
        $this->dNSConfig = $dNSConfig;
    }

    /**
     * Returns Dir.
     * The working directory for commands to run in.
     */
    public function getDir(): ?string
    {
        return $this->dir;
    }

    /**
     * Sets Dir.
     * The working directory for commands to run in.
     *
     * @maps Dir
     */
    public function setDir(?string $dir): void
    {
        $this->dir = $dir;
    }

    /**
     * Returns Env.
     * A list of environment variables in the form `VAR=value`.
     *
     * @return string[]|null
     */
    public function getEnv(): ?array
    {
        return $this->env;
    }

    /**
     * Sets Env.
     * A list of environment variables in the form `VAR=value`.
     *
     * @maps Env
     *
     * @param string[]|null $env
     */
    public function setEnv(?array $env): void
    {
        $this->env = $env;
    }

    /**
     * Returns Groups.
     * A list of additional groups that the container process will run as.
     *
     * @return string[]|null
     */
    public function getGroups(): ?array
    {
        return $this->groups;
    }

    /**
     * Sets Groups.
     * A list of additional groups that the container process will run as.
     *
     * @maps Groups
     *
     * @param string[]|null $groups
     */
    public function setGroups(?array $groups): void
    {
        $this->groups = $groups;
    }

    /**
     * Returns Health Check.
     */
    public function getHealthCheck(): ?Healthcheck
    {
        return $this->healthCheck;
    }

    /**
     * Sets Health Check.
     *
     * @maps HealthCheck
     */
    public function setHealthCheck(?Healthcheck $healthCheck): void
    {
        $this->healthCheck = $healthCheck;
    }

    /**
     * Returns Hostname.
     * The hostname to use for the container, as a valid RFC 1123 hostname.
     */
    public function getHostname(): ?string
    {
        return $this->hostname;
    }

    /**
     * Sets Hostname.
     * The hostname to use for the container, as a valid RFC 1123 hostname.
     *
     * @maps Hostname
     */
    public function setHostname(?string $hostname): void
    {
        $this->hostname = $hostname;
    }

    /**
     * Returns Hosts.
     * A list of hostname/IP mappings to add to the container's `hosts`
     * file. The format of extra hosts is specified in the
     * [hosts(5)](http://man7.org/linux/man-pages/man5/hosts.5.html)
     * man page:
     *
     * IP_address canonical_hostname [aliases...]
     *
     * @return string[]|null
     */
    public function getHosts(): ?array
    {
        return $this->hosts;
    }

    /**
     * Sets Hosts.
     * A list of hostname/IP mappings to add to the container's `hosts`
     * file. The format of extra hosts is specified in the
     * [hosts(5)](http://man7.org/linux/man-pages/man5/hosts.5.html)
     * man page:
     *
     * IP_address canonical_hostname [aliases...]
     *
     * @maps Hosts
     *
     * @param string[]|null $hosts
     */
    public function setHosts(?array $hosts): void
    {
        $this->hosts = $hosts;
    }

    /**
     * Returns Image.
     * The image name to use for the container
     */
    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * Sets Image.
     * The image name to use for the container
     *
     * @maps Image
     */
    public function setImage(?string $image): void
    {
        $this->image = $image;
    }

    /**
     * Returns Labels.
     * User-defined key/value data.
     *
     * @return array<string,string>|null
     */
    public function getLabels(): ?array
    {
        return $this->labels;
    }

    /**
     * Sets Labels.
     * User-defined key/value data.
     *
     * @maps Labels
     *
     * @param array<string,string>|null $labels
     */
    public function setLabels(?array $labels): void
    {
        $this->labels = $labels;
    }

    /**
     * Returns Mounts.
     * Specification for mounts to be added to containers created as part of the service.
     *
     * @return Mount[]|null
     */
    public function getMounts(): ?array
    {
        return $this->mounts;
    }

    /**
     * Sets Mounts.
     * Specification for mounts to be added to containers created as part of the service.
     *
     * @maps Mounts
     *
     * @param Mount[]|null $mounts
     */
    public function setMounts(?array $mounts): void
    {
        $this->mounts = $mounts;
    }

    /**
     * Returns Open Stdin.
     * Open `stdin`
     */
    public function getOpenStdin(): ?bool
    {
        return $this->openStdin;
    }

    /**
     * Sets Open Stdin.
     * Open `stdin`
     *
     * @maps OpenStdin
     */
    public function setOpenStdin(?bool $openStdin): void
    {
        $this->openStdin = $openStdin;
    }

    /**
     * Returns Privileges.
     */
    public function getPrivileges(): ?Privileges2
    {
        return $this->privileges;
    }

    /**
     * Sets Privileges.
     *
     * @maps Privileges
     */
    public function setPrivileges(?Privileges2 $privileges): void
    {
        $this->privileges = $privileges;
    }

    /**
     * Returns Read Only.
     * Mount the container's root filesystem as read only.
     */
    public function getReadOnly(): ?bool
    {
        return $this->readOnly;
    }

    /**
     * Sets Read Only.
     * Mount the container's root filesystem as read only.
     *
     * @maps ReadOnly
     */
    public function setReadOnly(?bool $readOnly): void
    {
        $this->readOnly = $readOnly;
    }

    /**
     * Returns Secrets.
     * Secrets contains references to zero or more secrets that will be exposed to the service.
     *
     * @return Secret1[]|null
     */
    public function getSecrets(): ?array
    {
        return $this->secrets;
    }

    /**
     * Sets Secrets.
     * Secrets contains references to zero or more secrets that will be exposed to the service.
     *
     * @maps Secrets
     *
     * @param Secret1[]|null $secrets
     */
    public function setSecrets(?array $secrets): void
    {
        $this->secrets = $secrets;
    }

    /**
     * Returns Stop Grace Period.
     * Amount of time to wait for the container to terminate before forcefully killing it.
     */
    public function getStopGracePeriod(): ?int
    {
        return $this->stopGracePeriod;
    }

    /**
     * Sets Stop Grace Period.
     * Amount of time to wait for the container to terminate before forcefully killing it.
     *
     * @maps StopGracePeriod
     */
    public function setStopGracePeriod(?int $stopGracePeriod): void
    {
        $this->stopGracePeriod = $stopGracePeriod;
    }

    /**
     * Returns Stop Signal.
     * Signal to stop the container.
     */
    public function getStopSignal(): ?string
    {
        return $this->stopSignal;
    }

    /**
     * Sets Stop Signal.
     * Signal to stop the container.
     *
     * @maps StopSignal
     */
    public function setStopSignal(?string $stopSignal): void
    {
        $this->stopSignal = $stopSignal;
    }

    /**
     * Returns T TY.
     * Whether a pseudo-TTY should be allocated.
     */
    public function getTTY(): ?bool
    {
        return $this->tTY;
    }

    /**
     * Sets T TY.
     * Whether a pseudo-TTY should be allocated.
     *
     * @maps TTY
     */
    public function setTTY(?bool $tTY): void
    {
        $this->tTY = $tTY;
    }

    /**
     * Returns User.
     * The user inside the container.
     */
    public function getUser(): ?string
    {
        return $this->user;
    }

    /**
     * Sets User.
     * The user inside the container.
     *
     * @maps User
     */
    public function setUser(?string $user): void
    {
        $this->user = $user;
    }

    /**
     * Converts the ContainerSpec object to a human-readable string representation.
     *
     * @return string The string representation of the ContainerSpec object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ContainerSpec',
            [
                'args' => $this->args,
                'command' => $this->command,
                'configs' => $this->configs,
                'dNSConfig' => $this->dNSConfig,
                'dir' => $this->dir,
                'env' => $this->env,
                'groups' => $this->groups,
                'healthCheck' => $this->healthCheck,
                'hostname' => $this->hostname,
                'hosts' => $this->hosts,
                'image' => $this->image,
                'labels' => $this->labels,
                'mounts' => $this->mounts,
                'openStdin' => $this->openStdin,
                'privileges' => $this->privileges,
                'readOnly' => $this->readOnly,
                'secrets' => $this->secrets,
                'stopGracePeriod' => $this->stopGracePeriod,
                'stopSignal' => $this->stopSignal,
                'tTY' => $this->tTY,
                'user' => $this->user
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->args)) {
            $json['Args']            = $this->args;
        }
        if (isset($this->command)) {
            $json['Command']         = $this->command;
        }
        if (isset($this->configs)) {
            $json['Configs']         = $this->configs;
        }
        if (isset($this->dNSConfig)) {
            $json['DNSConfig']       = $this->dNSConfig;
        }
        if (isset($this->dir)) {
            $json['Dir']             = $this->dir;
        }
        if (isset($this->env)) {
            $json['Env']             = $this->env;
        }
        if (isset($this->groups)) {
            $json['Groups']          = $this->groups;
        }
        if (isset($this->healthCheck)) {
            $json['HealthCheck']     = $this->healthCheck;
        }
        if (isset($this->hostname)) {
            $json['Hostname']        = $this->hostname;
        }
        if (isset($this->hosts)) {
            $json['Hosts']           = $this->hosts;
        }
        if (isset($this->image)) {
            $json['Image']           = $this->image;
        }
        if (isset($this->labels)) {
            $json['Labels']          = $this->labels;
        }
        if (isset($this->mounts)) {
            $json['Mounts']          = $this->mounts;
        }
        if (isset($this->openStdin)) {
            $json['OpenStdin']       = $this->openStdin;
        }
        if (isset($this->privileges)) {
            $json['Privileges']      = $this->privileges;
        }
        if (isset($this->readOnly)) {
            $json['ReadOnly']        = $this->readOnly;
        }
        if (isset($this->secrets)) {
            $json['Secrets']         = $this->secrets;
        }
        if (isset($this->stopGracePeriod)) {
            $json['StopGracePeriod'] = $this->stopGracePeriod;
        }
        if (isset($this->stopSignal)) {
            $json['StopSignal']      = $this->stopSignal;
        }
        if (isset($this->tTY)) {
            $json['TTY']             = $this->tTY;
        }
        if (isset($this->user)) {
            $json['User']            = $this->user;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
