<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ContainerStatus implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $containerID;

    /**
     * @var int|null
     */
    private $exitCode;

    /**
     * @var int|null
     */
    private $pID;

    /**
     * Returns Container ID.
     */
    public function getContainerID(): ?string
    {
        return $this->containerID;
    }

    /**
     * Sets Container ID.
     *
     * @maps ContainerID
     */
    public function setContainerID(?string $containerID): void
    {
        $this->containerID = $containerID;
    }

    /**
     * Returns Exit Code.
     */
    public function getExitCode(): ?int
    {
        return $this->exitCode;
    }

    /**
     * Sets Exit Code.
     *
     * @maps ExitCode
     */
    public function setExitCode(?int $exitCode): void
    {
        $this->exitCode = $exitCode;
    }

    /**
     * Returns P ID.
     */
    public function getPID(): ?int
    {
        return $this->pID;
    }

    /**
     * Sets P ID.
     *
     * @maps PID
     */
    public function setPID(?int $pID): void
    {
        $this->pID = $pID;
    }

    /**
     * Converts the ContainerStatus object to a human-readable string representation.
     *
     * @return string The string representation of the ContainerStatus object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ContainerStatus',
            ['containerID' => $this->containerID, 'exitCode' => $this->exitCode, 'pID' => $this->pID]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->containerID)) {
            $json['ContainerID'] = $this->containerID;
        }
        if (isset($this->exitCode)) {
            $json['ExitCode']    = $this->exitCode;
        }
        if (isset($this->pID)) {
            $json['PID']         = $this->pID;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
