<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ContainersCreateResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string[]
     */
    private $warnings;

    /**
     * @param string $id
     * @param string[] $warnings
     */
    public function __construct(string $id, array $warnings)
    {
        $this->id = $id;
        $this->warnings = $warnings;
    }

    /**
     * Returns Id.
     * The ID of the created container
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The ID of the created container
     *
     * @required
     * @maps Id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Warnings.
     * Warnings encountered when creating the container
     *
     * @return string[]
     */
    public function getWarnings(): array
    {
        return $this->warnings;
    }

    /**
     * Sets Warnings.
     * Warnings encountered when creating the container
     *
     * @required
     * @maps Warnings
     *
     * @param string[] $warnings
     */
    public function setWarnings(array $warnings): void
    {
        $this->warnings = $warnings;
    }

    /**
     * Converts the ContainersCreateResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ContainersCreateResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ContainersCreateResponse', ['id' => $this->id, 'warnings' => $this->warnings]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Id']       = $this->id;
        $json['Warnings'] = $this->warnings;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
