<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ContainersExecResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $id;

    /**
     * @param string $id
     */
    public function __construct(string $id)
    {
        $this->id = $id;
    }

    /**
     * Returns Id.
     * The id of the newly created object.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The id of the newly created object.
     *
     * @required
     * @maps Id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Converts the ContainersExecResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ContainersExecResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ContainersExecResponse', ['id' => $this->id]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Id'] = $this->id;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
