<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ContainersChangesResponse implements \JsonSerializable
{
    /**
     * @var int
     */
    private $kind;

    /**
     * @var string
     */
    private $path;

    /**
     * @param int $kind
     * @param string $path
     */
    public function __construct(int $kind, string $path)
    {
        $this->kind = $kind;
        $this->path = $path;
    }

    /**
     * Returns Kind.
     */
    public function getKind(): int
    {
        return $this->kind;
    }

    /**
     * Sets Kind.
     *
     * @required
     * @maps Kind
     * @factory \DockerLib\Models\KindEnum::checkValue
     */
    public function setKind(int $kind): void
    {
        $this->kind = $kind;
    }

    /**
     * Returns Path.
     * Path to file that has changed
     */
    public function getPath(): string
    {
        return $this->path;
    }

    /**
     * Sets Path.
     * Path to file that has changed
     *
     * @required
     * @maps Path
     */
    public function setPath(string $path): void
    {
        $this->path = $path;
    }

    /**
     * Converts the ContainersChangesResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ContainersChangesResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ContainersChangesResponse', ['kind' => $this->kind, 'path' => $this->path]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Kind'] = KindEnum::checkValue($this->kind);
        $json['Path'] = $this->path;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
