<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class CreateImageInfo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $error;

    /**
     * @var string|null
     */
    private $progress;

    /**
     * @var ProgressDetail|null
     */
    private $progressDetail;

    /**
     * @var string|null
     */
    private $status;

    /**
     * Returns Error.
     */
    public function getError(): ?string
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps error
     */
    public function setError(?string $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Progress.
     */
    public function getProgress(): ?string
    {
        return $this->progress;
    }

    /**
     * Sets Progress.
     *
     * @maps progress
     */
    public function setProgress(?string $progress): void
    {
        $this->progress = $progress;
    }

    /**
     * Returns Progress Detail.
     */
    public function getProgressDetail(): ?ProgressDetail
    {
        return $this->progressDetail;
    }

    /**
     * Sets Progress Detail.
     *
     * @maps progressDetail
     */
    public function setProgressDetail(?ProgressDetail $progressDetail): void
    {
        $this->progressDetail = $progressDetail;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Converts the CreateImageInfo object to a human-readable string representation.
     *
     * @return string The string representation of the CreateImageInfo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateImageInfo',
            [
                'error' => $this->error,
                'progress' => $this->progress,
                'progressDetail' => $this->progressDetail,
                'status' => $this->status
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->error)) {
            $json['error']          = $this->error;
        }
        if (isset($this->progress)) {
            $json['progress']       = $this->progress;
        }
        if (isset($this->progressDetail)) {
            $json['progressDetail'] = $this->progressDetail;
        }
        if (isset($this->status)) {
            $json['status']         = $this->status;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
