<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Descriptor1 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $digest;

    /**
     * @var string|null
     */
    private $mediaType;

    /**
     * @var int|null
     */
    private $size;

    /**
     * @var string[]|null
     */
    private $uRLs;

    /**
     * Returns Digest.
     */
    public function getDigest(): ?string
    {
        return $this->digest;
    }

    /**
     * Sets Digest.
     *
     * @maps Digest
     */
    public function setDigest(?string $digest): void
    {
        $this->digest = $digest;
    }

    /**
     * Returns Media Type.
     */
    public function getMediaType(): ?string
    {
        return $this->mediaType;
    }

    /**
     * Sets Media Type.
     *
     * @maps MediaType
     */
    public function setMediaType(?string $mediaType): void
    {
        $this->mediaType = $mediaType;
    }

    /**
     * Returns Size.
     */
    public function getSize(): ?int
    {
        return $this->size;
    }

    /**
     * Sets Size.
     *
     * @maps Size
     */
    public function setSize(?int $size): void
    {
        $this->size = $size;
    }

    /**
     * Returns U R Ls.
     *
     * @return string[]|null
     */
    public function getURLs(): ?array
    {
        return $this->uRLs;
    }

    /**
     * Sets U R Ls.
     *
     * @maps URLs
     *
     * @param string[]|null $uRLs
     */
    public function setURLs(?array $uRLs): void
    {
        $this->uRLs = $uRLs;
    }

    /**
     * Converts the Descriptor1 object to a human-readable string representation.
     *
     * @return string The string representation of the Descriptor1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Descriptor1',
            [
                'digest' => $this->digest,
                'mediaType' => $this->mediaType,
                'size' => $this->size,
                'uRLs' => $this->uRLs
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->digest)) {
            $json['Digest']    = $this->digest;
        }
        if (isset($this->mediaType)) {
            $json['MediaType'] = $this->mediaType;
        }
        if (isset($this->size)) {
            $json['Size']      = $this->size;
        }
        if (isset($this->uRLs)) {
            $json['URLs']      = $this->uRLs;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
