<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class DiscreteResourceSpec implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $kind;

    /**
     * @var int|null
     */
    private $value;

    /**
     * Returns Kind.
     */
    public function getKind(): ?string
    {
        return $this->kind;
    }

    /**
     * Sets Kind.
     *
     * @maps Kind
     */
    public function setKind(?string $kind): void
    {
        $this->kind = $kind;
    }

    /**
     * Returns Value.
     */
    public function getValue(): ?int
    {
        return $this->value;
    }

    /**
     * Sets Value.
     *
     * @maps Value
     */
    public function setValue(?int $value): void
    {
        $this->value = $value;
    }

    /**
     * Converts the DiscreteResourceSpec object to a human-readable string representation.
     *
     * @return string The string representation of the DiscreteResourceSpec object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('DiscreteResourceSpec', ['kind' => $this->kind, 'value' => $this->value]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->kind)) {
            $json['Kind']  = $this->kind;
        }
        if (isset($this->value)) {
            $json['Value'] = $this->value;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
