<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class DNSConfig2 implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $nameservers;

    /**
     * @var string[]|null
     */
    private $options;

    /**
     * @var string[]|null
     */
    private $search;

    /**
     * Returns Nameservers.
     * The IP addresses of the name servers.
     *
     * @return string[]|null
     */
    public function getNameservers(): ?array
    {
        return $this->nameservers;
    }

    /**
     * Sets Nameservers.
     * The IP addresses of the name servers.
     *
     * @maps Nameservers
     *
     * @param string[]|null $nameservers
     */
    public function setNameservers(?array $nameservers): void
    {
        $this->nameservers = $nameservers;
    }

    /**
     * Returns Options.
     * A list of internal resolver variables to be modified (e.g., `debug`, `ndots:3`, etc.).
     *
     * @return string[]|null
     */
    public function getOptions(): ?array
    {
        return $this->options;
    }

    /**
     * Sets Options.
     * A list of internal resolver variables to be modified (e.g., `debug`, `ndots:3`, etc.).
     *
     * @maps Options
     *
     * @param string[]|null $options
     */
    public function setOptions(?array $options): void
    {
        $this->options = $options;
    }

    /**
     * Returns Search.
     * A search list for host-name lookup.
     *
     * @return string[]|null
     */
    public function getSearch(): ?array
    {
        return $this->search;
    }

    /**
     * Sets Search.
     * A search list for host-name lookup.
     *
     * @maps Search
     *
     * @param string[]|null $search
     */
    public function setSearch(?array $search): void
    {
        $this->search = $search;
    }

    /**
     * Converts the DNSConfig2 object to a human-readable string representation.
     *
     * @return string The string representation of the DNSConfig2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'DNSConfig2',
            ['nameservers' => $this->nameservers, 'options' => $this->options, 'search' => $this->search]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->nameservers)) {
            $json['Nameservers'] = $this->nameservers;
        }
        if (isset($this->options)) {
            $json['Options']     = $this->options;
        }
        if (isset($this->search)) {
            $json['Search']      = $this->search;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
