<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Endpoint implements \JsonSerializable
{
    /**
     * @var EndpointPortConfig[]|null
     */
    private $ports;

    /**
     * @var Spec2|null
     */
    private $spec;

    /**
     * @var VirtualIP[]|null
     */
    private $virtualIPs;

    /**
     * Returns Ports.
     *
     * @return EndpointPortConfig[]|null
     */
    public function getPorts(): ?array
    {
        return $this->ports;
    }

    /**
     * Sets Ports.
     *
     * @maps Ports
     *
     * @param EndpointPortConfig[]|null $ports
     */
    public function setPorts(?array $ports): void
    {
        $this->ports = $ports;
    }

    /**
     * Returns Spec.
     */
    public function getSpec(): ?Spec2
    {
        return $this->spec;
    }

    /**
     * Sets Spec.
     *
     * @maps Spec
     */
    public function setSpec(?Spec2 $spec): void
    {
        $this->spec = $spec;
    }

    /**
     * Returns Virtual I Ps.
     *
     * @return VirtualIP[]|null
     */
    public function getVirtualIPs(): ?array
    {
        return $this->virtualIPs;
    }

    /**
     * Sets Virtual I Ps.
     *
     * @maps VirtualIPs
     *
     * @param VirtualIP[]|null $virtualIPs
     */
    public function setVirtualIPs(?array $virtualIPs): void
    {
        $this->virtualIPs = $virtualIPs;
    }

    /**
     * Converts the Endpoint object to a human-readable string representation.
     *
     * @return string The string representation of the Endpoint object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Endpoint',
            ['ports' => $this->ports, 'spec' => $this->spec, 'virtualIPs' => $this->virtualIPs]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->ports)) {
            $json['Ports']      = $this->ports;
        }
        if (isset($this->spec)) {
            $json['Spec']       = $this->spec;
        }
        if (isset($this->virtualIPs)) {
            $json['VirtualIPs'] = $this->virtualIPs;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
