<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Errinfo2 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $apiCallDockerId;

    /**
     * @var string|null
     */
    private $apiCallName;

    /**
     * @var string|null
     */
    private $apiCallStart;

    /**
     * @var string|null
     */
    private $apiCallTxnid;

    /**
     * Returns Api Call Docker Id.
     * ID of docker user.
     */
    public function getApiCallDockerId(): ?string
    {
        return $this->apiCallDockerId;
    }

    /**
     * Sets Api Call Docker Id.
     * ID of docker user.
     *
     * @maps api_call_docker_id
     */
    public function setApiCallDockerId(?string $apiCallDockerId): void
    {
        $this->apiCallDockerId = $apiCallDockerId;
    }

    /**
     * Returns Api Call Name.
     * Name of the API operation called.
     */
    public function getApiCallName(): ?string
    {
        return $this->apiCallName;
    }

    /**
     * Sets Api Call Name.
     * Name of the API operation called.
     *
     * @maps api_call_name
     */
    public function setApiCallName(?string $apiCallName): void
    {
        $this->apiCallName = $apiCallName;
    }

    /**
     * Returns Api Call Start.
     * Date/time of call start.
     */
    public function getApiCallStart(): ?string
    {
        return $this->apiCallStart;
    }

    /**
     * Sets Api Call Start.
     * Date/time of call start.
     *
     * @maps api_call_start
     */
    public function setApiCallStart(?string $apiCallStart): void
    {
        $this->apiCallStart = $apiCallStart;
    }

    /**
     * Returns Api Call Txnid.
     * Unique ID for this call.
     */
    public function getApiCallTxnid(): ?string
    {
        return $this->apiCallTxnid;
    }

    /**
     * Sets Api Call Txnid.
     * Unique ID for this call.
     *
     * @maps api_call_txnid
     */
    public function setApiCallTxnid(?string $apiCallTxnid): void
    {
        $this->apiCallTxnid = $apiCallTxnid;
    }

    /**
     * Converts the Errinfo2 object to a human-readable string representation.
     *
     * @return string The string representation of the Errinfo2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Errinfo2',
            [
                'apiCallDockerId' => $this->apiCallDockerId,
                'apiCallName' => $this->apiCallName,
                'apiCallStart' => $this->apiCallStart,
                'apiCallTxnid' => $this->apiCallTxnid
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->apiCallDockerId)) {
            $json['api_call_docker_id'] = $this->apiCallDockerId;
        }
        if (isset($this->apiCallName)) {
            $json['api_call_name']      = $this->apiCallName;
        }
        if (isset($this->apiCallStart)) {
            $json['api_call_start']     = $this->apiCallStart;
        }
        if (isset($this->apiCallTxnid)) {
            $json['api_call_txnid']     = $this->apiCallTxnid;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
