<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class EventsResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $action;

    /**
     * @var Actor|null
     */
    private $actor;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var int|null
     */
    private $time;

    /**
     * @var int|null
     */
    private $timeNano;

    /**
     * Returns Action.
     * The type of event
     */
    public function getAction(): ?string
    {
        return $this->action;
    }

    /**
     * Sets Action.
     * The type of event
     *
     * @maps Action
     */
    public function setAction(?string $action): void
    {
        $this->action = $action;
    }

    /**
     * Returns Actor.
     */
    public function getActor(): ?Actor
    {
        return $this->actor;
    }

    /**
     * Sets Actor.
     *
     * @maps Actor
     */
    public function setActor(?Actor $actor): void
    {
        $this->actor = $actor;
    }

    /**
     * Returns Type.
     * The type of object emitting the event
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of object emitting the event
     *
     * @maps Type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Time.
     * Timestamp of event
     */
    public function getTime(): ?int
    {
        return $this->time;
    }

    /**
     * Sets Time.
     * Timestamp of event
     *
     * @maps time
     */
    public function setTime(?int $time): void
    {
        $this->time = $time;
    }

    /**
     * Returns Time Nano.
     * Timestamp of event, with nanosecond accuracy
     */
    public function getTimeNano(): ?int
    {
        return $this->timeNano;
    }

    /**
     * Sets Time Nano.
     * Timestamp of event, with nanosecond accuracy
     *
     * @maps timeNano
     */
    public function setTimeNano(?int $timeNano): void
    {
        $this->timeNano = $timeNano;
    }

    /**
     * Converts the EventsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the EventsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'EventsResponse',
            [
                'action' => $this->action,
                'actor' => $this->actor,
                'type' => $this->type,
                'time' => $this->time,
                'timeNano' => $this->timeNano
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->action)) {
            $json['Action']   = $this->action;
        }
        if (isset($this->actor)) {
            $json['Actor']    = $this->actor;
        }
        if (isset($this->type)) {
            $json['Type']     = $this->type;
        }
        if (isset($this->time)) {
            $json['time']     = $this->time;
        }
        if (isset($this->timeNano)) {
            $json['timeNano'] = $this->timeNano;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
