<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ExecStartRequest implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $detach;

    /**
     * @var bool|null
     */
    private $tty;

    /**
     * Returns Detach.
     * Detach from the command.
     */
    public function getDetach(): ?bool
    {
        return $this->detach;
    }

    /**
     * Sets Detach.
     * Detach from the command.
     *
     * @maps Detach
     */
    public function setDetach(?bool $detach): void
    {
        $this->detach = $detach;
    }

    /**
     * Returns Tty.
     * Allocate a pseudo-TTY.
     */
    public function getTty(): ?bool
    {
        return $this->tty;
    }

    /**
     * Sets Tty.
     * Allocate a pseudo-TTY.
     *
     * @maps Tty
     */
    public function setTty(?bool $tty): void
    {
        $this->tty = $tty;
    }

    /**
     * Converts the ExecStartRequest object to a human-readable string representation.
     *
     * @return string The string representation of the ExecStartRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ExecStartRequest', ['detach' => $this->detach, 'tty' => $this->tty]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->detach)) {
            $json['Detach'] = $this->detach;
        }
        if (isset($this->tty)) {
            $json['Tty']    = $this->tty;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
