<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ExternalCA implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $cACert;

    /**
     * @var array<string,string>|null
     */
    private $options;

    /**
     * @var string|null
     */
    private $protocol;

    /**
     * @var string|null
     */
    private $uRL;

    /**
     * Returns C a Cert.
     * The root CA certificate (in PEM format) this external CA uses to issue TLS certificates (assumed to
     * be to the current swarm root CA certificate if not provided).
     */
    public function getCACert(): ?string
    {
        return $this->cACert;
    }

    /**
     * Sets C a Cert.
     * The root CA certificate (in PEM format) this external CA uses to issue TLS certificates (assumed to
     * be to the current swarm root CA certificate if not provided).
     *
     * @maps CACert
     */
    public function setCACert(?string $cACert): void
    {
        $this->cACert = $cACert;
    }

    /**
     * Returns Options.
     * An object with key/value pairs that are interpreted as protocol-specific options for the external CA
     * driver.
     *
     * @return array<string,string>|null
     */
    public function getOptions(): ?array
    {
        return $this->options;
    }

    /**
     * Sets Options.
     * An object with key/value pairs that are interpreted as protocol-specific options for the external CA
     * driver.
     *
     * @maps Options
     *
     * @param array<string,string>|null $options
     */
    public function setOptions(?array $options): void
    {
        $this->options = $options;
    }

    /**
     * Returns Protocol.
     */
    public function getProtocol(): ?string
    {
        return $this->protocol;
    }

    /**
     * Sets Protocol.
     *
     * @maps Protocol
     * @factory \DockerLib\Models\ProtocolEnum::checkValue
     */
    public function setProtocol(?string $protocol): void
    {
        $this->protocol = $protocol;
    }

    /**
     * Returns U RL.
     * URL where certificate signing requests should be sent.
     */
    public function getURL(): ?string
    {
        return $this->uRL;
    }

    /**
     * Sets U RL.
     * URL where certificate signing requests should be sent.
     *
     * @maps URL
     */
    public function setURL(?string $uRL): void
    {
        $this->uRL = $uRL;
    }

    /**
     * Converts the ExternalCA object to a human-readable string representation.
     *
     * @return string The string representation of the ExternalCA object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ExternalCA',
            [
                'cACert' => $this->cACert,
                'options' => $this->options,
                'protocol' => $this->protocol,
                'uRL' => $this->uRL
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cACert)) {
            $json['CACert']   = $this->cACert;
        }
        if (isset($this->options)) {
            $json['Options']  = $this->options;
        }
        if (isset($this->protocol)) {
            $json['Protocol'] = ProtocolEnum::checkValue($this->protocol);
        }
        if (isset($this->uRL)) {
            $json['URL']      = $this->uRL;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
