<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Action to take if an updated task fails to run, or stops running during the update.
 */
class FailureAction1Enum
{
    public const CONTINUE_ = 'continue';

    public const PAUSE = 'pause';

    public const ROLLBACK = 'rollback';

    private const _ALL_VALUES = [self::CONTINUE_, self::PAUSE, self::ROLLBACK];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for FailureAction1Enum.");
    }
}
