<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class File1 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $gID;

    /**
     * @var int|null
     */
    private $mode;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $uID;

    /**
     * Returns G ID.
     * GID represents the file GID.
     */
    public function getGID(): ?string
    {
        return $this->gID;
    }

    /**
     * Sets G ID.
     * GID represents the file GID.
     *
     * @maps GID
     */
    public function setGID(?string $gID): void
    {
        $this->gID = $gID;
    }

    /**
     * Returns Mode.
     * Mode represents the FileMode of the file.
     */
    public function getMode(): ?int
    {
        return $this->mode;
    }

    /**
     * Sets Mode.
     * Mode represents the FileMode of the file.
     *
     * @maps Mode
     */
    public function setMode(?int $mode): void
    {
        $this->mode = $mode;
    }

    /**
     * Returns Name.
     * Name represents the final filename in the filesystem.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Name represents the final filename in the filesystem.
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns U ID.
     * UID represents the file UID.
     */
    public function getUID(): ?string
    {
        return $this->uID;
    }

    /**
     * Sets U ID.
     * UID represents the file UID.
     *
     * @maps UID
     */
    public function setUID(?string $uID): void
    {
        $this->uID = $uID;
    }

    /**
     * Converts the File1 object to a human-readable string representation.
     *
     * @return string The string representation of the File1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'File1',
            ['gID' => $this->gID, 'mode' => $this->mode, 'name' => $this->name, 'uID' => $this->uID]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->gID)) {
            $json['GID']  = $this->gID;
        }
        if (isset($this->mode)) {
            $json['Mode'] = $this->mode;
        }
        if (isset($this->name)) {
            $json['Name'] = $this->name;
        }
        if (isset($this->uID)) {
            $json['UID']  = $this->uID;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
