<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * GetAuditActions response.
 */
class GetAuditActionsResponse implements \JsonSerializable
{
    /**
     * @var array<string,AuditLogActions>|null
     */
    private $actions;

    /**
     * Returns Actions.
     * Map of audit log actions.
     *
     * @return array<string,AuditLogActions>|null
     */
    public function getActions(): ?array
    {
        return $this->actions;
    }

    /**
     * Sets Actions.
     * Map of audit log actions.
     *
     * @maps actions
     *
     * @param array<string,AuditLogActions>|null $actions
     */
    public function setActions(?array $actions): void
    {
        $this->actions = $actions;
    }

    /**
     * Converts the GetAuditActionsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the GetAuditActionsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('GetAuditActionsResponse', ['actions' => $this->actions]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->actions)) {
            $json['actions'] = $this->actions;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
