<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ImageDeleteResponseItem implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $deleted;

    /**
     * @var string|null
     */
    private $untagged;

    /**
     * Returns Deleted.
     * The image ID of an image that was deleted
     */
    public function getDeleted(): ?string
    {
        return $this->deleted;
    }

    /**
     * Sets Deleted.
     * The image ID of an image that was deleted
     *
     * @maps Deleted
     */
    public function setDeleted(?string $deleted): void
    {
        $this->deleted = $deleted;
    }

    /**
     * Returns Untagged.
     * The image ID of an image that was untagged
     */
    public function getUntagged(): ?string
    {
        return $this->untagged;
    }

    /**
     * Sets Untagged.
     * The image ID of an image that was untagged
     *
     * @maps Untagged
     */
    public function setUntagged(?string $untagged): void
    {
        $this->untagged = $untagged;
    }

    /**
     * Converts the ImageDeleteResponseItem object to a human-readable string representation.
     *
     * @return string The string representation of the ImageDeleteResponseItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ImageDeleteResponseItem',
            ['deleted' => $this->deleted, 'untagged' => $this->untagged]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->deleted)) {
            $json['Deleted']  = $this->deleted;
        }
        if (isset($this->untagged)) {
            $json['Untagged'] = $this->untagged;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
