<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ImagesHistoryResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $comment;

    /**
     * @var int
     */
    private $created;

    /**
     * @var string
     */
    private $createdBy;

    /**
     * @var string
     */
    private $id;

    /**
     * @var int
     */
    private $size;

    /**
     * @var string[]
     */
    private $tags;

    /**
     * @param string $comment
     * @param int $created
     * @param string $createdBy
     * @param string $id
     * @param int $size
     * @param string[] $tags
     */
    public function __construct(string $comment, int $created, string $createdBy, string $id, int $size, array $tags)
    {
        $this->comment = $comment;
        $this->created = $created;
        $this->createdBy = $createdBy;
        $this->id = $id;
        $this->size = $size;
        $this->tags = $tags;
    }

    /**
     * Returns Comment.
     */
    public function getComment(): string
    {
        return $this->comment;
    }

    /**
     * Sets Comment.
     *
     * @required
     * @maps Comment
     */
    public function setComment(string $comment): void
    {
        $this->comment = $comment;
    }

    /**
     * Returns Created.
     */
    public function getCreated(): int
    {
        return $this->created;
    }

    /**
     * Sets Created.
     *
     * @required
     * @maps Created
     */
    public function setCreated(int $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Created By.
     */
    public function getCreatedBy(): string
    {
        return $this->createdBy;
    }

    /**
     * Sets Created By.
     *
     * @required
     * @maps CreatedBy
     */
    public function setCreatedBy(string $createdBy): void
    {
        $this->createdBy = $createdBy;
    }

    /**
     * Returns Id.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps Id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Size.
     */
    public function getSize(): int
    {
        return $this->size;
    }

    /**
     * Sets Size.
     *
     * @required
     * @maps Size
     */
    public function setSize(int $size): void
    {
        $this->size = $size;
    }

    /**
     * Returns Tags.
     *
     * @return string[]
     */
    public function getTags(): array
    {
        return $this->tags;
    }

    /**
     * Sets Tags.
     *
     * @required
     * @maps Tags
     *
     * @param string[] $tags
     */
    public function setTags(array $tags): void
    {
        $this->tags = $tags;
    }

    /**
     * Converts the ImagesHistoryResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ImagesHistoryResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ImagesHistoryResponse',
            [
                'comment' => $this->comment,
                'created' => $this->created,
                'createdBy' => $this->createdBy,
                'id' => $this->id,
                'size' => $this->size,
                'tags' => $this->tags
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Comment']   = $this->comment;
        $json['Created']   = $this->created;
        $json['CreatedBy'] = $this->createdBy;
        $json['Id']        = $this->id;
        $json['Size']      = $this->size;
        $json['Tags']      = $this->tags;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
