<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class IPAM implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $config;

    /**
     * @var string|null
     */
    private $driver = 'default';

    /**
     * @var string[]|null
     */
    private $options;

    /**
     * Returns Config.
     * List of IPAM configuration options, specified as a map: `{"Subnet": <CIDR>, "IPRange": <CIDR>,
     * "Gateway": <IP address>, "AuxAddress": <device_name:IP address>}`
     *
     * @return string[]|null
     */
    public function getConfig(): ?array
    {
        return $this->config;
    }

    /**
     * Sets Config.
     * List of IPAM configuration options, specified as a map: `{"Subnet": <CIDR>, "IPRange": <CIDR>,
     * "Gateway": <IP address>, "AuxAddress": <device_name:IP address>}`
     *
     * @maps Config
     *
     * @param string[]|null $config
     */
    public function setConfig(?array $config): void
    {
        $this->config = $config;
    }

    /**
     * Returns Driver.
     * Name of the IPAM driver to use.
     */
    public function getDriver(): ?string
    {
        return $this->driver;
    }

    /**
     * Sets Driver.
     * Name of the IPAM driver to use.
     *
     * @maps Driver
     */
    public function setDriver(?string $driver): void
    {
        $this->driver = $driver;
    }

    /**
     * Returns Options.
     * Driver-specific options, specified as a map.
     *
     * @return string[]|null
     */
    public function getOptions(): ?array
    {
        return $this->options;
    }

    /**
     * Sets Options.
     * Driver-specific options, specified as a map.
     *
     * @maps Options
     *
     * @param string[]|null $options
     */
    public function setOptions(?array $options): void
    {
        $this->options = $options;
    }

    /**
     * Converts the IPAM object to a human-readable string representation.
     *
     * @return string The string representation of the IPAM object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'IPAM',
            ['config' => $this->config, 'driver' => $this->driver, 'options' => $this->options]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->config)) {
            $json['Config']  = $this->config;
        }
        if (isset($this->driver)) {
            $json['Driver']  = $this->driver;
        }
        if (isset($this->options)) {
            $json['Options'] = $this->options;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
