<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Layer implements \JsonSerializable
{
    /**
     * @var array
     */
    private $digest = [];

    /**
     * @var string|null
     */
    private $instruction;

    /**
     * @var int|null
     */
    private $size;

    /**
     * Returns Digest.
     * image layer digest
     */
    public function getDigest(): ?string
    {
        if (count($this->digest) == 0) {
            return null;
        }
        return $this->digest['value'];
    }

    /**
     * Sets Digest.
     * image layer digest
     *
     * @maps digest
     */
    public function setDigest(?string $digest): void
    {
        $this->digest['value'] = $digest;
    }

    /**
     * Unsets Digest.
     * image layer digest
     */
    public function unsetDigest(): void
    {
        $this->digest = [];
    }

    /**
     * Returns Instruction.
     * Dockerfile instruction
     */
    public function getInstruction(): ?string
    {
        return $this->instruction;
    }

    /**
     * Sets Instruction.
     * Dockerfile instruction
     *
     * @maps instruction
     */
    public function setInstruction(?string $instruction): void
    {
        $this->instruction = $instruction;
    }

    /**
     * Returns Size.
     * size of the layer
     */
    public function getSize(): ?int
    {
        return $this->size;
    }

    /**
     * Sets Size.
     * size of the layer
     *
     * @maps size
     */
    public function setSize(?int $size): void
    {
        $this->size = $size;
    }

    /**
     * Converts the Layer object to a human-readable string representation.
     *
     * @return string The string representation of the Layer object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Layer',
            ['digest' => $this->getDigest(), 'instruction' => $this->instruction, 'size' => $this->size]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->digest)) {
            $json['digest']      = $this->digest['value'];
        }
        if (isset($this->instruction)) {
            $json['instruction'] = $this->instruction;
        }
        if (isset($this->size)) {
            $json['size']        = $this->size;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
