<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Linux implements \JsonSerializable
{
    /**
     * @var bool
     */
    private $allowAllDevices;

    /**
     * @var string[]
     */
    private $capabilities;

    /**
     * @var PluginDevice[]
     */
    private $devices;

    /**
     * @param bool $allowAllDevices
     * @param string[] $capabilities
     * @param PluginDevice[] $devices
     */
    public function __construct(bool $allowAllDevices, array $capabilities, array $devices)
    {
        $this->allowAllDevices = $allowAllDevices;
        $this->capabilities = $capabilities;
        $this->devices = $devices;
    }

    /**
     * Returns Allow All Devices.
     */
    public function getAllowAllDevices(): bool
    {
        return $this->allowAllDevices;
    }

    /**
     * Sets Allow All Devices.
     *
     * @required
     * @maps AllowAllDevices
     */
    public function setAllowAllDevices(bool $allowAllDevices): void
    {
        $this->allowAllDevices = $allowAllDevices;
    }

    /**
     * Returns Capabilities.
     *
     * @return string[]
     */
    public function getCapabilities(): array
    {
        return $this->capabilities;
    }

    /**
     * Sets Capabilities.
     *
     * @required
     * @maps Capabilities
     *
     * @param string[] $capabilities
     */
    public function setCapabilities(array $capabilities): void
    {
        $this->capabilities = $capabilities;
    }

    /**
     * Returns Devices.
     *
     * @return PluginDevice[]
     */
    public function getDevices(): array
    {
        return $this->devices;
    }

    /**
     * Sets Devices.
     *
     * @required
     * @maps Devices
     *
     * @param PluginDevice[] $devices
     */
    public function setDevices(array $devices): void
    {
        $this->devices = $devices;
    }

    /**
     * Converts the Linux object to a human-readable string representation.
     *
     * @return string The string representation of the Linux object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Linux',
            [
                'allowAllDevices' => $this->allowAllDevices,
                'capabilities' => $this->capabilities,
                'devices' => $this->devices
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['AllowAllDevices'] = $this->allowAllDevices;
        $json['Capabilities']    = $this->capabilities;
        $json['Devices']         = $this->devices;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
