<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Manifest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $digest;

    /**
     * @var string
     */
    private $repository;

    /**
     * @param string $digest
     * @param string $repository
     */
    public function __construct(string $digest, string $repository)
    {
        $this->digest = $digest;
        $this->repository = $repository;
    }

    /**
     * Returns Digest.
     * Digest of the image to delete.
     */
    public function getDigest(): string
    {
        return $this->digest;
    }

    /**
     * Sets Digest.
     * Digest of the image to delete.
     *
     * @required
     * @maps digest
     */
    public function setDigest(string $digest): void
    {
        $this->digest = $digest;
    }

    /**
     * Returns Repository.
     * Name of the repository to delete the image from.
     */
    public function getRepository(): string
    {
        return $this->repository;
    }

    /**
     * Sets Repository.
     * Name of the repository to delete the image from.
     *
     * @required
     * @maps repository
     */
    public function setRepository(string $repository): void
    {
        $this->repository = $repository;
    }

    /**
     * Converts the Manifest object to a human-readable string representation.
     *
     * @return string The string representation of the Manifest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Manifest', ['digest' => $this->digest, 'repository' => $this->repository]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['digest']     = $this->digest;
        $json['repository'] = $this->repository;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
