<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Metadata implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $lastTagTime;

    /**
     * Returns Last Tag Time.
     */
    public function getLastTagTime(): ?string
    {
        return $this->lastTagTime;
    }

    /**
     * Sets Last Tag Time.
     *
     * @maps LastTagTime
     */
    public function setLastTagTime(?string $lastTagTime): void
    {
        $this->lastTagTime = $lastTagTime;
    }

    /**
     * Converts the Metadata object to a human-readable string representation.
     *
     * @return string The string representation of the Metadata object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Metadata', ['lastTagTime' => $this->lastTagTime]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->lastTagTime)) {
            $json['LastTagTime'] = $this->lastTagTime;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
