<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Mount implements \JsonSerializable
{
    /**
     * @var BindOptions2|null
     */
    private $bindOptions;

    /**
     * @var string|null
     */
    private $consistency;

    /**
     * @var bool|null
     */
    private $readOnly;

    /**
     * @var string|null
     */
    private $source;

    /**
     * @var string|null
     */
    private $target;

    /**
     * @var TmpfsOptions2|null
     */
    private $tmpfsOptions;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var VolumeOptions2|null
     */
    private $volumeOptions;

    /**
     * Returns Bind Options.
     */
    public function getBindOptions(): ?BindOptions2
    {
        return $this->bindOptions;
    }

    /**
     * Sets Bind Options.
     *
     * @maps BindOptions
     */
    public function setBindOptions(?BindOptions2 $bindOptions): void
    {
        $this->bindOptions = $bindOptions;
    }

    /**
     * Returns Consistency.
     * The consistency requirement for the mount: `default`, `consistent`, `cached`, or `delegated`.
     */
    public function getConsistency(): ?string
    {
        return $this->consistency;
    }

    /**
     * Sets Consistency.
     * The consistency requirement for the mount: `default`, `consistent`, `cached`, or `delegated`.
     *
     * @maps Consistency
     */
    public function setConsistency(?string $consistency): void
    {
        $this->consistency = $consistency;
    }

    /**
     * Returns Read Only.
     * Whether the mount should be read-only.
     */
    public function getReadOnly(): ?bool
    {
        return $this->readOnly;
    }

    /**
     * Sets Read Only.
     * Whether the mount should be read-only.
     *
     * @maps ReadOnly
     */
    public function setReadOnly(?bool $readOnly): void
    {
        $this->readOnly = $readOnly;
    }

    /**
     * Returns Source.
     * Mount source (e.g. a volume name, a host path).
     */
    public function getSource(): ?string
    {
        return $this->source;
    }

    /**
     * Sets Source.
     * Mount source (e.g. a volume name, a host path).
     *
     * @maps Source
     */
    public function setSource(?string $source): void
    {
        $this->source = $source;
    }

    /**
     * Returns Target.
     * Container path.
     */
    public function getTarget(): ?string
    {
        return $this->target;
    }

    /**
     * Sets Target.
     * Container path.
     *
     * @maps Target
     */
    public function setTarget(?string $target): void
    {
        $this->target = $target;
    }

    /**
     * Returns Tmpfs Options.
     */
    public function getTmpfsOptions(): ?TmpfsOptions2
    {
        return $this->tmpfsOptions;
    }

    /**
     * Sets Tmpfs Options.
     *
     * @maps TmpfsOptions
     */
    public function setTmpfsOptions(?TmpfsOptions2 $tmpfsOptions): void
    {
        $this->tmpfsOptions = $tmpfsOptions;
    }

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps Type
     * @factory \DockerLib\Models\TypeEnum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Volume Options.
     */
    public function getVolumeOptions(): ?VolumeOptions2
    {
        return $this->volumeOptions;
    }

    /**
     * Sets Volume Options.
     *
     * @maps VolumeOptions
     */
    public function setVolumeOptions(?VolumeOptions2 $volumeOptions): void
    {
        $this->volumeOptions = $volumeOptions;
    }

    /**
     * Converts the Mount object to a human-readable string representation.
     *
     * @return string The string representation of the Mount object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Mount',
            [
                'bindOptions' => $this->bindOptions,
                'consistency' => $this->consistency,
                'readOnly' => $this->readOnly,
                'source' => $this->source,
                'target' => $this->target,
                'tmpfsOptions' => $this->tmpfsOptions,
                'type' => $this->type,
                'volumeOptions' => $this->volumeOptions
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->bindOptions)) {
            $json['BindOptions']   = $this->bindOptions;
        }
        if (isset($this->consistency)) {
            $json['Consistency']   = $this->consistency;
        }
        if (isset($this->readOnly)) {
            $json['ReadOnly']      = $this->readOnly;
        }
        if (isset($this->source)) {
            $json['Source']        = $this->source;
        }
        if (isset($this->target)) {
            $json['Target']        = $this->target;
        }
        if (isset($this->tmpfsOptions)) {
            $json['TmpfsOptions']  = $this->tmpfsOptions;
        }
        if (isset($this->type)) {
            $json['Type']          = TypeEnum::checkValue($this->type);
        }
        if (isset($this->volumeOptions)) {
            $json['VolumeOptions'] = $this->volumeOptions;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
