<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Network2 implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $aliases;

    /**
     * @var string|null
     */
    private $target;

    /**
     * Returns Aliases.
     *
     * @return string[]|null
     */
    public function getAliases(): ?array
    {
        return $this->aliases;
    }

    /**
     * Sets Aliases.
     *
     * @maps Aliases
     *
     * @param string[]|null $aliases
     */
    public function setAliases(?array $aliases): void
    {
        $this->aliases = $aliases;
    }

    /**
     * Returns Target.
     */
    public function getTarget(): ?string
    {
        return $this->target;
    }

    /**
     * Sets Target.
     *
     * @maps Target
     */
    public function setTarget(?string $target): void
    {
        $this->target = $target;
    }

    /**
     * Converts the Network2 object to a human-readable string representation.
     *
     * @return string The string representation of the Network2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Network2', ['aliases' => $this->aliases, 'target' => $this->target]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->aliases)) {
            $json['Aliases'] = $this->aliases;
        }
        if (isset($this->target)) {
            $json['Target']  = $this->target;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
