<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class NetworksDisconnectRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $container;

    /**
     * @var bool|null
     */
    private $force;

    /**
     * Returns Container.
     * The ID or name of the container to disconnect from the network.
     */
    public function getContainer(): ?string
    {
        return $this->container;
    }

    /**
     * Sets Container.
     * The ID or name of the container to disconnect from the network.
     *
     * @maps Container
     */
    public function setContainer(?string $container): void
    {
        $this->container = $container;
    }

    /**
     * Returns Force.
     * Force the container to disconnect from the network.
     */
    public function getForce(): ?bool
    {
        return $this->force;
    }

    /**
     * Sets Force.
     * Force the container to disconnect from the network.
     *
     * @maps Force
     */
    public function setForce(?bool $force): void
    {
        $this->force = $force;
    }

    /**
     * Converts the NetworksDisconnectRequest object to a human-readable string representation.
     *
     * @return string The string representation of the NetworksDisconnectRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'NetworksDisconnectRequest',
            ['container' => $this->container, 'force' => $this->force]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->container)) {
            $json['Container'] = $this->container;
        }
        if (isset($this->force)) {
            $json['Force']     = $this->force;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
