<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Placement implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $constraints;

    /**
     * @var Platform[]|null
     */
    private $platforms;

    /**
     * @var Preference[]|null
     */
    private $preferences;

    /**
     * Returns Constraints.
     * An array of constraints.
     *
     * @return string[]|null
     */
    public function getConstraints(): ?array
    {
        return $this->constraints;
    }

    /**
     * Sets Constraints.
     * An array of constraints.
     *
     * @maps Constraints
     *
     * @param string[]|null $constraints
     */
    public function setConstraints(?array $constraints): void
    {
        $this->constraints = $constraints;
    }

    /**
     * Returns Platforms.
     * Platforms stores all the platforms that the service's image can
     * run on. This field is used in the platform filter for scheduling.
     * If empty, then the platform filter is off, meaning there are no
     * scheduling restrictions.
     *
     * @return Platform[]|null
     */
    public function getPlatforms(): ?array
    {
        return $this->platforms;
    }

    /**
     * Sets Platforms.
     * Platforms stores all the platforms that the service's image can
     * run on. This field is used in the platform filter for scheduling.
     * If empty, then the platform filter is off, meaning there are no
     * scheduling restrictions.
     *
     * @maps Platforms
     *
     * @param Platform[]|null $platforms
     */
    public function setPlatforms(?array $platforms): void
    {
        $this->platforms = $platforms;
    }

    /**
     * Returns Preferences.
     * Preferences provide a way to make the scheduler aware of factors such as topology. They are provided
     * in order from highest to lowest precedence.
     *
     * @return Preference[]|null
     */
    public function getPreferences(): ?array
    {
        return $this->preferences;
    }

    /**
     * Sets Preferences.
     * Preferences provide a way to make the scheduler aware of factors such as topology. They are provided
     * in order from highest to lowest precedence.
     *
     * @maps Preferences
     *
     * @param Preference[]|null $preferences
     */
    public function setPreferences(?array $preferences): void
    {
        $this->preferences = $preferences;
    }

    /**
     * Converts the Placement object to a human-readable string representation.
     *
     * @return string The string representation of the Placement object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Placement',
            [
                'constraints' => $this->constraints,
                'platforms' => $this->platforms,
                'preferences' => $this->preferences
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->constraints)) {
            $json['Constraints'] = $this->constraints;
        }
        if (isset($this->platforms)) {
            $json['Platforms']   = $this->platforms;
        }
        if (isset($this->preferences)) {
            $json['Preferences'] = $this->preferences;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
