<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * Platform represents the platform (Arch/OS).
 */
class Platform implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $architecture;

    /**
     * @var string|null
     */
    private $oS;

    /**
     * Returns Architecture.
     * Architecture represents the hardware architecture (for example,
     * `x86_64`).
     */
    public function getArchitecture(): ?string
    {
        return $this->architecture;
    }

    /**
     * Sets Architecture.
     * Architecture represents the hardware architecture (for example,
     * `x86_64`).
     *
     * @maps Architecture
     */
    public function setArchitecture(?string $architecture): void
    {
        $this->architecture = $architecture;
    }

    /**
     * Returns O S.
     * OS represents the Operating System (for example, `linux` or `windows`).
     */
    public function getOS(): ?string
    {
        return $this->oS;
    }

    /**
     * Sets O S.
     * OS represents the Operating System (for example, `linux` or `windows`).
     *
     * @maps OS
     */
    public function setOS(?string $oS): void
    {
        $this->oS = $oS;
    }

    /**
     * Converts the Platform object to a human-readable string representation.
     *
     * @return string The string representation of the Platform object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Platform', ['architecture' => $this->architecture, 'oS' => $this->oS]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->architecture)) {
            $json['Architecture'] = $this->architecture;
        }
        if (isset($this->oS)) {
            $json['OS']           = $this->oS;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
