<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Platform1 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $architecture;

    /**
     * @var string[]|null
     */
    private $features;

    /**
     * @var string|null
     */
    private $oS;

    /**
     * @var string[]|null
     */
    private $oSFeatures;

    /**
     * @var string|null
     */
    private $oSVersion;

    /**
     * @var string|null
     */
    private $variant;

    /**
     * Returns Architecture.
     */
    public function getArchitecture(): ?string
    {
        return $this->architecture;
    }

    /**
     * Sets Architecture.
     *
     * @maps Architecture
     */
    public function setArchitecture(?string $architecture): void
    {
        $this->architecture = $architecture;
    }

    /**
     * Returns Features.
     *
     * @return string[]|null
     */
    public function getFeatures(): ?array
    {
        return $this->features;
    }

    /**
     * Sets Features.
     *
     * @maps Features
     *
     * @param string[]|null $features
     */
    public function setFeatures(?array $features): void
    {
        $this->features = $features;
    }

    /**
     * Returns O S.
     */
    public function getOS(): ?string
    {
        return $this->oS;
    }

    /**
     * Sets O S.
     *
     * @maps OS
     */
    public function setOS(?string $oS): void
    {
        $this->oS = $oS;
    }

    /**
     * Returns O S Features.
     *
     * @return string[]|null
     */
    public function getOSFeatures(): ?array
    {
        return $this->oSFeatures;
    }

    /**
     * Sets O S Features.
     *
     * @maps OSFeatures
     *
     * @param string[]|null $oSFeatures
     */
    public function setOSFeatures(?array $oSFeatures): void
    {
        $this->oSFeatures = $oSFeatures;
    }

    /**
     * Returns O S Version.
     */
    public function getOSVersion(): ?string
    {
        return $this->oSVersion;
    }

    /**
     * Sets O S Version.
     *
     * @maps OSVersion
     */
    public function setOSVersion(?string $oSVersion): void
    {
        $this->oSVersion = $oSVersion;
    }

    /**
     * Returns Variant.
     */
    public function getVariant(): ?string
    {
        return $this->variant;
    }

    /**
     * Sets Variant.
     *
     * @maps Variant
     */
    public function setVariant(?string $variant): void
    {
        $this->variant = $variant;
    }

    /**
     * Converts the Platform1 object to a human-readable string representation.
     *
     * @return string The string representation of the Platform1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Platform1',
            [
                'architecture' => $this->architecture,
                'features' => $this->features,
                'oS' => $this->oS,
                'oSFeatures' => $this->oSFeatures,
                'oSVersion' => $this->oSVersion,
                'variant' => $this->variant
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->architecture)) {
            $json['Architecture'] = $this->architecture;
        }
        if (isset($this->features)) {
            $json['Features']     = $this->features;
        }
        if (isset($this->oS)) {
            $json['OS']           = $this->oS;
        }
        if (isset($this->oSFeatures)) {
            $json['OSFeatures']   = $this->oSFeatures;
        }
        if (isset($this->oSVersion)) {
            $json['OSVersion']    = $this->oSVersion;
        }
        if (isset($this->variant)) {
            $json['Variant']      = $this->variant;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
