<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * Invalid when specified with `ContainerSpec`. *(Experimental release only.)*
 */
class PluginSpec implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $disabled;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var PluginPrivilege[]|null
     */
    private $pluginPrivilege;

    /**
     * @var string|null
     */
    private $remote;

    /**
     * Returns Disabled.
     * Disable the plugin once scheduled.
     */
    public function getDisabled(): ?bool
    {
        return $this->disabled;
    }

    /**
     * Sets Disabled.
     * Disable the plugin once scheduled.
     *
     * @maps Disabled
     */
    public function setDisabled(?bool $disabled): void
    {
        $this->disabled = $disabled;
    }

    /**
     * Returns Name.
     * The name or 'alias' to use for the plugin.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name or 'alias' to use for the plugin.
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Plugin Privilege.
     *
     * @return PluginPrivilege[]|null
     */
    public function getPluginPrivilege(): ?array
    {
        return $this->pluginPrivilege;
    }

    /**
     * Sets Plugin Privilege.
     *
     * @maps PluginPrivilege
     *
     * @param PluginPrivilege[]|null $pluginPrivilege
     */
    public function setPluginPrivilege(?array $pluginPrivilege): void
    {
        $this->pluginPrivilege = $pluginPrivilege;
    }

    /**
     * Returns Remote.
     * The plugin image reference to use.
     */
    public function getRemote(): ?string
    {
        return $this->remote;
    }

    /**
     * Sets Remote.
     * The plugin image reference to use.
     *
     * @maps Remote
     */
    public function setRemote(?string $remote): void
    {
        $this->remote = $remote;
    }

    /**
     * Converts the PluginSpec object to a human-readable string representation.
     *
     * @return string The string representation of the PluginSpec object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PluginSpec',
            [
                'disabled' => $this->disabled,
                'name' => $this->name,
                'pluginPrivilege' => $this->pluginPrivilege,
                'remote' => $this->remote
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->disabled)) {
            $json['Disabled']        = $this->disabled;
        }
        if (isset($this->name)) {
            $json['Name']            = $this->name;
        }
        if (isset($this->pluginPrivilege)) {
            $json['PluginPrivilege'] = $this->pluginPrivilege;
        }
        if (isset($this->remote)) {
            $json['Remote']          = $this->remote;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
