<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * PortBinding represents a binding between a host IP address and a host
 * port.
 */
class PortBinding implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $hostIp;

    /**
     * @var string|null
     */
    private $hostPort;

    /**
     * Returns Host Ip.
     * Host IP address that the container's port is mapped to.
     */
    public function getHostIp(): ?string
    {
        return $this->hostIp;
    }

    /**
     * Sets Host Ip.
     * Host IP address that the container's port is mapped to.
     *
     * @maps HostIp
     */
    public function setHostIp(?string $hostIp): void
    {
        $this->hostIp = $hostIp;
    }

    /**
     * Returns Host Port.
     * Host port number that the container's port is mapped to.
     */
    public function getHostPort(): ?string
    {
        return $this->hostPort;
    }

    /**
     * Sets Host Port.
     * Host port number that the container's port is mapped to.
     *
     * @maps HostPort
     */
    public function setHostPort(?string $hostPort): void
    {
        $this->hostPort = $hostPort;
    }

    /**
     * Converts the PortBinding object to a human-readable string representation.
     *
     * @return string The string representation of the PortBinding object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('PortBinding', ['hostIp' => $this->hostIp, 'hostPort' => $this->hostPort]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->hostIp)) {
            $json['HostIp']   = $this->hostIp;
        }
        if (isset($this->hostPort)) {
            $json['HostPort'] = $this->hostPort;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
