<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * Deletion not possible.
 */
class PostNamespacesDeleteImagesResponseError implements \JsonSerializable
{
    /**
     * @var Errinfo|null
     */
    private $errinfo;

    /**
     * @var string|null
     */
    private $message;

    /**
     * @var string|null
     */
    private $txnid;

    /**
     * Returns Errinfo.
     */
    public function getErrinfo(): ?Errinfo
    {
        return $this->errinfo;
    }

    /**
     * Sets Errinfo.
     *
     * @maps errinfo
     */
    public function setErrinfo(?Errinfo $errinfo): void
    {
        $this->errinfo = $errinfo;
    }

    /**
     * Returns Message.
     * The error message.
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     * The error message.
     *
     * @maps message
     */
    public function setMessage(?string $message): void
    {
        $this->message = $message;
    }

    /**
     * Returns Txnid.
     * Unique ID for this call.
     */
    public function getTxnid(): ?string
    {
        return $this->txnid;
    }

    /**
     * Sets Txnid.
     * Unique ID for this call.
     *
     * @maps txnid
     */
    public function setTxnid(?string $txnid): void
    {
        $this->txnid = $txnid;
    }

    /**
     * Converts the PostNamespacesDeleteImagesResponseError object to a human-readable string
     * representation.
     *
     * @return string The string representation of the PostNamespacesDeleteImagesResponseError object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PostNamespacesDeleteImagesResponseError',
            ['errinfo' => $this->errinfo, 'message' => $this->message, 'txnid' => $this->txnid]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->errinfo)) {
            $json['errinfo'] = $this->errinfo;
        }
        if (isset($this->message)) {
            $json['message'] = $this->message;
        }
        if (isset($this->txnid)) {
            $json['txnid']   = $this->txnid;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
