<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * successful user login response
 */
class PostUsersLoginSuccessResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $token;

    /**
     * Returns Token.
     * Created authentication token.
     *
     * This token can be used in the HTTP Authorization header as a JWT to authenticate with the Docker Hub
     * APIs.
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * Sets Token.
     * Created authentication token.
     *
     * This token can be used in the HTTP Authorization header as a JWT to authenticate with the Docker Hub
     * APIs.
     *
     * @maps token
     */
    public function setToken(?string $token): void
    {
        $this->token = $token;
    }

    /**
     * Converts the PostUsersLoginSuccessResponse object to a human-readable string representation.
     *
     * @return string The string representation of the PostUsersLoginSuccessResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('PostUsersLoginSuccessResponse', ['token' => $this->token]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->token)) {
            $json['token'] = $this->token;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
