<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * Security options for the container
 */
class Privileges implements \JsonSerializable
{
    /**
     * @var CredentialSpec2|null
     */
    private $credentialSpec;

    /**
     * @var SELinuxContext2|null
     */
    private $sELinuxContext;

    /**
     * Returns Credential Spec.
     */
    public function getCredentialSpec(): ?CredentialSpec2
    {
        return $this->credentialSpec;
    }

    /**
     * Sets Credential Spec.
     *
     * @maps CredentialSpec
     */
    public function setCredentialSpec(?CredentialSpec2 $credentialSpec): void
    {
        $this->credentialSpec = $credentialSpec;
    }

    /**
     * Returns S E Linux Context.
     */
    public function getSELinuxContext(): ?SELinuxContext2
    {
        return $this->sELinuxContext;
    }

    /**
     * Sets S E Linux Context.
     *
     * @maps SELinuxContext
     */
    public function setSELinuxContext(?SELinuxContext2 $sELinuxContext): void
    {
        $this->sELinuxContext = $sELinuxContext;
    }

    /**
     * Converts the Privileges object to a human-readable string representation.
     *
     * @return string The string representation of the Privileges object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Privileges',
            ['credentialSpec' => $this->credentialSpec, 'sELinuxContext' => $this->sELinuxContext]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->credentialSpec)) {
            $json['CredentialSpec'] = $this->credentialSpec;
        }
        if (isset($this->sELinuxContext)) {
            $json['SELinuxContext'] = $this->sELinuxContext;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
