<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * RegistryServiceConfig stores daemon registry services configuration.
 */
class RegistryServiceConfig implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $allowNondistributableArtifactsCIDRs;

    /**
     * @var string[]|null
     */
    private $allowNondistributableArtifactsHostnames;

    /**
     * @var array<string,array|null|IndexInfo>|null
     */
    private $indexConfigs;

    /**
     * @var string[]|null
     */
    private $insecureRegistryCIDRs;

    /**
     * @var string[]|null
     */
    private $mirrors;

    /**
     * Returns Allow Nondistributable Artifacts CID Rs.
     * List of IP ranges to which nondistributable artifacts can be pushed,
     * using the CIDR syntax [RFC 4632](https://tools.ietf.org/html/4632).
     *
     * Some images (for example, Windows base images) contain artifacts
     * whose distribution is restricted by license. When these images are
     * pushed to a registry, restricted artifacts are not included.
     *
     * This configuration override this behavior, and enables the daemon to
     * push nondistributable artifacts to all registries whose resolved IP
     * address is within the subnet described by the CIDR syntax.
     *
     * This option is useful when pushing images containing
     * nondistributable artifacts to a registry on an air-gapped network so
     * hosts on that network can pull the images without connecting to
     * another server.
     *
     * > **Warning**: Nondistributable artifacts typically have restrictions
     * > on how and where they can be distributed and shared. Only use this
     * > feature to push artifacts to private registries and ensure that you
     * > are in compliance with any terms that cover redistributing
     * > nondistributable artifacts.
     *
     * @return string[]|null
     */
    public function getAllowNondistributableArtifactsCIDRs(): ?array
    {
        return $this->allowNondistributableArtifactsCIDRs;
    }

    /**
     * Sets Allow Nondistributable Artifacts CID Rs.
     * List of IP ranges to which nondistributable artifacts can be pushed,
     * using the CIDR syntax [RFC 4632](https://tools.ietf.org/html/4632).
     *
     * Some images (for example, Windows base images) contain artifacts
     * whose distribution is restricted by license. When these images are
     * pushed to a registry, restricted artifacts are not included.
     *
     * This configuration override this behavior, and enables the daemon to
     * push nondistributable artifacts to all registries whose resolved IP
     * address is within the subnet described by the CIDR syntax.
     *
     * This option is useful when pushing images containing
     * nondistributable artifacts to a registry on an air-gapped network so
     * hosts on that network can pull the images without connecting to
     * another server.
     *
     * > **Warning**: Nondistributable artifacts typically have restrictions
     * > on how and where they can be distributed and shared. Only use this
     * > feature to push artifacts to private registries and ensure that you
     * > are in compliance with any terms that cover redistributing
     * > nondistributable artifacts.
     *
     * @maps AllowNondistributableArtifactsCIDRs
     *
     * @param string[]|null $allowNondistributableArtifactsCIDRs
     */
    public function setAllowNondistributableArtifactsCIDRs(?array $allowNondistributableArtifactsCIDRs): void
    {
        $this->allowNondistributableArtifactsCIDRs = $allowNondistributableArtifactsCIDRs;
    }

    /**
     * Returns Allow Nondistributable Artifacts Hostnames.
     * List of registry hostnames to which nondistributable artifacts can be
     * pushed, using the format `<hostname>[:<port>]` or `<IP address>[:<port>]`.
     *
     * Some images (for example, Windows base images) contain artifacts
     * whose distribution is restricted by license. When these images are
     * pushed to a registry, restricted artifacts are not included.
     *
     * This configuration override this behavior for the specified
     * registries.
     *
     * This option is useful when pushing images containing
     * nondistributable artifacts to a registry on an air-gapped network so
     * hosts on that network can pull the images without connecting to
     * another server.
     *
     * > **Warning**: Nondistributable artifacts typically have restrictions
     * > on how and where they can be distributed and shared. Only use this
     * > feature to push artifacts to private registries and ensure that you
     * > are in compliance with any terms that cover redistributing
     * > nondistributable artifacts.
     *
     * @return string[]|null
     */
    public function getAllowNondistributableArtifactsHostnames(): ?array
    {
        return $this->allowNondistributableArtifactsHostnames;
    }

    /**
     * Sets Allow Nondistributable Artifacts Hostnames.
     * List of registry hostnames to which nondistributable artifacts can be
     * pushed, using the format `<hostname>[:<port>]` or `<IP address>[:<port>]`.
     *
     * Some images (for example, Windows base images) contain artifacts
     * whose distribution is restricted by license. When these images are
     * pushed to a registry, restricted artifacts are not included.
     *
     * This configuration override this behavior for the specified
     * registries.
     *
     * This option is useful when pushing images containing
     * nondistributable artifacts to a registry on an air-gapped network so
     * hosts on that network can pull the images without connecting to
     * another server.
     *
     * > **Warning**: Nondistributable artifacts typically have restrictions
     * > on how and where they can be distributed and shared. Only use this
     * > feature to push artifacts to private registries and ensure that you
     * > are in compliance with any terms that cover redistributing
     * > nondistributable artifacts.
     *
     * @maps AllowNondistributableArtifactsHostnames
     *
     * @param string[]|null $allowNondistributableArtifactsHostnames
     */
    public function setAllowNondistributableArtifactsHostnames(?array $allowNondistributableArtifactsHostnames): void
    {
        $this->allowNondistributableArtifactsHostnames = $allowNondistributableArtifactsHostnames;
    }

    /**
     * Returns Index Configs.
     *
     * @return array<string,array|null|IndexInfo>|null
     */
    public function getIndexConfigs(): ?array
    {
        return $this->indexConfigs;
    }

    /**
     * Sets Index Configs.
     *
     * @maps IndexConfigs
     * @mapsBy anyOf(array<string,oneOf(anyOf(array,null),IndexInfo)>,null)
     *
     * @param array<string,array|null|IndexInfo>|null $indexConfigs
     */
    public function setIndexConfigs(?array $indexConfigs): void
    {
        $this->indexConfigs = $indexConfigs;
    }

    /**
     * Returns Insecure Registry CID Rs.
     * List of IP ranges of insecure registries, using the CIDR syntax
     * ([RFC 4632](https://tools.ietf.org/html/4632)). Insecure registries
     * accept un-encrypted (HTTP) and/or untrusted (HTTPS with certificates
     * from unknown CAs) communication.
     *
     * By default, local registries (`127.0.0.0/8`) are configured as
     * insecure. All other registries are secure. Communicating with an
     * insecure registry is not possible if the daemon assumes that registry
     * is secure.
     *
     * This configuration override this behavior, insecure communication with
     * registries whose resolved IP address is within the subnet described by
     * the CIDR syntax.
     *
     * Registries can also be marked insecure by hostname. Those registries
     * are listed under `IndexConfigs` and have their `Secure` field set to
     * `false`.
     *
     * > **Warning**: Using this option can be useful when running a local
     * > registry, but introduces security vulnerabilities. This option
     * > should therefore ONLY be used for testing purposes. For increased
     * > security, users should add their CA to their system's list of trusted
     * > CAs instead of enabling this option.
     *
     * @return string[]|null
     */
    public function getInsecureRegistryCIDRs(): ?array
    {
        return $this->insecureRegistryCIDRs;
    }

    /**
     * Sets Insecure Registry CID Rs.
     * List of IP ranges of insecure registries, using the CIDR syntax
     * ([RFC 4632](https://tools.ietf.org/html/4632)). Insecure registries
     * accept un-encrypted (HTTP) and/or untrusted (HTTPS with certificates
     * from unknown CAs) communication.
     *
     * By default, local registries (`127.0.0.0/8`) are configured as
     * insecure. All other registries are secure. Communicating with an
     * insecure registry is not possible if the daemon assumes that registry
     * is secure.
     *
     * This configuration override this behavior, insecure communication with
     * registries whose resolved IP address is within the subnet described by
     * the CIDR syntax.
     *
     * Registries can also be marked insecure by hostname. Those registries
     * are listed under `IndexConfigs` and have their `Secure` field set to
     * `false`.
     *
     * > **Warning**: Using this option can be useful when running a local
     * > registry, but introduces security vulnerabilities. This option
     * > should therefore ONLY be used for testing purposes. For increased
     * > security, users should add their CA to their system's list of trusted
     * > CAs instead of enabling this option.
     *
     * @maps InsecureRegistryCIDRs
     *
     * @param string[]|null $insecureRegistryCIDRs
     */
    public function setInsecureRegistryCIDRs(?array $insecureRegistryCIDRs): void
    {
        $this->insecureRegistryCIDRs = $insecureRegistryCIDRs;
    }

    /**
     * Returns Mirrors.
     * List of registry URLs that act as a mirror for the official
     * (`docker.io`) registry.
     *
     * @return string[]|null
     */
    public function getMirrors(): ?array
    {
        return $this->mirrors;
    }

    /**
     * Sets Mirrors.
     * List of registry URLs that act as a mirror for the official
     * (`docker.io`) registry.
     *
     * @maps Mirrors
     *
     * @param string[]|null $mirrors
     */
    public function setMirrors(?array $mirrors): void
    {
        $this->mirrors = $mirrors;
    }

    /**
     * Converts the RegistryServiceConfig object to a human-readable string representation.
     *
     * @return string The string representation of the RegistryServiceConfig object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RegistryServiceConfig',
            [
                'allowNondistributableArtifactsCIDRs' => $this->allowNondistributableArtifactsCIDRs,
                'allowNondistributableArtifactsHostnames' => $this->allowNondistributableArtifactsHostnames,
                'indexConfigs' => $this->indexConfigs,
                'insecureRegistryCIDRs' => $this->insecureRegistryCIDRs,
                'mirrors' => $this->mirrors
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->allowNondistributableArtifactsCIDRs)) {
            $json['AllowNondistributableArtifactsCIDRs']     = $this->allowNondistributableArtifactsCIDRs;
        }
        if (isset($this->allowNondistributableArtifactsHostnames)) {
            $json['AllowNondistributableArtifactsHostnames'] = $this->allowNondistributableArtifactsHostnames;
        }
        if (isset($this->indexConfigs)) {
            $json['IndexConfigs']                            =
                ApiHelper::getJsonHelper()->verifyTypes(
                    $this->indexConfigs,
                    'anyOf(array<string,oneOf(anyOf(array,null),IndexInfo)>,null)'
                );
        }
        if (isset($this->insecureRegistryCIDRs)) {
            $json['InsecureRegistryCIDRs']                   = $this->insecureRegistryCIDRs;
        }
        if (isset($this->mirrors)) {
            $json['Mirrors']                                 = $this->mirrors;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
