<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Reservation implements \JsonSerializable
{
    /**
     * @var GenericResource[]|null
     */
    private $genericResources;

    /**
     * @var int|null
     */
    private $memoryBytes;

    /**
     * @var int|null
     */
    private $nanoCPUs;

    /**
     * Returns Generic Resources.
     * User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g,
     * `GPU=UUID1`)
     *
     * @return GenericResource[]|null
     */
    public function getGenericResources(): ?array
    {
        return $this->genericResources;
    }

    /**
     * Sets Generic Resources.
     * User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g,
     * `GPU=UUID1`)
     *
     * @maps GenericResources
     *
     * @param GenericResource[]|null $genericResources
     */
    public function setGenericResources(?array $genericResources): void
    {
        $this->genericResources = $genericResources;
    }

    /**
     * Returns Memory Bytes.
     */
    public function getMemoryBytes(): ?int
    {
        return $this->memoryBytes;
    }

    /**
     * Sets Memory Bytes.
     *
     * @maps MemoryBytes
     */
    public function setMemoryBytes(?int $memoryBytes): void
    {
        $this->memoryBytes = $memoryBytes;
    }

    /**
     * Returns Nano CP Us.
     */
    public function getNanoCPUs(): ?int
    {
        return $this->nanoCPUs;
    }

    /**
     * Sets Nano CP Us.
     *
     * @maps NanoCPUs
     */
    public function setNanoCPUs(?int $nanoCPUs): void
    {
        $this->nanoCPUs = $nanoCPUs;
    }

    /**
     * Converts the Reservation object to a human-readable string representation.
     *
     * @return string The string representation of the Reservation object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Reservation',
            [
                'genericResources' => $this->genericResources,
                'memoryBytes' => $this->memoryBytes,
                'nanoCPUs' => $this->nanoCPUs
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->genericResources)) {
            $json['GenericResources'] = $this->genericResources;
        }
        if (isset($this->memoryBytes)) {
            $json['MemoryBytes']      = $this->memoryBytes;
        }
        if (isset($this->nanoCPUs)) {
            $json['NanoCPUs']         = $this->nanoCPUs;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
