<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * The behavior to apply when the container exits. The default is not to restart.
 *
 * An ever increasing delay (double the previous delay, starting at 100ms) is added before each restart
 * to prevent flooding the server.
 */
class RestartPolicy implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $maximumRetryCount;

    /**
     * @var string|null
     */
    private $name;

    /**
     * Returns Maximum Retry Count.
     * If `on-failure` is used, the number of times to retry before giving up
     */
    public function getMaximumRetryCount(): ?int
    {
        return $this->maximumRetryCount;
    }

    /**
     * Sets Maximum Retry Count.
     * If `on-failure` is used, the number of times to retry before giving up
     *
     * @maps MaximumRetryCount
     */
    public function setMaximumRetryCount(?int $maximumRetryCount): void
    {
        $this->maximumRetryCount = $maximumRetryCount;
    }

    /**
     * Returns Name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps Name
     * @factory \DockerLib\Models\NameEnum::checkValue
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Converts the RestartPolicy object to a human-readable string representation.
     *
     * @return string The string representation of the RestartPolicy object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RestartPolicy',
            ['maximumRetryCount' => $this->maximumRetryCount, 'name' => $this->name]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->maximumRetryCount)) {
            $json['MaximumRetryCount'] = $this->maximumRetryCount;
        }
        if (isset($this->name)) {
            $json['Name']              = NameEnum::checkValue($this->name);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
