<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * Runtime describes an [OCI compliant](https://github.com/opencontainers/runtime-spec)
 * runtime.
 *
 * The runtime is invoked by the daemon via the `containerd` daemon. OCI
 * runtimes act as an interface to the Linux kernel namespaces, cgroups,
 * and SELinux.
 */
class Runtime implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $path;

    /**
     * @var array
     */
    private $runtimeArgs = [];

    /**
     * Returns Path.
     * Name and, optional, path, of the OCI executable binary.
     *
     * If the path is omitted, the daemon searches the host's `$PATH` for the
     * binary and uses the first result.
     */
    public function getPath(): ?string
    {
        return $this->path;
    }

    /**
     * Sets Path.
     * Name and, optional, path, of the OCI executable binary.
     *
     * If the path is omitted, the daemon searches the host's `$PATH` for the
     * binary and uses the first result.
     *
     * @maps path
     */
    public function setPath(?string $path): void
    {
        $this->path = $path;
    }

    /**
     * Returns Runtime Args.
     * List of command-line arguments to pass to the runtime when invoked.
     *
     * @return string[]|null
     */
    public function getRuntimeArgs(): ?array
    {
        if (count($this->runtimeArgs) == 0) {
            return null;
        }
        return $this->runtimeArgs['value'];
    }

    /**
     * Sets Runtime Args.
     * List of command-line arguments to pass to the runtime when invoked.
     *
     * @maps runtimeArgs
     *
     * @param string[]|null $runtimeArgs
     */
    public function setRuntimeArgs(?array $runtimeArgs): void
    {
        $this->runtimeArgs['value'] = $runtimeArgs;
    }

    /**
     * Unsets Runtime Args.
     * List of command-line arguments to pass to the runtime when invoked.
     */
    public function unsetRuntimeArgs(): void
    {
        $this->runtimeArgs = [];
    }

    /**
     * Converts the Runtime object to a human-readable string representation.
     *
     * @return string The string representation of the Runtime object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Runtime', ['path' => $this->path, 'runtimeArgs' => $this->getRuntimeArgs()]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->path)) {
            $json['path']        = $this->path;
        }
        if (!empty($this->runtimeArgs)) {
            $json['runtimeArgs'] = $this->runtimeArgs['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
