<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ScimUser implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $active;

    /**
     * @var string|null
     */
    private $displayName;

    /**
     * @var ScimEmail[]|null
     */
    private $emails;

    /**
     * @var ScimGroup[]|null
     */
    private $groups;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var Meta|null
     */
    private $meta;

    /**
     * @var ScimUserName|null
     */
    private $name;

    /**
     * @var string[]|null
     */
    private $schemas;

    /**
     * @var string|null
     */
    private $userName;

    /**
     * Returns Active.
     */
    public function getActive(): ?bool
    {
        return $this->active;
    }

    /**
     * Sets Active.
     *
     * @maps active
     */
    public function setActive(?bool $active): void
    {
        $this->active = $active;
    }

    /**
     * Returns Display Name.
     * The username in Docker. Also known as the "Docker ID".
     */
    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    /**
     * Sets Display Name.
     * The username in Docker. Also known as the "Docker ID".
     *
     * @maps displayName
     */
    public function setDisplayName(?string $displayName): void
    {
        $this->displayName = $displayName;
    }

    /**
     * Returns Emails.
     *
     * @return ScimEmail[]|null
     */
    public function getEmails(): ?array
    {
        return $this->emails;
    }

    /**
     * Sets Emails.
     *
     * @maps emails
     *
     * @param ScimEmail[]|null $emails
     */
    public function setEmails(?array $emails): void
    {
        $this->emails = $emails;
    }

    /**
     * Returns Groups.
     *
     * @return ScimGroup[]|null
     */
    public function getGroups(): ?array
    {
        return $this->groups;
    }

    /**
     * Sets Groups.
     *
     * @maps groups
     *
     * @param ScimGroup[]|null $groups
     */
    public function setGroups(?array $groups): void
    {
        $this->groups = $groups;
    }

    /**
     * Returns Id.
     * The unique identifier for the user. A v4 UUID.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The unique identifier for the user. A v4 UUID.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Meta.
     */
    public function getMeta(): ?Meta
    {
        return $this->meta;
    }

    /**
     * Sets Meta.
     *
     * @maps meta
     */
    public function setMeta(?Meta $meta): void
    {
        $this->meta = $meta;
    }

    /**
     * Returns Name.
     */
    public function getName(): ?ScimUserName
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps name
     */
    public function setName(?ScimUserName $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Schemas.
     *
     * @return string[]|null
     */
    public function getSchemas(): ?array
    {
        return $this->schemas;
    }

    /**
     * Sets Schemas.
     *
     * @maps schemas
     *
     * @param string[]|null $schemas
     */
    public function setSchemas(?array $schemas): void
    {
        $this->schemas = $schemas;
    }

    /**
     * Returns User Name.
     * The user's email address. This must be reachable via email.
     */
    public function getUserName(): ?string
    {
        return $this->userName;
    }

    /**
     * Sets User Name.
     * The user's email address. This must be reachable via email.
     *
     * @maps userName
     */
    public function setUserName(?string $userName): void
    {
        $this->userName = $userName;
    }

    /**
     * Converts the ScimUser object to a human-readable string representation.
     *
     * @return string The string representation of the ScimUser object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ScimUser',
            [
                'active' => $this->active,
                'displayName' => $this->displayName,
                'emails' => $this->emails,
                'groups' => $this->groups,
                'id' => $this->id,
                'meta' => $this->meta,
                'name' => $this->name,
                'schemas' => $this->schemas,
                'userName' => $this->userName
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->active)) {
            $json['active']      = $this->active;
        }
        if (isset($this->displayName)) {
            $json['displayName'] = $this->displayName;
        }
        if (isset($this->emails)) {
            $json['emails']      = $this->emails;
        }
        if (isset($this->groups)) {
            $json['groups']      = $this->groups;
        }
        if (isset($this->id)) {
            $json['id']          = $this->id;
        }
        if (isset($this->meta)) {
            $json['meta']        = $this->meta;
        }
        if (isset($this->name)) {
            $json['name']        = $this->name;
        }
        if (isset($this->schemas)) {
            $json['schemas']     = $this->schemas;
        }
        if (isset($this->userName)) {
            $json['userName']    = $this->userName;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
