<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Secret1 implements \JsonSerializable
{
    /**
     * @var File1|null
     */
    private $file;

    /**
     * @var string|null
     */
    private $secretID;

    /**
     * @var string|null
     */
    private $secretName;

    /**
     * Returns File.
     */
    public function getFile(): ?File1
    {
        return $this->file;
    }

    /**
     * Sets File.
     *
     * @maps File
     */
    public function setFile(?File1 $file): void
    {
        $this->file = $file;
    }

    /**
     * Returns Secret ID.
     * SecretID represents the ID of the specific secret that we're referencing.
     */
    public function getSecretID(): ?string
    {
        return $this->secretID;
    }

    /**
     * Sets Secret ID.
     * SecretID represents the ID of the specific secret that we're referencing.
     *
     * @maps SecretID
     */
    public function setSecretID(?string $secretID): void
    {
        $this->secretID = $secretID;
    }

    /**
     * Returns Secret Name.
     * SecretName is the name of the secret that this references, but this is just provided for
     * lookup/display purposes. The secret in the reference will be identified by its ID.
     */
    public function getSecretName(): ?string
    {
        return $this->secretName;
    }

    /**
     * Sets Secret Name.
     * SecretName is the name of the secret that this references, but this is just provided for
     * lookup/display purposes. The secret in the reference will be identified by its ID.
     *
     * @maps SecretName
     */
    public function setSecretName(?string $secretName): void
    {
        $this->secretName = $secretName;
    }

    /**
     * Converts the Secret1 object to a human-readable string representation.
     *
     * @return string The string representation of the Secret1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Secret1',
            ['file' => $this->file, 'secretID' => $this->secretID, 'secretName' => $this->secretName]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->file)) {
            $json['File']       = $this->file;
        }
        if (isset($this->secretID)) {
            $json['SecretID']   = $this->secretID;
        }
        if (isset($this->secretName)) {
            $json['SecretName'] = $this->secretName;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
