<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * SELinux labels of the container
 */
class SELinuxContext implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $disable;

    /**
     * @var string|null
     */
    private $level;

    /**
     * @var string|null
     */
    private $role;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $user;

    /**
     * Returns Disable.
     * Disable SELinux
     */
    public function getDisable(): ?bool
    {
        return $this->disable;
    }

    /**
     * Sets Disable.
     * Disable SELinux
     *
     * @maps Disable
     */
    public function setDisable(?bool $disable): void
    {
        $this->disable = $disable;
    }

    /**
     * Returns Level.
     * SELinux level label
     */
    public function getLevel(): ?string
    {
        return $this->level;
    }

    /**
     * Sets Level.
     * SELinux level label
     *
     * @maps Level
     */
    public function setLevel(?string $level): void
    {
        $this->level = $level;
    }

    /**
     * Returns Role.
     * SELinux role label
     */
    public function getRole(): ?string
    {
        return $this->role;
    }

    /**
     * Sets Role.
     * SELinux role label
     *
     * @maps Role
     */
    public function setRole(?string $role): void
    {
        $this->role = $role;
    }

    /**
     * Returns Type.
     * SELinux type label
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * SELinux type label
     *
     * @maps Type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns User.
     * SELinux user label
     */
    public function getUser(): ?string
    {
        return $this->user;
    }

    /**
     * Sets User.
     * SELinux user label
     *
     * @maps User
     */
    public function setUser(?string $user): void
    {
        $this->user = $user;
    }

    /**
     * Converts the SELinuxContext object to a human-readable string representation.
     *
     * @return string The string representation of the SELinuxContext object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SELinuxContext',
            [
                'disable' => $this->disable,
                'level' => $this->level,
                'role' => $this->role,
                'type' => $this->type,
                'user' => $this->user
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->disable)) {
            $json['Disable'] = $this->disable;
        }
        if (isset($this->level)) {
            $json['Level']   = $this->level;
        }
        if (isset($this->role)) {
            $json['Role']    = $this->role;
        }
        if (isset($this->type)) {
            $json['Type']    = $this->type;
        }
        if (isset($this->user)) {
            $json['User']    = $this->user;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
