<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ServiceUpdateResponse implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $warnings;

    /**
     * Returns Warnings.
     * Optional warning messages
     *
     * @return string[]|null
     */
    public function getWarnings(): ?array
    {
        return $this->warnings;
    }

    /**
     * Sets Warnings.
     * Optional warning messages
     *
     * @maps Warnings
     *
     * @param string[]|null $warnings
     */
    public function setWarnings(?array $warnings): void
    {
        $this->warnings = $warnings;
    }

    /**
     * Converts the ServiceUpdateResponse object to a human-readable string representation.
     *
     * @return string The string representation of the ServiceUpdateResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ServiceUpdateResponse', ['warnings' => $this->warnings]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->warnings)) {
            $json['Warnings'] = $this->warnings;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
