<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

/**
 * User modifiable swarm configuration.
 */
class SwarmSpec implements \JsonSerializable
{
    /**
     * @var array|null
     */
    private $cAConfig;

    /**
     * @var array|null
     */
    private $dispatcher;

    /**
     * @var EncryptionConfig2|null
     */
    private $encryptionConfig;

    /**
     * @var array<string,string>|null
     */
    private $labels;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var array|null
     */
    private $orchestration;

    /**
     * @var Raft2|null
     */
    private $raft;

    /**
     * @var TaskDefaults2|null
     */
    private $taskDefaults;

    /**
     * Returns C a Config.
     */
    public function getCAConfig(): ?array
    {
        return $this->cAConfig;
    }

    /**
     * Sets C a Config.
     *
     * @maps CAConfig
     */
    public function setCAConfig(?array $cAConfig): void
    {
        $this->cAConfig = $cAConfig;
    }

    /**
     * Returns Dispatcher.
     */
    public function getDispatcher(): ?array
    {
        return $this->dispatcher;
    }

    /**
     * Sets Dispatcher.
     *
     * @maps Dispatcher
     */
    public function setDispatcher(?array $dispatcher): void
    {
        $this->dispatcher = $dispatcher;
    }

    /**
     * Returns Encryption Config.
     */
    public function getEncryptionConfig(): ?EncryptionConfig2
    {
        return $this->encryptionConfig;
    }

    /**
     * Sets Encryption Config.
     *
     * @maps EncryptionConfig
     */
    public function setEncryptionConfig(?EncryptionConfig2 $encryptionConfig): void
    {
        $this->encryptionConfig = $encryptionConfig;
    }

    /**
     * Returns Labels.
     * User-defined key/value metadata.
     *
     * @return array<string,string>|null
     */
    public function getLabels(): ?array
    {
        return $this->labels;
    }

    /**
     * Sets Labels.
     * User-defined key/value metadata.
     *
     * @maps Labels
     *
     * @param array<string,string>|null $labels
     */
    public function setLabels(?array $labels): void
    {
        $this->labels = $labels;
    }

    /**
     * Returns Name.
     * Name of the swarm.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Name of the swarm.
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Orchestration.
     */
    public function getOrchestration(): ?array
    {
        return $this->orchestration;
    }

    /**
     * Sets Orchestration.
     *
     * @maps Orchestration
     */
    public function setOrchestration(?array $orchestration): void
    {
        $this->orchestration = $orchestration;
    }

    /**
     * Returns Raft.
     */
    public function getRaft(): ?Raft2
    {
        return $this->raft;
    }

    /**
     * Sets Raft.
     *
     * @maps Raft
     */
    public function setRaft(?Raft2 $raft): void
    {
        $this->raft = $raft;
    }

    /**
     * Returns Task Defaults.
     */
    public function getTaskDefaults(): ?TaskDefaults2
    {
        return $this->taskDefaults;
    }

    /**
     * Sets Task Defaults.
     *
     * @maps TaskDefaults
     */
    public function setTaskDefaults(?TaskDefaults2 $taskDefaults): void
    {
        $this->taskDefaults = $taskDefaults;
    }

    /**
     * Converts the SwarmSpec object to a human-readable string representation.
     *
     * @return string The string representation of the SwarmSpec object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SwarmSpec',
            [
                'cAConfig' => $this->cAConfig,
                'dispatcher' => $this->dispatcher,
                'encryptionConfig' => $this->encryptionConfig,
                'labels' => $this->labels,
                'name' => $this->name,
                'orchestration' => $this->orchestration,
                'raft' => $this->raft,
                'taskDefaults' => $this->taskDefaults
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cAConfig)) {
            $json['CAConfig']         = $this->cAConfig;
        }
        if (isset($this->dispatcher)) {
            $json['Dispatcher']       = $this->dispatcher;
        }
        if (isset($this->encryptionConfig)) {
            $json['EncryptionConfig'] = $this->encryptionConfig;
        }
        if (isset($this->labels)) {
            $json['Labels']           = $this->labels;
        }
        if (isset($this->name)) {
            $json['Name']             = $this->name;
        }
        if (isset($this->orchestration)) {
            $json['Orchestration']    = $this->orchestration;
        }
        if (isset($this->raft)) {
            $json['Raft']             = $this->raft;
        }
        if (isset($this->taskDefaults)) {
            $json['TaskDefaults']     = $this->taskDefaults;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
