<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class SwarmUnlockRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $unlockKey;

    /**
     * Returns Unlock Key.
     * The swarm's unlock key.
     */
    public function getUnlockKey(): ?string
    {
        return $this->unlockKey;
    }

    /**
     * Sets Unlock Key.
     * The swarm's unlock key.
     *
     * @maps UnlockKey
     */
    public function setUnlockKey(?string $unlockKey): void
    {
        $this->unlockKey = $unlockKey;
    }

    /**
     * Converts the SwarmUnlockRequest object to a human-readable string representation.
     *
     * @return string The string representation of the SwarmUnlockRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('SwarmUnlockRequest', ['unlockKey' => $this->unlockKey]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->unlockKey)) {
            $json['UnlockKey'] = $this->unlockKey;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
