<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class SystemInfo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $architecture;

    /**
     * @var bool|null
     */
    private $bridgeNfIp6tables;

    /**
     * @var bool|null
     */
    private $bridgeNfIptables;

    /**
     * @var bool|null
     */
    private $cPUSet;

    /**
     * @var bool|null
     */
    private $cPUShares;

    /**
     * @var string|null
     */
    private $cgroupDriver;

    /**
     * @var string|null
     */
    private $clusterAdvertise;

    /**
     * @var string|null
     */
    private $clusterStore;

    /**
     * @var ContainerdCommit|null
     */
    private $containerdCommit;

    /**
     * @var int|null
     */
    private $containers;

    /**
     * @var int|null
     */
    private $containersPaused;

    /**
     * @var int|null
     */
    private $containersRunning;

    /**
     * @var int|null
     */
    private $containersStopped;

    /**
     * @var bool|null
     */
    private $cpuCfsPeriod;

    /**
     * @var bool|null
     */
    private $cpuCfsQuota;

    /**
     * @var bool|null
     */
    private $debug;

    /**
     * @var string|null
     */
    private $defaultRuntime = 'runc';

    /**
     * @var string|null
     */
    private $dockerRootDir;

    /**
     * @var string|null
     */
    private $driver;

    /**
     * @var string[][]|null
     */
    private $driverStatus;

    /**
     * @var bool|null
     */
    private $experimentalBuild;

    /**
     * @var GenericResource[]|null
     */
    private $genericResources;

    /**
     * @var string|null
     */
    private $httpProxy;

    /**
     * @var string|null
     */
    private $httpsProxy;

    /**
     * @var string|null
     */
    private $iD;

    /**
     * @var bool|null
     */
    private $iPv4Forwarding;

    /**
     * @var int|null
     */
    private $images;

    /**
     * @var string|null
     */
    private $indexServerAddress = 'https://index.docker.io/v1/';

    /**
     * @var string|null
     */
    private $initBinary;

    /**
     * @var InitCommit|null
     */
    private $initCommit;

    /**
     * @var string|null
     */
    private $isolation;

    /**
     * @var bool|null
     */
    private $kernelMemory;

    /**
     * @var string|null
     */
    private $kernelVersion;

    /**
     * @var string[]|null
     */
    private $labels;

    /**
     * @var bool|null
     */
    private $liveRestoreEnabled = false;

    /**
     * @var string|null
     */
    private $loggingDriver;

    /**
     * @var int|null
     */
    private $memTotal;

    /**
     * @var bool|null
     */
    private $memoryLimit;

    /**
     * @var int|null
     */
    private $nCPU;

    /**
     * @var int|null
     */
    private $nEventsListener;

    /**
     * @var int|null
     */
    private $nFd;

    /**
     * @var int|null
     */
    private $nGoroutines;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $noProxy;

    /**
     * @var string|null
     */
    private $oSType;

    /**
     * @var bool|null
     */
    private $oomKillDisable;

    /**
     * @var string|null
     */
    private $operatingSystem;

    /**
     * @var Plugins|null
     */
    private $plugins;

    /**
     * @var array|null
     */
    private $registryConfig;

    /**
     * @var RuncCommit|null
     */
    private $runcCommit;

    /**
     * @var array<string,Runtime>|null
     */
    private $runtimes;

    /**
     * @var string[]|null
     */
    private $securityOptions;

    /**
     * @var string|null
     */
    private $serverVersion;

    /**
     * @var bool|null
     */
    private $swapLimit;

    /**
     * @var Swarm1|null
     */
    private $swarm;

    /**
     * @var string[][]|null
     */
    private $systemStatus;

    /**
     * @var string|null
     */
    private $systemTime;

    /**
     * Returns Architecture.
     * Hardware architecture of the host, as returned by the Go runtime
     * (`GOARCH`).
     *
     * A full list of possible values can be found in the [Go documentation](https://golang.
     * org/doc/install/source#environment).
     */
    public function getArchitecture(): ?string
    {
        return $this->architecture;
    }

    /**
     * Sets Architecture.
     * Hardware architecture of the host, as returned by the Go runtime
     * (`GOARCH`).
     *
     * A full list of possible values can be found in the [Go documentation](https://golang.
     * org/doc/install/source#environment).
     *
     * @maps Architecture
     */
    public function setArchitecture(?string $architecture): void
    {
        $this->architecture = $architecture;
    }

    /**
     * Returns Bridge Nf Ip 6 Tables.
     * Indicates if `bridge-nf-call-ip6tables` is available on the host.
     */
    public function getBridgeNfIp6tables(): ?bool
    {
        return $this->bridgeNfIp6tables;
    }

    /**
     * Sets Bridge Nf Ip 6 Tables.
     * Indicates if `bridge-nf-call-ip6tables` is available on the host.
     *
     * @maps BridgeNfIp6tables
     */
    public function setBridgeNfIp6tables(?bool $bridgeNfIp6tables): void
    {
        $this->bridgeNfIp6tables = $bridgeNfIp6tables;
    }

    /**
     * Returns Bridge Nf Iptables.
     * Indicates if `bridge-nf-call-iptables` is available on the host.
     */
    public function getBridgeNfIptables(): ?bool
    {
        return $this->bridgeNfIptables;
    }

    /**
     * Sets Bridge Nf Iptables.
     * Indicates if `bridge-nf-call-iptables` is available on the host.
     *
     * @maps BridgeNfIptables
     */
    public function setBridgeNfIptables(?bool $bridgeNfIptables): void
    {
        $this->bridgeNfIptables = $bridgeNfIptables;
    }

    /**
     * Returns C PU Set.
     * Indicates if CPUsets (cpuset.cpus, cpuset.mems) are supported by the host.
     *
     * See [cpuset(7)](https://www.kernel.org/doc/Documentation/cgroup-v1/cpusets.txt)
     */
    public function getCPUSet(): ?bool
    {
        return $this->cPUSet;
    }

    /**
     * Sets C PU Set.
     * Indicates if CPUsets (cpuset.cpus, cpuset.mems) are supported by the host.
     *
     * See [cpuset(7)](https://www.kernel.org/doc/Documentation/cgroup-v1/cpusets.txt)
     *
     * @maps CPUSet
     */
    public function setCPUSet(?bool $cPUSet): void
    {
        $this->cPUSet = $cPUSet;
    }

    /**
     * Returns C PU Shares.
     * Indicates if CPU Shares limiting is supported by the host.
     */
    public function getCPUShares(): ?bool
    {
        return $this->cPUShares;
    }

    /**
     * Sets C PU Shares.
     * Indicates if CPU Shares limiting is supported by the host.
     *
     * @maps CPUShares
     */
    public function setCPUShares(?bool $cPUShares): void
    {
        $this->cPUShares = $cPUShares;
    }

    /**
     * Returns Cgroup Driver.
     */
    public function getCgroupDriver(): ?string
    {
        return $this->cgroupDriver;
    }

    /**
     * Sets Cgroup Driver.
     *
     * @maps CgroupDriver
     * @factory \DockerLib\Models\CgroupDriverEnum::checkValue
     */
    public function setCgroupDriver(?string $cgroupDriver): void
    {
        $this->cgroupDriver = $cgroupDriver;
    }

    /**
     * Returns Cluster Advertise.
     * The network endpoint that the Engine advertises for the purpose of
     * node discovery. ClusterAdvertise is a `host:port` combination on which
     * the daemon is reachable by other hosts.
     *
     * <p><br /></p>
     *
     * > **Note**: This field is only propagated when using standalone Swarm
     * > mode, and overlay networking using an external k/v store. Overlay
     * > networks with Swarm mode enabled use the built-in raft store, and
     * > this field will be empty.
     */
    public function getClusterAdvertise(): ?string
    {
        return $this->clusterAdvertise;
    }

    /**
     * Sets Cluster Advertise.
     * The network endpoint that the Engine advertises for the purpose of
     * node discovery. ClusterAdvertise is a `host:port` combination on which
     * the daemon is reachable by other hosts.
     *
     * <p><br /></p>
     *
     * > **Note**: This field is only propagated when using standalone Swarm
     * > mode, and overlay networking using an external k/v store. Overlay
     * > networks with Swarm mode enabled use the built-in raft store, and
     * > this field will be empty.
     *
     * @maps ClusterAdvertise
     */
    public function setClusterAdvertise(?string $clusterAdvertise): void
    {
        $this->clusterAdvertise = $clusterAdvertise;
    }

    /**
     * Returns Cluster Store.
     * URL of the distributed storage backend.
     *
     *
     * The storage backend is used for multihost networking (to store
     * network and endpoint information) and by the node discovery mechanism.
     *
     * <p><br /></p>
     *
     * > **Note**: This field is only propagated when using standalone Swarm
     * > mode, and overlay networking using an external k/v store. Overlay
     * > networks with Swarm mode enabled use the built-in raft store, and
     * > this field will be empty.
     */
    public function getClusterStore(): ?string
    {
        return $this->clusterStore;
    }

    /**
     * Sets Cluster Store.
     * URL of the distributed storage backend.
     *
     *
     * The storage backend is used for multihost networking (to store
     * network and endpoint information) and by the node discovery mechanism.
     *
     * <p><br /></p>
     *
     * > **Note**: This field is only propagated when using standalone Swarm
     * > mode, and overlay networking using an external k/v store. Overlay
     * > networks with Swarm mode enabled use the built-in raft store, and
     * > this field will be empty.
     *
     * @maps ClusterStore
     */
    public function setClusterStore(?string $clusterStore): void
    {
        $this->clusterStore = $clusterStore;
    }

    /**
     * Returns Containerd Commit.
     */
    public function getContainerdCommit(): ?ContainerdCommit
    {
        return $this->containerdCommit;
    }

    /**
     * Sets Containerd Commit.
     *
     * @maps ContainerdCommit
     */
    public function setContainerdCommit(?ContainerdCommit $containerdCommit): void
    {
        $this->containerdCommit = $containerdCommit;
    }

    /**
     * Returns Containers.
     * Total number of containers on the host.
     */
    public function getContainers(): ?int
    {
        return $this->containers;
    }

    /**
     * Sets Containers.
     * Total number of containers on the host.
     *
     * @maps Containers
     */
    public function setContainers(?int $containers): void
    {
        $this->containers = $containers;
    }

    /**
     * Returns Containers Paused.
     * Number of containers with status `"paused"`.
     */
    public function getContainersPaused(): ?int
    {
        return $this->containersPaused;
    }

    /**
     * Sets Containers Paused.
     * Number of containers with status `"paused"`.
     *
     * @maps ContainersPaused
     */
    public function setContainersPaused(?int $containersPaused): void
    {
        $this->containersPaused = $containersPaused;
    }

    /**
     * Returns Containers Running.
     * Number of containers with status `"running"`.
     */
    public function getContainersRunning(): ?int
    {
        return $this->containersRunning;
    }

    /**
     * Sets Containers Running.
     * Number of containers with status `"running"`.
     *
     * @maps ContainersRunning
     */
    public function setContainersRunning(?int $containersRunning): void
    {
        $this->containersRunning = $containersRunning;
    }

    /**
     * Returns Containers Stopped.
     * Number of containers with status `"stopped"`.
     */
    public function getContainersStopped(): ?int
    {
        return $this->containersStopped;
    }

    /**
     * Sets Containers Stopped.
     * Number of containers with status `"stopped"`.
     *
     * @maps ContainersStopped
     */
    public function setContainersStopped(?int $containersStopped): void
    {
        $this->containersStopped = $containersStopped;
    }

    /**
     * Returns Cpu Cfs Period.
     * Indicates if CPU CFS(Completely Fair Scheduler) period is supported by the host.
     */
    public function getCpuCfsPeriod(): ?bool
    {
        return $this->cpuCfsPeriod;
    }

    /**
     * Sets Cpu Cfs Period.
     * Indicates if CPU CFS(Completely Fair Scheduler) period is supported by the host.
     *
     * @maps CpuCfsPeriod
     */
    public function setCpuCfsPeriod(?bool $cpuCfsPeriod): void
    {
        $this->cpuCfsPeriod = $cpuCfsPeriod;
    }

    /**
     * Returns Cpu Cfs Quota.
     * Indicates if CPU CFS(Completely Fair Scheduler) quota is supported by the host.
     */
    public function getCpuCfsQuota(): ?bool
    {
        return $this->cpuCfsQuota;
    }

    /**
     * Sets Cpu Cfs Quota.
     * Indicates if CPU CFS(Completely Fair Scheduler) quota is supported by the host.
     *
     * @maps CpuCfsQuota
     */
    public function setCpuCfsQuota(?bool $cpuCfsQuota): void
    {
        $this->cpuCfsQuota = $cpuCfsQuota;
    }

    /**
     * Returns Debug.
     * Indicates if the daemon is running in debug-mode / with debug-level logging enabled.
     */
    public function getDebug(): ?bool
    {
        return $this->debug;
    }

    /**
     * Sets Debug.
     * Indicates if the daemon is running in debug-mode / with debug-level logging enabled.
     *
     * @maps Debug
     */
    public function setDebug(?bool $debug): void
    {
        $this->debug = $debug;
    }

    /**
     * Returns Default Runtime.
     * Name of the default OCI runtime that is used when starting containers.
     *
     * The default can be overridden per-container at create time.
     */
    public function getDefaultRuntime(): ?string
    {
        return $this->defaultRuntime;
    }

    /**
     * Sets Default Runtime.
     * Name of the default OCI runtime that is used when starting containers.
     *
     * The default can be overridden per-container at create time.
     *
     * @maps DefaultRuntime
     */
    public function setDefaultRuntime(?string $defaultRuntime): void
    {
        $this->defaultRuntime = $defaultRuntime;
    }

    /**
     * Returns Docker Root Dir.
     * Root directory of persistent Docker state.
     *
     * Defaults to `/var/lib/docker` on Linux, and `C:\ProgramData\docker`
     * on Windows.
     */
    public function getDockerRootDir(): ?string
    {
        return $this->dockerRootDir;
    }

    /**
     * Sets Docker Root Dir.
     * Root directory of persistent Docker state.
     *
     * Defaults to `/var/lib/docker` on Linux, and `C:\ProgramData\docker`
     * on Windows.
     *
     * @maps DockerRootDir
     */
    public function setDockerRootDir(?string $dockerRootDir): void
    {
        $this->dockerRootDir = $dockerRootDir;
    }

    /**
     * Returns Driver.
     * Name of the storage driver in use.
     */
    public function getDriver(): ?string
    {
        return $this->driver;
    }

    /**
     * Sets Driver.
     * Name of the storage driver in use.
     *
     * @maps Driver
     */
    public function setDriver(?string $driver): void
    {
        $this->driver = $driver;
    }

    /**
     * Returns Driver Status.
     * Information specific to the storage driver, provided as
     * "label" / "value" pairs.
     *
     * This information is provided by the storage driver, and formatted
     * in a way consistent with the output of `docker info` on the command
     * line.
     *
     * <p><br /></p>
     *
     * > **Note**: The information returned in this field, including the
     * > formatting of values and labels, should not be considered stable,
     * > and may change without notice.
     *
     * @return string[][]|null
     */
    public function getDriverStatus(): ?array
    {
        return $this->driverStatus;
    }

    /**
     * Sets Driver Status.
     * Information specific to the storage driver, provided as
     * "label" / "value" pairs.
     *
     * This information is provided by the storage driver, and formatted
     * in a way consistent with the output of `docker info` on the command
     * line.
     *
     * <p><br /></p>
     *
     * > **Note**: The information returned in this field, including the
     * > formatting of values and labels, should not be considered stable,
     * > and may change without notice.
     *
     * @maps DriverStatus
     *
     * @param string[][]|null $driverStatus
     */
    public function setDriverStatus(?array $driverStatus): void
    {
        $this->driverStatus = $driverStatus;
    }

    /**
     * Returns Experimental Build.
     * Indicates if experimental features are enabled on the daemon.
     */
    public function getExperimentalBuild(): ?bool
    {
        return $this->experimentalBuild;
    }

    /**
     * Sets Experimental Build.
     * Indicates if experimental features are enabled on the daemon.
     *
     * @maps ExperimentalBuild
     */
    public function setExperimentalBuild(?bool $experimentalBuild): void
    {
        $this->experimentalBuild = $experimentalBuild;
    }

    /**
     * Returns Generic Resources.
     * User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g,
     * `GPU=UUID1`)
     *
     * @return GenericResource[]|null
     */
    public function getGenericResources(): ?array
    {
        return $this->genericResources;
    }

    /**
     * Sets Generic Resources.
     * User-defined resources can be either Integer resources (e.g, `SSD=3`) or String resources (e.g,
     * `GPU=UUID1`)
     *
     * @maps GenericResources
     *
     * @param GenericResource[]|null $genericResources
     */
    public function setGenericResources(?array $genericResources): void
    {
        $this->genericResources = $genericResources;
    }

    /**
     * Returns Http Proxy.
     * HTTP-proxy configured for the daemon. This value is obtained from the
     * [`HTTP_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable.
     *
     * Containers do not automatically inherit this configuration.
     */
    public function getHttpProxy(): ?string
    {
        return $this->httpProxy;
    }

    /**
     * Sets Http Proxy.
     * HTTP-proxy configured for the daemon. This value is obtained from the
     * [`HTTP_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable.
     *
     * Containers do not automatically inherit this configuration.
     *
     * @maps HttpProxy
     */
    public function setHttpProxy(?string $httpProxy): void
    {
        $this->httpProxy = $httpProxy;
    }

    /**
     * Returns Https Proxy.
     * HTTPS-proxy configured for the daemon. This value is obtained from the
     * [`HTTPS_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment
     * variable.
     *
     * Containers do not automatically inherit this configuration.
     */
    public function getHttpsProxy(): ?string
    {
        return $this->httpsProxy;
    }

    /**
     * Sets Https Proxy.
     * HTTPS-proxy configured for the daemon. This value is obtained from the
     * [`HTTPS_PROXY`](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment
     * variable.
     *
     * Containers do not automatically inherit this configuration.
     *
     * @maps HttpsProxy
     */
    public function setHttpsProxy(?string $httpsProxy): void
    {
        $this->httpsProxy = $httpsProxy;
    }

    /**
     * Returns I D.
     * Unique identifier of the daemon.
     *
     * <p><br /></p>
     *
     * > **Note**: The format of the ID itself is not part of the API, and
     * > should not be considered stable.
     */
    public function getID(): ?string
    {
        return $this->iD;
    }

    /**
     * Sets I D.
     * Unique identifier of the daemon.
     *
     * <p><br /></p>
     *
     * > **Note**: The format of the ID itself is not part of the API, and
     * > should not be considered stable.
     *
     * @maps ID
     */
    public function setID(?string $iD): void
    {
        $this->iD = $iD;
    }

    /**
     * Returns I Pv 4 Forwarding.
     * Indicates IPv4 forwarding is enabled.
     */
    public function getIPv4Forwarding(): ?bool
    {
        return $this->iPv4Forwarding;
    }

    /**
     * Sets I Pv 4 Forwarding.
     * Indicates IPv4 forwarding is enabled.
     *
     * @maps IPv4Forwarding
     */
    public function setIPv4Forwarding(?bool $iPv4Forwarding): void
    {
        $this->iPv4Forwarding = $iPv4Forwarding;
    }

    /**
     * Returns Images.
     * Total number of images on the host.
     *
     * Both _tagged_ and _untagged_ (dangling) images are counted.
     */
    public function getImages(): ?int
    {
        return $this->images;
    }

    /**
     * Sets Images.
     * Total number of images on the host.
     *
     * Both _tagged_ and _untagged_ (dangling) images are counted.
     *
     * @maps Images
     */
    public function setImages(?int $images): void
    {
        $this->images = $images;
    }

    /**
     * Returns Index Server Address.
     * Address / URL of the index server that is used for image search,
     * and as a default for user authentication for Docker Hub and Docker Cloud.
     */
    public function getIndexServerAddress(): ?string
    {
        return $this->indexServerAddress;
    }

    /**
     * Sets Index Server Address.
     * Address / URL of the index server that is used for image search,
     * and as a default for user authentication for Docker Hub and Docker Cloud.
     *
     * @maps IndexServerAddress
     */
    public function setIndexServerAddress(?string $indexServerAddress): void
    {
        $this->indexServerAddress = $indexServerAddress;
    }

    /**
     * Returns Init Binary.
     * Name and, optional, path of the the `docker-init` binary.
     *
     * If the path is omitted, the daemon searches the host's `$PATH` for the
     * binary and uses the first result.
     */
    public function getInitBinary(): ?string
    {
        return $this->initBinary;
    }

    /**
     * Sets Init Binary.
     * Name and, optional, path of the the `docker-init` binary.
     *
     * If the path is omitted, the daemon searches the host's `$PATH` for the
     * binary and uses the first result.
     *
     * @maps InitBinary
     */
    public function setInitBinary(?string $initBinary): void
    {
        $this->initBinary = $initBinary;
    }

    /**
     * Returns Init Commit.
     */
    public function getInitCommit(): ?InitCommit
    {
        return $this->initCommit;
    }

    /**
     * Sets Init Commit.
     *
     * @maps InitCommit
     */
    public function setInitCommit(?InitCommit $initCommit): void
    {
        $this->initCommit = $initCommit;
    }

    /**
     * Returns Isolation.
     */
    public function getIsolation(): ?string
    {
        return $this->isolation;
    }

    /**
     * Sets Isolation.
     *
     * @maps Isolation
     * @factory \DockerLib\Models\Isolation1Enum::checkValue
     */
    public function setIsolation(?string $isolation): void
    {
        $this->isolation = $isolation;
    }

    /**
     * Returns Kernel Memory.
     * Indicates if the host has kernel memory limit support enabled.
     */
    public function getKernelMemory(): ?bool
    {
        return $this->kernelMemory;
    }

    /**
     * Sets Kernel Memory.
     * Indicates if the host has kernel memory limit support enabled.
     *
     * @maps KernelMemory
     */
    public function setKernelMemory(?bool $kernelMemory): void
    {
        $this->kernelMemory = $kernelMemory;
    }

    /**
     * Returns Kernel Version.
     * Kernel version of the host.
     *
     * On Linux, this information obtained from `uname`. On Windows this
     * information is queried from the <kbd>HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows
     * NT\\CurrentVersion\\</kbd>
     * registry value, for example _"10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)"_.
     */
    public function getKernelVersion(): ?string
    {
        return $this->kernelVersion;
    }

    /**
     * Sets Kernel Version.
     * Kernel version of the host.
     *
     * On Linux, this information obtained from `uname`. On Windows this
     * information is queried from the <kbd>HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows
     * NT\\CurrentVersion\\</kbd>
     * registry value, for example _"10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)"_.
     *
     * @maps KernelVersion
     */
    public function setKernelVersion(?string $kernelVersion): void
    {
        $this->kernelVersion = $kernelVersion;
    }

    /**
     * Returns Labels.
     * User-defined labels (key/value metadata) as set on the daemon.
     *
     * <p><br /></p>
     *
     * > **Note**: When part of a Swarm, nodes can both have _daemon_ labels,
     * > set through the daemon configuration, and _node_ labels, set from a
     * > manager node in the Swarm. Node labels are not included in this
     * > field. Node labels can be retrieved using the `/nodes/(id)` endpoint
     * > on a manager node in the Swarm.
     *
     * @return string[]|null
     */
    public function getLabels(): ?array
    {
        return $this->labels;
    }

    /**
     * Sets Labels.
     * User-defined labels (key/value metadata) as set on the daemon.
     *
     * <p><br /></p>
     *
     * > **Note**: When part of a Swarm, nodes can both have _daemon_ labels,
     * > set through the daemon configuration, and _node_ labels, set from a
     * > manager node in the Swarm. Node labels are not included in this
     * > field. Node labels can be retrieved using the `/nodes/(id)` endpoint
     * > on a manager node in the Swarm.
     *
     * @maps Labels
     *
     * @param string[]|null $labels
     */
    public function setLabels(?array $labels): void
    {
        $this->labels = $labels;
    }

    /**
     * Returns Live Restore Enabled.
     * Indicates if live restore is enabled.
     *
     * If enabled, containers are kept running when the daemon is shutdown
     * or upon daemon start if running containers are detected.
     */
    public function getLiveRestoreEnabled(): ?bool
    {
        return $this->liveRestoreEnabled;
    }

    /**
     * Sets Live Restore Enabled.
     * Indicates if live restore is enabled.
     *
     * If enabled, containers are kept running when the daemon is shutdown
     * or upon daemon start if running containers are detected.
     *
     * @maps LiveRestoreEnabled
     */
    public function setLiveRestoreEnabled(?bool $liveRestoreEnabled): void
    {
        $this->liveRestoreEnabled = $liveRestoreEnabled;
    }

    /**
     * Returns Logging Driver.
     * The logging driver to use as a default for new containers.
     */
    public function getLoggingDriver(): ?string
    {
        return $this->loggingDriver;
    }

    /**
     * Sets Logging Driver.
     * The logging driver to use as a default for new containers.
     *
     * @maps LoggingDriver
     */
    public function setLoggingDriver(?string $loggingDriver): void
    {
        $this->loggingDriver = $loggingDriver;
    }

    /**
     * Returns Mem Total.
     * Total amount of physical memory available on the host, in kilobytes (kB).
     */
    public function getMemTotal(): ?int
    {
        return $this->memTotal;
    }

    /**
     * Sets Mem Total.
     * Total amount of physical memory available on the host, in kilobytes (kB).
     *
     * @maps MemTotal
     */
    public function setMemTotal(?int $memTotal): void
    {
        $this->memTotal = $memTotal;
    }

    /**
     * Returns Memory Limit.
     * Indicates if the host has memory limit support enabled.
     */
    public function getMemoryLimit(): ?bool
    {
        return $this->memoryLimit;
    }

    /**
     * Sets Memory Limit.
     * Indicates if the host has memory limit support enabled.
     *
     * @maps MemoryLimit
     */
    public function setMemoryLimit(?bool $memoryLimit): void
    {
        $this->memoryLimit = $memoryLimit;
    }

    /**
     * Returns N CPU.
     * The number of logical CPUs usable by the daemon.
     *
     * The number of available CPUs is checked by querying the operating
     * system when the daemon starts. Changes to operating system CPU
     * allocation after the daemon is started are not reflected.
     */
    public function getNCPU(): ?int
    {
        return $this->nCPU;
    }

    /**
     * Sets N CPU.
     * The number of logical CPUs usable by the daemon.
     *
     * The number of available CPUs is checked by querying the operating
     * system when the daemon starts. Changes to operating system CPU
     * allocation after the daemon is started are not reflected.
     *
     * @maps NCPU
     */
    public function setNCPU(?int $nCPU): void
    {
        $this->nCPU = $nCPU;
    }

    /**
     * Returns N Events Listener.
     * Number of event listeners subscribed.
     */
    public function getNEventsListener(): ?int
    {
        return $this->nEventsListener;
    }

    /**
     * Sets N Events Listener.
     * Number of event listeners subscribed.
     *
     * @maps NEventsListener
     */
    public function setNEventsListener(?int $nEventsListener): void
    {
        $this->nEventsListener = $nEventsListener;
    }

    /**
     * Returns N Fd.
     * The total number of file Descriptors in use by the daemon process.
     *
     * This information is only returned if debug-mode is enabled.
     */
    public function getNFd(): ?int
    {
        return $this->nFd;
    }

    /**
     * Sets N Fd.
     * The total number of file Descriptors in use by the daemon process.
     *
     * This information is only returned if debug-mode is enabled.
     *
     * @maps NFd
     */
    public function setNFd(?int $nFd): void
    {
        $this->nFd = $nFd;
    }

    /**
     * Returns N Goroutines.
     * The  number of goroutines that currently exist.
     *
     * This information is only returned if debug-mode is enabled.
     */
    public function getNGoroutines(): ?int
    {
        return $this->nGoroutines;
    }

    /**
     * Sets N Goroutines.
     * The  number of goroutines that currently exist.
     *
     * This information is only returned if debug-mode is enabled.
     *
     * @maps NGoroutines
     */
    public function setNGoroutines(?int $nGoroutines): void
    {
        $this->nGoroutines = $nGoroutines;
    }

    /**
     * Returns Name.
     * Hostname of the host.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Hostname of the host.
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns No Proxy.
     * Comma-separated list of domain extensions for which no proxy should be
     * used. This value is obtained from the [`NO_PROXY`](https://www.gnu.
     * org/software/wget/manual/html_node/Proxies.html)
     * environment variable.
     *
     * Containers do not automatically inherit this configuration.
     */
    public function getNoProxy(): ?string
    {
        return $this->noProxy;
    }

    /**
     * Sets No Proxy.
     * Comma-separated list of domain extensions for which no proxy should be
     * used. This value is obtained from the [`NO_PROXY`](https://www.gnu.
     * org/software/wget/manual/html_node/Proxies.html)
     * environment variable.
     *
     * Containers do not automatically inherit this configuration.
     *
     * @maps NoProxy
     */
    public function setNoProxy(?string $noProxy): void
    {
        $this->noProxy = $noProxy;
    }

    /**
     * Returns O S Type.
     * Generic type of the operating system of the host, as returned by the
     * Go runtime (`GOOS`).
     *
     * Currently returned values are "linux" and "windows". A full list of
     * possible values can be found in the [Go documentation](https://golang.
     * org/doc/install/source#environment).
     */
    public function getOSType(): ?string
    {
        return $this->oSType;
    }

    /**
     * Sets O S Type.
     * Generic type of the operating system of the host, as returned by the
     * Go runtime (`GOOS`).
     *
     * Currently returned values are "linux" and "windows". A full list of
     * possible values can be found in the [Go documentation](https://golang.
     * org/doc/install/source#environment).
     *
     * @maps OSType
     */
    public function setOSType(?string $oSType): void
    {
        $this->oSType = $oSType;
    }

    /**
     * Returns Oom Kill Disable.
     * Indicates if OOM killer disable is supported on the host.
     */
    public function getOomKillDisable(): ?bool
    {
        return $this->oomKillDisable;
    }

    /**
     * Sets Oom Kill Disable.
     * Indicates if OOM killer disable is supported on the host.
     *
     * @maps OomKillDisable
     */
    public function setOomKillDisable(?bool $oomKillDisable): void
    {
        $this->oomKillDisable = $oomKillDisable;
    }

    /**
     * Returns Operating System.
     * Name of the host's operating system, for example: "Ubuntu 16.04.2 LTS"
     * or "Windows Server 2016 Datacenter"
     */
    public function getOperatingSystem(): ?string
    {
        return $this->operatingSystem;
    }

    /**
     * Sets Operating System.
     * Name of the host's operating system, for example: "Ubuntu 16.04.2 LTS"
     * or "Windows Server 2016 Datacenter"
     *
     * @maps OperatingSystem
     */
    public function setOperatingSystem(?string $operatingSystem): void
    {
        $this->operatingSystem = $operatingSystem;
    }

    /**
     * Returns Plugins.
     */
    public function getPlugins(): ?Plugins
    {
        return $this->plugins;
    }

    /**
     * Sets Plugins.
     *
     * @maps Plugins
     */
    public function setPlugins(?Plugins $plugins): void
    {
        $this->plugins = $plugins;
    }

    /**
     * Returns Registry Config.
     */
    public function getRegistryConfig(): ?array
    {
        return $this->registryConfig;
    }

    /**
     * Sets Registry Config.
     *
     * @maps RegistryConfig
     */
    public function setRegistryConfig(?array $registryConfig): void
    {
        $this->registryConfig = $registryConfig;
    }

    /**
     * Returns Runc Commit.
     */
    public function getRuncCommit(): ?RuncCommit
    {
        return $this->runcCommit;
    }

    /**
     * Sets Runc Commit.
     *
     * @maps RuncCommit
     */
    public function setRuncCommit(?RuncCommit $runcCommit): void
    {
        $this->runcCommit = $runcCommit;
    }

    /**
     * Returns Runtimes.
     * List of [OCI compliant](https://github.com/opencontainers/runtime-spec)
     * runtimes configured on the daemon. Keys hold the "name" used to
     * reference the runtime.
     *
     * The Docker daemon relies on an OCI compliant runtime (invoked via the
     * `containerd` daemon) as its interface to the Linux kernel namespaces,
     * cgroups, and SELinux.
     *
     * The default runtime is `runc`, and automatically configured. Additional
     * runtimes can be configured by the user and will be listed here.
     *
     * @return array<string,Runtime>|null
     */
    public function getRuntimes(): ?array
    {
        return $this->runtimes;
    }

    /**
     * Sets Runtimes.
     * List of [OCI compliant](https://github.com/opencontainers/runtime-spec)
     * runtimes configured on the daemon. Keys hold the "name" used to
     * reference the runtime.
     *
     * The Docker daemon relies on an OCI compliant runtime (invoked via the
     * `containerd` daemon) as its interface to the Linux kernel namespaces,
     * cgroups, and SELinux.
     *
     * The default runtime is `runc`, and automatically configured. Additional
     * runtimes can be configured by the user and will be listed here.
     *
     * @maps Runtimes
     *
     * @param array<string,Runtime>|null $runtimes
     */
    public function setRuntimes(?array $runtimes): void
    {
        $this->runtimes = $runtimes;
    }

    /**
     * Returns Security Options.
     * List of security features that are enabled on the daemon, such as
     * apparmor, seccomp, SELinux, and user-namespaces (userns).
     *
     * Additional configuration options for each security feature may
     * be present, and are included as a comma-separated list of key/value
     * pairs.
     *
     * @return string[]|null
     */
    public function getSecurityOptions(): ?array
    {
        return $this->securityOptions;
    }

    /**
     * Sets Security Options.
     * List of security features that are enabled on the daemon, such as
     * apparmor, seccomp, SELinux, and user-namespaces (userns).
     *
     * Additional configuration options for each security feature may
     * be present, and are included as a comma-separated list of key/value
     * pairs.
     *
     * @maps SecurityOptions
     *
     * @param string[]|null $securityOptions
     */
    public function setSecurityOptions(?array $securityOptions): void
    {
        $this->securityOptions = $securityOptions;
    }

    /**
     * Returns Server Version.
     * Version string of the daemon.
     *
     * > **Note**: the [standalone Swarm API](https://docs.docker.com/swarm/swarm-api/)
     * > returns the Swarm version instead of the daemon  version, for example
     * > `swarm/1.2.8`.
     */
    public function getServerVersion(): ?string
    {
        return $this->serverVersion;
    }

    /**
     * Sets Server Version.
     * Version string of the daemon.
     *
     * > **Note**: the [standalone Swarm API](https://docs.docker.com/swarm/swarm-api/)
     * > returns the Swarm version instead of the daemon  version, for example
     * > `swarm/1.2.8`.
     *
     * @maps ServerVersion
     */
    public function setServerVersion(?string $serverVersion): void
    {
        $this->serverVersion = $serverVersion;
    }

    /**
     * Returns Swap Limit.
     * Indicates if the host has memory swap limit support enabled.
     */
    public function getSwapLimit(): ?bool
    {
        return $this->swapLimit;
    }

    /**
     * Sets Swap Limit.
     * Indicates if the host has memory swap limit support enabled.
     *
     * @maps SwapLimit
     */
    public function setSwapLimit(?bool $swapLimit): void
    {
        $this->swapLimit = $swapLimit;
    }

    /**
     * Returns Swarm.
     */
    public function getSwarm(): ?Swarm1
    {
        return $this->swarm;
    }

    /**
     * Sets Swarm.
     *
     * @maps Swarm
     */
    public function setSwarm(?Swarm1 $swarm): void
    {
        $this->swarm = $swarm;
    }

    /**
     * Returns System Status.
     * Status information about this node (standalone Swarm API).
     *
     * <p><br /></p>
     *
     * > **Note**: The information returned in this field is only propagated
     * > by the Swarm standalone API, and is empty (`null`) when using
     * > built-in swarm mode.
     *
     * @return string[][]|null
     */
    public function getSystemStatus(): ?array
    {
        return $this->systemStatus;
    }

    /**
     * Sets System Status.
     * Status information about this node (standalone Swarm API).
     *
     * <p><br /></p>
     *
     * > **Note**: The information returned in this field is only propagated
     * > by the Swarm standalone API, and is empty (`null`) when using
     * > built-in swarm mode.
     *
     * @maps SystemStatus
     *
     * @param string[][]|null $systemStatus
     */
    public function setSystemStatus(?array $systemStatus): void
    {
        $this->systemStatus = $systemStatus;
    }

    /**
     * Returns System Time.
     * Current system-time in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt)
     * format with nano-seconds.
     */
    public function getSystemTime(): ?string
    {
        return $this->systemTime;
    }

    /**
     * Sets System Time.
     * Current system-time in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt)
     * format with nano-seconds.
     *
     * @maps SystemTime
     */
    public function setSystemTime(?string $systemTime): void
    {
        $this->systemTime = $systemTime;
    }

    /**
     * Converts the SystemInfo object to a human-readable string representation.
     *
     * @return string The string representation of the SystemInfo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SystemInfo',
            [
                'architecture' => $this->architecture,
                'bridgeNfIp6tables' => $this->bridgeNfIp6tables,
                'bridgeNfIptables' => $this->bridgeNfIptables,
                'cPUSet' => $this->cPUSet,
                'cPUShares' => $this->cPUShares,
                'cgroupDriver' => $this->cgroupDriver,
                'clusterAdvertise' => $this->clusterAdvertise,
                'clusterStore' => $this->clusterStore,
                'containerdCommit' => $this->containerdCommit,
                'containers' => $this->containers,
                'containersPaused' => $this->containersPaused,
                'containersRunning' => $this->containersRunning,
                'containersStopped' => $this->containersStopped,
                'cpuCfsPeriod' => $this->cpuCfsPeriod,
                'cpuCfsQuota' => $this->cpuCfsQuota,
                'debug' => $this->debug,
                'defaultRuntime' => $this->defaultRuntime,
                'dockerRootDir' => $this->dockerRootDir,
                'driver' => $this->driver,
                'driverStatus' => $this->driverStatus,
                'experimentalBuild' => $this->experimentalBuild,
                'genericResources' => $this->genericResources,
                'httpProxy' => $this->httpProxy,
                'httpsProxy' => $this->httpsProxy,
                'iD' => $this->iD,
                'iPv4Forwarding' => $this->iPv4Forwarding,
                'images' => $this->images,
                'indexServerAddress' => $this->indexServerAddress,
                'initBinary' => $this->initBinary,
                'initCommit' => $this->initCommit,
                'isolation' => $this->isolation,
                'kernelMemory' => $this->kernelMemory,
                'kernelVersion' => $this->kernelVersion,
                'labels' => $this->labels,
                'liveRestoreEnabled' => $this->liveRestoreEnabled,
                'loggingDriver' => $this->loggingDriver,
                'memTotal' => $this->memTotal,
                'memoryLimit' => $this->memoryLimit,
                'nCPU' => $this->nCPU,
                'nEventsListener' => $this->nEventsListener,
                'nFd' => $this->nFd,
                'nGoroutines' => $this->nGoroutines,
                'name' => $this->name,
                'noProxy' => $this->noProxy,
                'oSType' => $this->oSType,
                'oomKillDisable' => $this->oomKillDisable,
                'operatingSystem' => $this->operatingSystem,
                'plugins' => $this->plugins,
                'registryConfig' => $this->registryConfig,
                'runcCommit' => $this->runcCommit,
                'runtimes' => $this->runtimes,
                'securityOptions' => $this->securityOptions,
                'serverVersion' => $this->serverVersion,
                'swapLimit' => $this->swapLimit,
                'swarm' => $this->swarm,
                'systemStatus' => $this->systemStatus,
                'systemTime' => $this->systemTime
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->architecture)) {
            $json['Architecture']       = $this->architecture;
        }
        if (isset($this->bridgeNfIp6tables)) {
            $json['BridgeNfIp6tables']  = $this->bridgeNfIp6tables;
        }
        if (isset($this->bridgeNfIptables)) {
            $json['BridgeNfIptables']   = $this->bridgeNfIptables;
        }
        if (isset($this->cPUSet)) {
            $json['CPUSet']             = $this->cPUSet;
        }
        if (isset($this->cPUShares)) {
            $json['CPUShares']          = $this->cPUShares;
        }
        if (isset($this->cgroupDriver)) {
            $json['CgroupDriver']       = CgroupDriverEnum::checkValue($this->cgroupDriver);
        }
        if (isset($this->clusterAdvertise)) {
            $json['ClusterAdvertise']   = $this->clusterAdvertise;
        }
        if (isset($this->clusterStore)) {
            $json['ClusterStore']       = $this->clusterStore;
        }
        if (isset($this->containerdCommit)) {
            $json['ContainerdCommit']   = $this->containerdCommit;
        }
        if (isset($this->containers)) {
            $json['Containers']         = $this->containers;
        }
        if (isset($this->containersPaused)) {
            $json['ContainersPaused']   = $this->containersPaused;
        }
        if (isset($this->containersRunning)) {
            $json['ContainersRunning']  = $this->containersRunning;
        }
        if (isset($this->containersStopped)) {
            $json['ContainersStopped']  = $this->containersStopped;
        }
        if (isset($this->cpuCfsPeriod)) {
            $json['CpuCfsPeriod']       = $this->cpuCfsPeriod;
        }
        if (isset($this->cpuCfsQuota)) {
            $json['CpuCfsQuota']        = $this->cpuCfsQuota;
        }
        if (isset($this->debug)) {
            $json['Debug']              = $this->debug;
        }
        if (isset($this->defaultRuntime)) {
            $json['DefaultRuntime']     = $this->defaultRuntime;
        }
        if (isset($this->dockerRootDir)) {
            $json['DockerRootDir']      = $this->dockerRootDir;
        }
        if (isset($this->driver)) {
            $json['Driver']             = $this->driver;
        }
        if (isset($this->driverStatus)) {
            $json['DriverStatus']       = $this->driverStatus;
        }
        if (isset($this->experimentalBuild)) {
            $json['ExperimentalBuild']  = $this->experimentalBuild;
        }
        if (isset($this->genericResources)) {
            $json['GenericResources']   = $this->genericResources;
        }
        if (isset($this->httpProxy)) {
            $json['HttpProxy']          = $this->httpProxy;
        }
        if (isset($this->httpsProxy)) {
            $json['HttpsProxy']         = $this->httpsProxy;
        }
        if (isset($this->iD)) {
            $json['ID']                 = $this->iD;
        }
        if (isset($this->iPv4Forwarding)) {
            $json['IPv4Forwarding']     = $this->iPv4Forwarding;
        }
        if (isset($this->images)) {
            $json['Images']             = $this->images;
        }
        if (isset($this->indexServerAddress)) {
            $json['IndexServerAddress'] = $this->indexServerAddress;
        }
        if (isset($this->initBinary)) {
            $json['InitBinary']         = $this->initBinary;
        }
        if (isset($this->initCommit)) {
            $json['InitCommit']         = $this->initCommit;
        }
        if (isset($this->isolation)) {
            $json['Isolation']          = Isolation1Enum::checkValue($this->isolation);
        }
        if (isset($this->kernelMemory)) {
            $json['KernelMemory']       = $this->kernelMemory;
        }
        if (isset($this->kernelVersion)) {
            $json['KernelVersion']      = $this->kernelVersion;
        }
        if (isset($this->labels)) {
            $json['Labels']             = $this->labels;
        }
        if (isset($this->liveRestoreEnabled)) {
            $json['LiveRestoreEnabled'] = $this->liveRestoreEnabled;
        }
        if (isset($this->loggingDriver)) {
            $json['LoggingDriver']      = $this->loggingDriver;
        }
        if (isset($this->memTotal)) {
            $json['MemTotal']           = $this->memTotal;
        }
        if (isset($this->memoryLimit)) {
            $json['MemoryLimit']        = $this->memoryLimit;
        }
        if (isset($this->nCPU)) {
            $json['NCPU']               = $this->nCPU;
        }
        if (isset($this->nEventsListener)) {
            $json['NEventsListener']    = $this->nEventsListener;
        }
        if (isset($this->nFd)) {
            $json['NFd']                = $this->nFd;
        }
        if (isset($this->nGoroutines)) {
            $json['NGoroutines']        = $this->nGoroutines;
        }
        if (isset($this->name)) {
            $json['Name']               = $this->name;
        }
        if (isset($this->noProxy)) {
            $json['NoProxy']            = $this->noProxy;
        }
        if (isset($this->oSType)) {
            $json['OSType']             = $this->oSType;
        }
        if (isset($this->oomKillDisable)) {
            $json['OomKillDisable']     = $this->oomKillDisable;
        }
        if (isset($this->operatingSystem)) {
            $json['OperatingSystem']    = $this->operatingSystem;
        }
        if (isset($this->plugins)) {
            $json['Plugins']            = $this->plugins;
        }
        if (isset($this->registryConfig)) {
            $json['RegistryConfig']     = $this->registryConfig;
        }
        if (isset($this->runcCommit)) {
            $json['RuncCommit']         = $this->runcCommit;
        }
        if (isset($this->runtimes)) {
            $json['Runtimes']           = $this->runtimes;
        }
        if (isset($this->securityOptions)) {
            $json['SecurityOptions']    = $this->securityOptions;
        }
        if (isset($this->serverVersion)) {
            $json['ServerVersion']      = $this->serverVersion;
        }
        if (isset($this->swapLimit)) {
            $json['SwapLimit']          = $this->swapLimit;
        }
        if (isset($this->swarm)) {
            $json['Swarm']              = $this->swarm;
        }
        if (isset($this->systemStatus)) {
            $json['SystemStatus']       = $this->systemStatus;
        }
        if (isset($this->systemTime)) {
            $json['SystemTime']         = $this->systemTime;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
