<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Tag2 implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $isCurrent;

    /**
     * @var string|null
     */
    private $tag;

    /**
     * Returns Is Current.
     * `true` if the tag currently points to this image.
     *
     * `false` if it has been overwritten to point at a different image.
     */
    public function getIsCurrent(): ?bool
    {
        return $this->isCurrent;
    }

    /**
     * Sets Is Current.
     * `true` if the tag currently points to this image.
     *
     * `false` if it has been overwritten to point at a different image.
     *
     * @maps is_current
     */
    public function setIsCurrent(?bool $isCurrent): void
    {
        $this->isCurrent = $isCurrent;
    }

    /**
     * Returns Tag.
     * The tag.
     */
    public function getTag(): ?string
    {
        return $this->tag;
    }

    /**
     * Sets Tag.
     * The tag.
     *
     * @maps tag
     */
    public function setTag(?string $tag): void
    {
        $this->tag = $tag;
    }

    /**
     * Converts the Tag2 object to a human-readable string representation.
     *
     * @return string The string representation of the Tag2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Tag2', ['isCurrent' => $this->isCurrent, 'tag' => $this->tag]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->isCurrent)) {
            $json['is_current'] = $this->isCurrent;
        }
        if (isset($this->tag)) {
            $json['tag']        = $this->tag;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
