<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

class TaskStateEnum
{
    public const NEW_ = 'new';

    public const ALLOCATED = 'allocated';

    public const PENDING = 'pending';

    public const ASSIGNED = 'assigned';

    public const ACCEPTED = 'accepted';

    public const PREPARING = 'preparing';

    public const READY = 'ready';

    public const STARTING = 'starting';

    public const RUNNING = 'running';

    public const COMPLETE = 'complete';

    public const SHUTDOWN = 'shutdown';

    public const FAILED = 'failed';

    public const REJECTED = 'rejected';

    private const _ALL_VALUES = [
        self::NEW_,
        self::ALLOCATED,
        self::PENDING,
        self::ASSIGNED,
        self::ACCEPTED,
        self::PREPARING,
        self::READY,
        self::STARTING,
        self::RUNNING,
        self::COMPLETE,
        self::SHUTDOWN,
        self::FAILED,
        self::REJECTED
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for TaskStateEnum.");
    }
}
