<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class TaskTemplate implements \JsonSerializable
{
    /**
     * @var ContainerSpec2|null
     */
    private $containerSpec;

    /**
     * @var int|null
     */
    private $forceUpdate;

    /**
     * @var LogDriver12|null
     */
    private $logDriver;

    /**
     * @var Network2[]|null
     */
    private $networks;

    /**
     * @var Placement|null
     */
    private $placement;

    /**
     * @var PluginSpec2|null
     */
    private $pluginSpec;

    /**
     * @var Resources2|null
     */
    private $resources;

    /**
     * @var RestartPolicy2|null
     */
    private $restartPolicy;

    /**
     * @var string|null
     */
    private $runtime;

    /**
     * Returns Container Spec.
     */
    public function getContainerSpec(): ?ContainerSpec2
    {
        return $this->containerSpec;
    }

    /**
     * Sets Container Spec.
     *
     * @maps ContainerSpec
     */
    public function setContainerSpec(?ContainerSpec2 $containerSpec): void
    {
        $this->containerSpec = $containerSpec;
    }

    /**
     * Returns Force Update.
     * A counter that triggers an update even if no relevant parameters have been changed.
     */
    public function getForceUpdate(): ?int
    {
        return $this->forceUpdate;
    }

    /**
     * Sets Force Update.
     * A counter that triggers an update even if no relevant parameters have been changed.
     *
     * @maps ForceUpdate
     */
    public function setForceUpdate(?int $forceUpdate): void
    {
        $this->forceUpdate = $forceUpdate;
    }

    /**
     * Returns Log Driver.
     */
    public function getLogDriver(): ?LogDriver12
    {
        return $this->logDriver;
    }

    /**
     * Sets Log Driver.
     *
     * @maps LogDriver
     */
    public function setLogDriver(?LogDriver12 $logDriver): void
    {
        $this->logDriver = $logDriver;
    }

    /**
     * Returns Networks.
     *
     * @return Network2[]|null
     */
    public function getNetworks(): ?array
    {
        return $this->networks;
    }

    /**
     * Sets Networks.
     *
     * @maps Networks
     *
     * @param Network2[]|null $networks
     */
    public function setNetworks(?array $networks): void
    {
        $this->networks = $networks;
    }

    /**
     * Returns Placement.
     */
    public function getPlacement(): ?Placement
    {
        return $this->placement;
    }

    /**
     * Sets Placement.
     *
     * @maps Placement
     */
    public function setPlacement(?Placement $placement): void
    {
        $this->placement = $placement;
    }

    /**
     * Returns Plugin Spec.
     */
    public function getPluginSpec(): ?PluginSpec2
    {
        return $this->pluginSpec;
    }

    /**
     * Sets Plugin Spec.
     *
     * @maps PluginSpec
     */
    public function setPluginSpec(?PluginSpec2 $pluginSpec): void
    {
        $this->pluginSpec = $pluginSpec;
    }

    /**
     * Returns Resources.
     */
    public function getResources(): ?Resources2
    {
        return $this->resources;
    }

    /**
     * Sets Resources.
     *
     * @maps Resources
     */
    public function setResources(?Resources2 $resources): void
    {
        $this->resources = $resources;
    }

    /**
     * Returns Restart Policy.
     */
    public function getRestartPolicy(): ?RestartPolicy2
    {
        return $this->restartPolicy;
    }

    /**
     * Sets Restart Policy.
     *
     * @maps RestartPolicy
     */
    public function setRestartPolicy(?RestartPolicy2 $restartPolicy): void
    {
        $this->restartPolicy = $restartPolicy;
    }

    /**
     * Returns Runtime.
     * Runtime is the type of runtime specified for the task executor.
     */
    public function getRuntime(): ?string
    {
        return $this->runtime;
    }

    /**
     * Sets Runtime.
     * Runtime is the type of runtime specified for the task executor.
     *
     * @maps Runtime
     */
    public function setRuntime(?string $runtime): void
    {
        $this->runtime = $runtime;
    }

    /**
     * Converts the TaskTemplate object to a human-readable string representation.
     *
     * @return string The string representation of the TaskTemplate object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TaskTemplate',
            [
                'containerSpec' => $this->containerSpec,
                'forceUpdate' => $this->forceUpdate,
                'logDriver' => $this->logDriver,
                'networks' => $this->networks,
                'placement' => $this->placement,
                'pluginSpec' => $this->pluginSpec,
                'resources' => $this->resources,
                'restartPolicy' => $this->restartPolicy,
                'runtime' => $this->runtime
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->containerSpec)) {
            $json['ContainerSpec'] = $this->containerSpec;
        }
        if (isset($this->forceUpdate)) {
            $json['ForceUpdate']   = $this->forceUpdate;
        }
        if (isset($this->logDriver)) {
            $json['LogDriver']     = $this->logDriver;
        }
        if (isset($this->networks)) {
            $json['Networks']      = $this->networks;
        }
        if (isset($this->placement)) {
            $json['Placement']     = $this->placement;
        }
        if (isset($this->pluginSpec)) {
            $json['PluginSpec']    = $this->pluginSpec;
        }
        if (isset($this->resources)) {
            $json['Resources']     = $this->resources;
        }
        if (isset($this->restartPolicy)) {
            $json['RestartPolicy'] = $this->restartPolicy;
        }
        if (isset($this->runtime)) {
            $json['Runtime']       = $this->runtime;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
