<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class ThrottleDevice implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $path;

    /**
     * @var int|null
     */
    private $rate;

    /**
     * Returns Path.
     * Device path
     */
    public function getPath(): ?string
    {
        return $this->path;
    }

    /**
     * Sets Path.
     * Device path
     *
     * @maps Path
     */
    public function setPath(?string $path): void
    {
        $this->path = $path;
    }

    /**
     * Returns Rate.
     * Rate
     */
    public function getRate(): ?int
    {
        return $this->rate;
    }

    /**
     * Sets Rate.
     * Rate
     *
     * @maps Rate
     */
    public function setRate(?int $rate): void
    {
        $this->rate = $rate;
    }

    /**
     * Converts the ThrottleDevice object to a human-readable string representation.
     *
     * @return string The string representation of the ThrottleDevice object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ThrottleDevice', ['path' => $this->path, 'rate' => $this->rate]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->path)) {
            $json['Path'] = $this->path;
        }
        if (isset($this->rate)) {
            $json['Rate'] = $this->rate;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
