<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class Ulimit implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $hard;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var int|null
     */
    private $soft;

    /**
     * Returns Hard.
     * Hard limit
     */
    public function getHard(): ?int
    {
        return $this->hard;
    }

    /**
     * Sets Hard.
     * Hard limit
     *
     * @maps Hard
     */
    public function setHard(?int $hard): void
    {
        $this->hard = $hard;
    }

    /**
     * Returns Name.
     * Name of ulimit
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Name of ulimit
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Soft.
     * Soft limit
     */
    public function getSoft(): ?int
    {
        return $this->soft;
    }

    /**
     * Sets Soft.
     * Soft limit
     *
     * @maps Soft
     */
    public function setSoft(?int $soft): void
    {
        $this->soft = $soft;
    }

    /**
     * Converts the Ulimit object to a human-readable string representation.
     *
     * @return string The string representation of the Ulimit object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Ulimit',
            ['hard' => $this->hard, 'name' => $this->name, 'soft' => $this->soft]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->hard)) {
            $json['Hard'] = $this->hard;
        }
        if (isset($this->name)) {
            $json['Name'] = $this->name;
        }
        if (isset($this->soft)) {
            $json['Soft'] = $this->soft;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
