<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class User implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $gID;

    /**
     * @var int|null
     */
    private $uID;

    /**
     * Returns G ID.
     */
    public function getGID(): ?int
    {
        return $this->gID;
    }

    /**
     * Sets G ID.
     *
     * @maps GID
     */
    public function setGID(?int $gID): void
    {
        $this->gID = $gID;
    }

    /**
     * Returns U ID.
     */
    public function getUID(): ?int
    {
        return $this->uID;
    }

    /**
     * Sets U ID.
     *
     * @maps UID
     */
    public function setUID(?int $uID): void
    {
        $this->uID = $uID;
    }

    /**
     * Converts the User object to a human-readable string representation.
     *
     * @return string The string representation of the User object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('User', ['gID' => $this->gID, 'uID' => $this->uID]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->gID)) {
            $json['GID'] = $this->gID;
        }
        if (isset($this->uID)) {
            $json['UID'] = $this->uID;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
