<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class V2NamespacesRepositoriesImagesSummaryResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $activeFrom;

    /**
     * @var Statistics|null
     */
    private $statistics;

    /**
     * Returns Active From.
     * Time from which an image must have been pushed or pulled to be counted as active.
     */
    public function getActiveFrom(): ?string
    {
        return $this->activeFrom;
    }

    /**
     * Sets Active From.
     * Time from which an image must have been pushed or pulled to be counted as active.
     *
     * @maps active_from
     */
    public function setActiveFrom(?string $activeFrom): void
    {
        $this->activeFrom = $activeFrom;
    }

    /**
     * Returns Statistics.
     */
    public function getStatistics(): ?Statistics
    {
        return $this->statistics;
    }

    /**
     * Sets Statistics.
     *
     * @maps statistics
     */
    public function setStatistics(?Statistics $statistics): void
    {
        $this->statistics = $statistics;
    }

    /**
     * Converts the V2NamespacesRepositoriesImagesSummaryResponse object to a human-readable string
     * representation.
     *
     * @return string The string representation of the V2NamespacesRepositoriesImagesSummaryResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'V2NamespacesRepositoriesImagesSummaryResponse',
            ['activeFrom' => $this->activeFrom, 'statistics' => $this->statistics]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->activeFrom)) {
            $json['active_from'] = $this->activeFrom;
        }
        if (isset($this->statistics)) {
            $json['statistics']  = $this->statistics;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
