<?php

declare(strict_types=1);

/*
 * DockerLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DockerLib\Models;

use DockerLib\ApiHelper;
use stdClass;

class V2UsersLoginRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $password;

    /**
     * @var string
     */
    private $username;

    /**
     * @param string $password
     * @param string $username
     */
    public function __construct(string $password, string $username)
    {
        $this->password = $password;
        $this->username = $username;
    }

    /**
     * Returns Password.
     * The password or personal access token (PAT) of the Docker Hub account to authenticate with.
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * Sets Password.
     * The password or personal access token (PAT) of the Docker Hub account to authenticate with.
     *
     * @required
     * @maps password
     */
    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    /**
     * Returns Username.
     * The username of the Docker Hub account to authenticate with.
     */
    public function getUsername(): string
    {
        return $this->username;
    }

    /**
     * Sets Username.
     * The username of the Docker Hub account to authenticate with.
     *
     * @required
     * @maps username
     */
    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    /**
     * Converts the V2UsersLoginRequest object to a human-readable string representation.
     *
     * @return string The string representation of the V2UsersLoginRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'V2UsersLoginRequest',
            ['password' => $this->password, 'username' => $this->username]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['password'] = $this->password;
        $json['username'] = $this->username;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
